<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>budgetOverageReason_textBox</name>
   <tag></tag>
   <elementGuidId>c1664cb5-adbc-416f-9180-c11d4a148488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='OverageReason'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-2-leg-909636 > #new-executive-quote-noorder > #pickup-quote-0 > div.panel-body > div.row > div.col-xs-7 > div.row > div.target-enter-quoted-amount > div.col-xs-12.target-div-overage-reason > div.target-quoted-amount-div > #OverageReason</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a9acb589-8707-416e-816b-202c4b69e8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OverageReason</value>
      <webElementGuid>29bda573-c2d5-4e1f-8d16-3c7d9444dc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OverageReason</value>
      <webElementGuid>f2f8a9c7-6bc5-4bfb-9ea7-ded82bbcbf8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909636&quot;)/div[@id=&quot;new-executive-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;target-enter-quoted-amount&quot;]/div[@class=&quot;col-xs-12 target-div-overage-reason&quot;]/div[@class=&quot;target-quoted-amount-div&quot;]/textarea[@id=&quot;OverageReason&quot;]</value>
      <webElementGuid>4c746555-b00c-42a2-b239-2880b42e252f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='OverageReason'])[10]</value>
      <webElementGuid>d127a379-bc93-4a62-875f-e79beeba7ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='pickup-quote-0']/div/div/div[3]/div/div[10]/div/div/textarea)[2]</value>
      <webElementGuid>2406893a-ee89-43bc-b996-74ad6d530c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[10]/div/div/textarea</value>
      <webElementGuid>c1419b82-344f-4c6e-be0c-f0e20b41d3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'OverageReason' and @name = 'OverageReason']</value>
      <webElementGuid>70686103-5559-421f-ad50-3544f9783832</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
