<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>electronicSignature_textBox</name>
   <tag></tag>
   <elementGuidId>19eecf3a-3b9f-4b79-8594-ed7eb22682e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FlightPlanOriginal_ElectronicSignature</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlanOriginal_ElectronicSignature']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>397971cb-6f42-4376-9838-22f8b599bcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d65aa64a-c0ce-4403-8394-82f0399e6100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a21f6ae8-197e-435a-8062-43dd2a1b60a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Electronic Signature field is required.</value>
      <webElementGuid>1148f6f4-222c-4f4c-9d9b-419759169a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlanOriginal_ElectronicSignature</value>
      <webElementGuid>29df56b5-d50c-4989-8d2e-b8428e5f9d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlanOriginal.ElectronicSignature</value>
      <webElementGuid>6999087b-1c8c-4e30-a949-e95f23dff4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c3c8c69-c381-4e82-9c2a-bbcafc09eb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlanOriginal_ElectronicSignature&quot;)</value>
      <webElementGuid>a9be14da-bd63-47eb-8bd4-ccd6dad33b41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlanOriginal_ElectronicSignature']</value>
      <webElementGuid>07f53acb-db95-405b-b5d7-d138a1a13c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ItineraryPaymentForm']/div[3]/div/div[4]/div/input</value>
      <webElementGuid>f1e7d9d0-5255-4464-80a8-524f9d100f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>01b9b6dd-df5a-4077-a5f4-e65bbd1e121e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FlightPlanOriginal_ElectronicSignature' and @name = 'FlightPlanOriginal.ElectronicSignature' and @type = 'text']</value>
      <webElementGuid>fc73ffc6-696f-43cf-bb7d-7b041652ba82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
