<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pay_button</name>
   <tag></tag>
   <elementGuidId>f367c629-02da-4a93-b226-64a655e53766</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.baj-btn.accept-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Pay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>654980de-4328-40f1-ad27-e33f59e43ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn accept-button</value>
      <webElementGuid>1ec8a6ff-5624-47d0-a939-cab46cc34b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>871913c4-252a-4be7-a801-5671f2b90c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ItineraryReview.Pay(this);</value>
      <webElementGuid>a9470bf3-3d3c-49e4-85c0-2c91d2d4ff15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pay</value>
      <webElementGuid>f629a88d-9ece-45f7-8cf1-ffe9952b1c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ItineraryPaymentForm&quot;)/div[@class=&quot;col-md-8 col-sm-12 col-xs-12 terms-conditions-margin-top&quot;]/div[@class=&quot;col-md-12 div-no-padding whitesmoke-background&quot;]/div[@class=&quot;clearfix col-xs-12 text-center&quot;]/input[@class=&quot;baj-btn accept-button&quot;]</value>
      <webElementGuid>1e572de9-99aa-4bec-91cd-ac115562f661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Pay']</value>
      <webElementGuid>ea7f0da4-1086-4e33-abcc-d24b52f10254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ItineraryPaymentForm']/div[3]/div/div[5]/input</value>
      <webElementGuid>3fcfff90-c434-494a-a755-75e4ff40214d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>15b2d064-5189-4c45-86d4-bb88db3e91b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>ceff189a-5d2e-4178-bd1a-4268fd3505ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
