<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>privacyPolicy_checkBox</name>
   <tag></tag>
   <elementGuidId>10224c3d-2407-42a2-9268-37f1581fb83e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FlightPlanOriginal_UserAgreement_PrivacyPolicy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlanOriginal_UserAgreement_PrivacyPolicy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b12ff388-a19b-4111-aaf5-6351ae3c495c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>position-absolute</value>
      <webElementGuid>c80aa1a4-5787-4a2c-9150-4094846fcf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ae3a677e-762b-4482-9515-b39e25298464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Must Agree to Privacy Policy</value>
      <webElementGuid>7443b731-3c41-4c7f-9171-446d1575925a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>fd9524ab-4d13-42fa-af8c-aaeb9b11e2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>9757a4ff-58cd-41a7-8a17-91e651091665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Privacy Policy field is required.</value>
      <webElementGuid>d8184e4b-bfef-4961-8743-1f950a3cee76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlanOriginal_UserAgreement_PrivacyPolicy</value>
      <webElementGuid>0c4b070a-24d5-4eef-86c3-9fa82f4b3fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlanOriginal.UserAgreement_PrivacyPolicy</value>
      <webElementGuid>a759dcd0-4e49-4cf4-acfd-e8c9dfcbf4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e37e33e2-352b-4740-9894-66c1bf314c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>177ed360-5abd-4630-b0e7-6cad4cb12085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlanOriginal_UserAgreement_PrivacyPolicy&quot;)</value>
      <webElementGuid>8b359df8-c8bf-46a2-8761-2a76e066ec8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlanOriginal_UserAgreement_PrivacyPolicy']</value>
      <webElementGuid>75c95f2c-9118-485c-8833-c290e6871167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ItineraryPaymentForm']/div[3]/div/div[3]/div/div/input</value>
      <webElementGuid>52e3a7f0-b8e9-4a8e-915b-101076ffa846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/input</value>
      <webElementGuid>5480af5d-aa70-42f5-ac1a-356a83dcd3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FlightPlanOriginal_UserAgreement_PrivacyPolicy' and @name = 'FlightPlanOriginal.UserAgreement_PrivacyPolicy' and @type = 'checkbox']</value>
      <webElementGuid>55fa58bd-fc78-4030-abf1-df970f9ee92c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
