<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>initialDepartureDateTime_field</name>
   <tag></tag>
   <elementGuidId>84e5bb1c-d1bc-42de-846e-2b272bbf65ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SelectedDepartureFromDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SelectedDepartureFromDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b34d603d-ca31-44e0-a5de-0d96e1688ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72dca2d2-4e52-48d4-a431-30ee566dfcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SelectedDepartureFromDate</value>
      <webElementGuid>b7409159-50af-40f1-b26b-013281931647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box target-one-loop-selected-departure-datetime date-time-picker</value>
      <webElementGuid>8edd3e0d-4295-465d-8eac-85ddb260a931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>47980c3c-533a-4210-98eb-ea8dfe5d5651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Date/Time</value>
      <webElementGuid>4b1198f2-e44a-470e-99b1-b7296ccb601e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectedDepartureFromDate&quot;)</value>
      <webElementGuid>88650633-4280-4ae1-803b-ae22a14248b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SelectedDepartureFromDate']</value>
      <webElementGuid>7f6821af-d51e-47f4-b9d8-4b2b9e867f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LoopTool']/div[2]/div/div/div/div/fieldset/div/div[4]/div[2]/div[2]/input</value>
      <webElementGuid>881a7c95-2320-4a07-895c-45f149761a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/input</value>
      <webElementGuid>b1141331-1b90-47e0-839b-d57a6771932e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'SelectedDepartureFromDate' and @placeholder = 'Select Date/Time']</value>
      <webElementGuid>58197d5d-265c-46d8-abf7-27f2a0c47995</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
