<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gender _dropDown</name>
   <tag></tag>
   <elementGuidId>f2c928ec-5daa-4a4d-b318-801933b8abf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Legs_0__Passengers_0__Gender']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_0__Gender</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a7f5c1d5-60a7-4b51-a433-63afa70a124f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control target-pax-gender</value>
      <webElementGuid>c891d823-ebb3-4ad0-a2c6-0a65cd56c3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>146fac79-e6b4-4616-a0e9-edb682602159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Gender field is required.</value>
      <webElementGuid>9211dad8-c2ba-4831-a480-6fea50180f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_0__Gender</value>
      <webElementGuid>2f812798-e0c7-482b-a918-7a2e4a67c5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[0].Gender</value>
      <webElementGuid>59543a6e-2b8d-4ebe-bf99-3934f79a84a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Gender
                                    M
                                    F
                        </value>
      <webElementGuid>f928e760-a677-43d8-8efb-e2666cb9c92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_0__Gender&quot;)</value>
      <webElementGuid>9d2564b7-3709-4ea7-9029-1de72531956a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Legs_0__Passengers_0__Gender']</value>
      <webElementGuid>28d89147-8217-4048-a07f-0af6ca696d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-1']/div[3]/div[2]/div/div[2]/div[4]/div/select</value>
      <webElementGuid>16141537-6a97-4b92-89bf-1f9a0e941b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::select[1]</value>
      <webElementGuid>134fffe9-7fd4-4053-9c08-3ff69b32d4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/preceding::select[1]</value>
      <webElementGuid>78c5f5f1-c24a-423a-9b18-333b7353f555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>77c443b4-3dae-48e3-a00e-9ca3ea126898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Legs_0__Passengers_0__Gender' and @name = 'Legs[0].Passengers[0].Gender' and (text() = '
                            Gender
                                    M
                                    F
                        ' or . = '
                            Gender
                                    M
                                    F
                        ')]</value>
      <webElementGuid>bdde6219-4455-40c3-acf1-9ea6b7e8fcdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
