<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select</name>
   <tag></tag>
   <elementGuidId>8761cb8c-0647-440a-bfd5-615486e26bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BAJ_Aircraft']/div[2]/div/div/div/div[3]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a951b0e8-aec0-4775-be63-ac84017a4677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>48cf343d-d7c9-42f2-a613-f51e56cfb36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn aircraft-select-button target-baj-button-aircraft-select</value>
      <webElementGuid>3bddf06c-787e-4d49-9b07-c763effd6e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aircraft-id</name>
      <type>Main</type>
      <value>6668</value>
      <webElementGuid>dd022bc1-b5c6-4ec2-9baa-a1d565972380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Select 
                                </value>
      <webElementGuid>9dd310c8-0918-4596-93fe-63f84aa9cddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BAJ_Aircraft&quot;)/div[@class=&quot;col-xs-12 baj-results-aircraft clearfix colNoSideMargins&quot;]/div[@class=&quot;col-xs-12 colNoSideMargins&quot;]/div[@class=&quot;media aircraftList&quot;]/div[@class=&quot;aircraftList-top&quot;]/div[@class=&quot;media-body&quot;]/div[@class=&quot;aircraft-results-right&quot;]/div[@class=&quot;bookingDetails&quot;]/a[@class=&quot;btn aircraft-select-button target-baj-button-aircraft-select&quot;]</value>
      <webElementGuid>a1bc297f-934a-4078-8aa7-105d4e6e489e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BAJ_Aircraft']/div[2]/div/div/div/div[3]/div[2]/div/a</value>
      <webElementGuid>fbadcf6a-2c19-457c-9dbc-afa004b935a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[2]</value>
      <webElementGuid>141543de-6144-4efa-8e77-6339ff103c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$70,750'])[2]/following::a[1]</value>
      <webElementGuid>efe91d71-2d2b-4a91-905d-11f31a6aa166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAFETY RATING'])[2]/following::a[1]</value>
      <webElementGuid>8b88f85d-948d-4e69-ad8f-dc77531f20cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manufacturer'])[2]/preceding::a[4]</value>
      <webElementGuid>84c74a47-5ea2-4e7b-bdfd-88ed621ec2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEXTRON AVIATION INC'])[1]/preceding::a[4]</value>
      <webElementGuid>93342582-1103-4798-8951-6fa8da37f424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[19]</value>
      <webElementGuid>9a04f871-ce79-4d71-b957-937befdd66cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div[2]/div/a</value>
      <webElementGuid>2b18736c-cf66-4379-a7ba-11b20e4fd89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '
                                    Select 
                                ' or . = '
                                    Select 
                                ')]</value>
      <webElementGuid>a078477c-fec2-4977-aba3-5c49f522f24d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
