<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_button</name>
   <tag></tag>
   <elementGuidId>0bca4f9a-20d6-4121-bc15-01b2b4cfad76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#6668 > div.aircraftDetailBox > div.row-fluid.clearfix.bg-white > a.target-img-nav-hide.target-img-nav.aircraftInfoCloseButton > i.fa.fa-window-close.fa-2x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='6668']/div/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fc06c928-da7a-4a6b-b0e4-d0d18441e92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-window-close fa-2x</value>
      <webElementGuid>307d28c1-f984-41fe-a53b-10838c65340a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b8c7e27e-004b-47aa-b4b8-688c85ac80ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6668&quot;)/div[@class=&quot;aircraftDetailBox&quot;]/div[@class=&quot;row-fluid clearfix  bg-white&quot;]/a[@class=&quot;target-img-nav-hide target-img-nav aircraftInfoCloseButton&quot;]/i[@class=&quot;fa fa-window-close fa-2x&quot;]</value>
      <webElementGuid>d30b33e4-bd48-4030-bbea-c142a6753f58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='6668']/div/div/a/i</value>
      <webElementGuid>f2023f03-97a6-420a-83f3-ffdc3692c473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/a/i</value>
      <webElementGuid>2be5d017-dbd7-485a-8c41-ee0dab826247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
