<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>manufacturer_text</name>
   <tag></tag>
   <elementGuidId>e6707a91-7379-4a14-8f6d-6b63f9b4292c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#6668 > div.aircraftDetailBox > div.row-fluid.clearfix.bg-white > div.col-xs-12.col-md-5.additional-aircraft-info-top-container > div.additional-aircraft-info-container > div.row-fluid.clearfix.additional-aircraft-info > div.additional-aircraft-info-left > ul.jet-additional-info > li > span.jet-additional-info-dd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='6668']/div/div/div[2]/div/div/div/ul/li/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>47efee8a-5acb-4093-b4cf-1e88c010a541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jet-additional-info-dd</value>
      <webElementGuid>ee7fcb07-1d73-4e7d-bea6-e40f2548dee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEXTRON AVIATION INC</value>
      <webElementGuid>be5ef12f-ca94-4fbd-bbf6-c4f201807d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6668&quot;)/div[@class=&quot;aircraftDetailBox&quot;]/div[@class=&quot;row-fluid clearfix  bg-white&quot;]/div[@class=&quot;col-xs-12 col-md-5 additional-aircraft-info-top-container&quot;]/div[@class=&quot;additional-aircraft-info-container&quot;]/div[@class=&quot;row-fluid clearfix additional-aircraft-info&quot;]/div[@class=&quot;additional-aircraft-info-left&quot;]/ul[@class=&quot;jet-additional-info&quot;]/li[1]/span[@class=&quot;jet-additional-info-dd&quot;]</value>
      <webElementGuid>65efffcb-a77b-46da-bb19-dd7d5cb52860</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='6668']/div/div/div[2]/div/div/div/ul/li/span[2]</value>
      <webElementGuid>1b97794e-f38b-4ea3-b898-88f5aed93a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manufacturer'])[2]/following::span[1]</value>
      <webElementGuid>8b7d99dc-b6b0-4cfe-b096-e4e44afde1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/following::span[2]</value>
      <webElementGuid>85ac8442-f15d-4090-914e-ceb906f7dca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model'])[2]/preceding::span[1]</value>
      <webElementGuid>46ced244-6cbf-4cbf-8fb3-216f7d4aa362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabin Height'])[2]/preceding::span[3]</value>
      <webElementGuid>f3d7634e-f35b-44b8-afe5-e38e576d7187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TEXTRON AVIATION INC']/parent::*</value>
      <webElementGuid>69f3ce1a-fbe6-4e89-88fd-df6034fdac6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/div/div/ul/li/span[2]</value>
      <webElementGuid>e497c553-bec4-4a33-8192-f8a55ab65931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TEXTRON AVIATION INC' or . = 'TEXTRON AVIATION INC')]</value>
      <webElementGuid>6a6901c5-c21d-48da-822a-ab44e8f490dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
