<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>economicAdjustmentFee_value</name>
   <tag></tag>
   <elementGuidId>6d286b32-cbb0-4f69-8602-5bf9d5f018c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ONEflightDownDropDivContents']/table/tbody/tr[2]/td[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>89e2d53f-bc47-44ee-8722-c7d4a8567b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dd-txt dd-align-r</value>
      <webElementGuid>73dbe419-8ab6-460b-ba48-ac70244b52b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-$15,647.82</value>
      <webElementGuid>3cf68c5d-3aeb-42fc-8dc5-c311467a3306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ONEflightDownDropDivContents&quot;)/table[1]/tbody[1]/tr[2]/td[@class=&quot;dd-txt dd-align-r&quot;]</value>
      <webElementGuid>f37691be-b168-4795-a6cd-ae9a8d0e4425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ONEflightDownDropDivContents']/table/tbody/tr[2]/td[6]</value>
      <webElementGuid>2d08e70c-fd64-4ad4-b9b7-852d7e71c919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='='])[2]/following::td[1]</value>
      <webElementGuid>6958a0f5-c207-4d24-9b75-8c057f14caeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-$15,647.82'])[1]/following::td[2]</value>
      <webElementGuid>a2929bd8-379e-4f2f-8210-908c59b0701b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[2]/preceding::td[1]</value>
      <webElementGuid>d3b7ee89-c851-4f27-8e1f-44d2c77130ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-$13,397.82'])[2]/preceding::td[2]</value>
      <webElementGuid>f2e839be-285f-4c59-9bdb-c6886773a67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]</value>
      <webElementGuid>30a019d4-2c5a-41cc-9903-e4317db23772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '-$15,647.82' or . = '-$15,647.82')]</value>
      <webElementGuid>02e43e3f-abe0-42b2-ad55-974b5674755c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
