<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>highDensityAirportFee_value</name>
   <tag></tag>
   <elementGuidId>031c640a-9b30-47a8-bb77-ade8af3e6ae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ONEflightDownDropDivContents']/table/tbody/tr/td[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ea8cef1c-6fa5-41eb-b0a2-46a4d9c0da22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dd-txt dd-align-r</value>
      <webElementGuid>46f2c233-0f5a-41c1-a609-7ef8cf140a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$2,250.00</value>
      <webElementGuid>9265bf90-a1f7-408d-8304-132a13ed4b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ONEflightDownDropDivContents&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;dd-txt dd-align-r&quot;]</value>
      <webElementGuid>70e57ba2-a232-4e80-a8ca-e92b96622c9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ONEflightDownDropDivContents']/table/tbody/tr/td[6]</value>
      <webElementGuid>8b51f1e8-f3ab-4386-a515-3e3e37c6843b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='='])[1]/following::td[1]</value>
      <webElementGuid>25b684d0-9b32-4617-9a71-5f85dc67f6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$750.00'])[1]/following::td[2]</value>
      <webElementGuid>9b337717-c4ca-41ae-afe0-64a3cabac104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Economic Adjustment Fee (Domestic)'])[1]/preceding::td[1]</value>
      <webElementGuid>66ede757-3433-401e-97a2-4bf757aaca84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[2]/preceding::td[3]</value>
      <webElementGuid>a15f3700-6eb4-4d12-9bfc-69207c36a172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$2,250.00']/parent::*</value>
      <webElementGuid>00d333ca-bba8-412a-843a-a766bdb18110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]</value>
      <webElementGuid>7955b4a9-c90d-4c3c-a5ef-cff370752ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$2,250.00' or . = '$2,250.00')]</value>
      <webElementGuid>2866fe49-ac30-43b5-b761-1ddadb050867</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
