<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>amount_textBox</name>
   <tag></tag>
   <elementGuidId>e41ae783-f0fa-4173-bee2-de9b57c9513b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Bill_NewBillItem_Rate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Bill_NewBillItem_Rate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fec1129-58dc-4406-bf62-c3a18866221b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Amount</value>
      <webElementGuid>8c93af26-b105-4d3f-ae90-d4622e212ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5b9ebc3a-3258-41ff-b31e-f590a8ad21cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>39c764d5-f422-4120-be6e-5be8abfef7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>b9963c7b-0141-4d63-8249-750bb844e524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c883f22c-e532-4245-a1e5-5cbb153fe956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Rate must be a number.</value>
      <webElementGuid>566e7366-8426-48c3-837d-ad19adae2256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Rate field is required.</value>
      <webElementGuid>bb8629c7-7c7c-4029-b8e2-a0e5a1bf6a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Bill_NewBillItem_Rate</value>
      <webElementGuid>e957349f-59f0-40b8-956e-b1c07087d257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Bill.NewBillItem.Rate</value>
      <webElementGuid>ba9a9866-d1c8-4698-8b90-fdc0c52c00fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Bill_NewBillItem_Rate&quot;)</value>
      <webElementGuid>089adf48-4f18-424f-949f-1210250c18a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Bill_NewBillItem_Rate']</value>
      <webElementGuid>29e44736-411a-4201-aee5-77c1ba6ca086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='newbillitem']/div/div[3]/input</value>
      <webElementGuid>7b2af04d-2047-40c0-ba78-eae64fc912e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/input</value>
      <webElementGuid>ab3336eb-b53f-46e6-af02-0c7b032b2b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Amount' and @type = 'number' and @id = 'FlightPlan_Bill_NewBillItem_Rate' and @name = 'FlightPlan.Bill.NewBillItem.Rate']</value>
      <webElementGuid>63f8f0ac-56d2-4bca-ae0f-597627011497</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
