<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>luggage_checkBox</name>
   <tag></tag>
   <elementGuidId>60bea014-3843-4164-b821-7f9171ecd847</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_2__LuggageDescriptionNone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_2__LuggageDescriptionNone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76bfa6f7-f862-4832-85e6-2797fa1a5ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom form-check-input target-luggage-nonecheckbox</value>
      <webElementGuid>4daf82e3-8a7e-438c-966d-7e96cde52b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48a08f86-b822-47d9-ae41-04e12effaa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The LuggageDescriptionNone field is required.</value>
      <webElementGuid>dbe2c8c4-6d25-4655-a0a7-e28019456743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_2__LuggageDescriptionNone</value>
      <webElementGuid>563b4f6e-4911-4e60-964c-dc0dbe492562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[2].LuggageDescriptionNone</value>
      <webElementGuid>011fbe51-03eb-47e5-85ef-504563a8015d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7cf91066-d260-4e5f-a65e-52023f9002d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c723e9d-fb17-4e0f-b136-f55d083d0605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_2__LuggageDescriptionNone&quot;)</value>
      <webElementGuid>d50266ce-cb2a-4f4f-a3b5-a15f69c23ef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_2__LuggageDescriptionNone']</value>
      <webElementGuid>822c9dd0-7c99-4a03-9bc6-3002c94c9bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div/div[3]/div/div/input)[7]</value>
      <webElementGuid>24766b88-a443-40e1-adf8-21c395908f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[5]/div/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>5bc37814-4d31-48af-97bc-ff8938545496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_2__LuggageDescriptionNone' and @name = 'Legs[2].LuggageDescriptionNone' and @type = 'checkbox']</value>
      <webElementGuid>40e3f27e-c44e-47d8-846e-e8a5852dc500</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
