<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pets_checkBox</name>
   <tag></tag>
   <elementGuidId>9d661169-21c4-464e-b021-f7961081fd76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_2__PetsDescriptionNone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_2__PetsDescriptionNone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75522895-e363-435d-bf7d-cc0be1f80379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom form-check-input target-pets-nonecheckbox</value>
      <webElementGuid>40b7632b-d045-49fe-b5d3-4117a57ff285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3bf3a848-b03e-4a3f-9579-a28c7368cda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PetsDescriptionNone field is required.</value>
      <webElementGuid>f41ef6b5-2467-4196-a563-3e1efdc4b2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_2__PetsDescriptionNone</value>
      <webElementGuid>56e29a57-443d-4b9e-8fee-df7677a34abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[2].PetsDescriptionNone</value>
      <webElementGuid>db3d846b-1c87-47af-b8f8-04cdc55976c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e528e7be-e5e6-422a-b8e0-0b8e3c51d203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3e3d9ca8-10d4-4eb0-b4c2-ec157ccdc67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_2__PetsDescriptionNone&quot;)</value>
      <webElementGuid>ce1e5822-84ac-4457-97eb-915aa8f94727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_2__PetsDescriptionNone']</value>
      <webElementGuid>e47624f5-dbda-4bb1-ab44-f6f3553aada7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div[3]/div[3]/div/div/input)[3]</value>
      <webElementGuid>8003df5b-1a3a-4430-ac4c-656e5a5edc7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[5]/div/div/div/div[3]/div[3]/div/div/input</value>
      <webElementGuid>59b711c1-b623-4001-a310-ffc0673ede55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_2__PetsDescriptionNone' and @name = 'Legs[2].PetsDescriptionNone' and @type = 'checkbox']</value>
      <webElementGuid>59e28314-a109-4a77-9fdc-119e7f35c893</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
