<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pets_textArea</name>
   <tag></tag>
   <elementGuidId>ba52bace-b95b-4c88-8d86-e9416c7a7a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_2__PetsDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Legs_2__PetsDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>35da5367-4fc1-43e8-888c-446580799bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-textarea form-control target-pets-description</value>
      <webElementGuid>a9dbf8f0-a937-45a9-a052-9a11b9d65496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>580da5a4-f839-43da-b89a-ea5457a91911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_2__PetsDescription</value>
      <webElementGuid>49925a3e-d4ac-4fb4-9f74-f32b33cb2d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[2].PetsDescription</value>
      <webElementGuid>079b2000-ff67-496b-86d4-0483a4257877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>7c91ccee-6cc4-4bc6-9ead-132117059c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_2__PetsDescription&quot;)</value>
      <webElementGuid>2fa59db7-583c-40f2-94ee-e7e281c91a78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Legs_2__PetsDescription']</value>
      <webElementGuid>8f2cfdd4-e0de-4447-8e45-cf0e380c3a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div[3]/div[5]/textarea)[3]</value>
      <webElementGuid>2c2e0dfe-fd4d-49cb-8c37-16a03378188b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[5]/div/div/div/div[3]/div[5]/textarea</value>
      <webElementGuid>6e43978d-94ac-4d1c-95d7-0f468bb8e906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Legs_2__PetsDescription' and @name = 'Legs[2].PetsDescription']</value>
      <webElementGuid>b5e76815-2ce4-4664-8167-5981ae3bbec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
