<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>serviceFee_textBox</name>
   <tag></tag>
   <elementGuidId>206b6903-6905-4843-9e7c-152cee46f290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='ClientConciergePayment_ClientConciergePaymentReason_ServiceFee'])[17]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab9b744e-9cde-4b03-85df-f682cfa9eb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2d27f447-e9f0-4b52-826d-5fb6bdb6312f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>6b541ff1-d6ef-448d-97ae-d7c8f3570098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4c37cdc0-7f53-47d8-bb32-c2856b82512c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tight-input target-service-fee</value>
      <webElementGuid>d55cf2d6-d86d-455f-b155-59d8cd72000c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ClientConciergePayment_ClientConciergePaymentReason_ServiceFee</value>
      <webElementGuid>b72aa4a4-d7c0-47d1-bcfc-ab9fa7ea11dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ClientConciergePayment.ClientConciergePaymentReason.ServiceFee</value>
      <webElementGuid>ec05a290-0d81-40fd-851b-8f9e82af20b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909637&quot;)/div[@id=&quot;new-executive-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;target-concierge-payment-div&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@id=&quot;target-client-concierge-payment-2-0&quot;]/table[1]/tbody[1]/tr[2]/td[2]/input[@id=&quot;ClientConciergePayment_ClientConciergePaymentReason_ServiceFee&quot;]</value>
      <webElementGuid>32009ee9-0863-4cb8-ae6c-cdbbd5e7289d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='ClientConciergePayment_ClientConciergePaymentReason_ServiceFee'])[17]</value>
      <webElementGuid>0defef20-7447-425b-8c0c-648bf21c3649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='target-client-concierge-payment-2-0']/table/tbody/tr[2]/td[2]/input)[6]</value>
      <webElementGuid>e45f4f1f-8c5a-44bd-92ff-93051bd50b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[11]/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>6a3fcd43-2dc2-495b-bde9-3ab436e8bb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'ClientConciergePayment_ClientConciergePaymentReason_ServiceFee' and @name = 'ClientConciergePayment.ClientConciergePaymentReason.ServiceFee']</value>
      <webElementGuid>e1795e5a-a48d-4338-ad27-13f660868db4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
