<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectPassenger_dropDown</name>
   <tag></tag>
   <elementGuidId>0ecec37e-5948-4547-a548-c78285d4544e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Legs_0__Passengers_0__GuestId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_0__GuestId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ad13657e-37b5-49f1-aa3b-5bccbd74e85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control target-baj-results-passenger-my-guest-select l1p1</value>
      <webElementGuid>219687a8-22fb-4cc4-9724-774c075acf03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-guest-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9a0ffafb-4091-4285-899a-4c57cf50097e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0bb3e624-7ac8-4697-9d4b-00b53f901fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-number-of-legs</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8435bb1c-2f43-4424-8ce4-9dced7ca1b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-class</name>
      <type>Main</type>
      <value>l1p1</value>
      <webElementGuid>0b117691-1cdc-4fc3-8bf8-b685034a998b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-number</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>40a4ac0c-0057-4787-911e-59ca76d10f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_0__GuestId</value>
      <webElementGuid>7f945ee3-c4f9-482f-b2cc-a88c4652ad4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[0].GuestId</value>
      <webElementGuid>329cebf3-fc5e-40b5-b53c-ec60a430b136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Passenger
</value>
      <webElementGuid>16794e81-f279-44be-895e-1937a28b1797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passengercontainer-leg-1-number-1&quot;)/div[@class=&quot;clearfix baj-results-pax-grid-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-4 target-baj-results-passenger-my-guest-select-div l1p1&quot;]/select[@id=&quot;Legs_0__Passengers_0__GuestId&quot;]</value>
      <webElementGuid>81fdbdf2-b798-4457-ac87-870804770e31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Legs_0__Passengers_0__GuestId']</value>
      <webElementGuid>7bf431d4-1f95-4507-b521-fca99ff47d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-1']/div[3]/div/div[2]/select</value>
      <webElementGuid>e0fd1160-b940-4eb7-96f9-990f22f92b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leg3'])[1]/following::select[1]</value>
      <webElementGuid>71639756-f78f-469d-888c-95898506f4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger Information'])[1]/preceding::select[1]</value>
      <webElementGuid>babc8699-ec3f-43f0-b7e2-21764338248d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>fa6b8b5b-9c92-4b0e-ba23-8cf2cfec4c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Legs_0__Passengers_0__GuestId' and @name = 'Legs[0].Passengers[0].GuestId' and (text() = 'Select Passenger
' or . = 'Select Passenger
')]</value>
      <webElementGuid>a139741e-5f68-4e21-b0b4-a607aee64aff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
