<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>leg3_checkBox</name>
   <tag></tag>
   <elementGuidId>5a26c152-c2e5-4b7a-bfa5-4b3c15bd8d1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[17]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb912094-cdc0-400b-8113-968b9c542804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-operator-quote-group-select cursor</value>
      <webElementGuid>442520ac-1e82-433d-a0ac-e170147f2b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-id</name>
      <type>Main</type>
      <value>909579</value>
      <webElementGuid>ca4a227c-9525-4659-b7dc-3703b34283ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-operator-quote-id</name>
      <type>Main</type>
      <value>137426</value>
      <webElementGuid>e572968e-9147-49a9-9cdf-bb6485734e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b7eb0db8-975d-4f62-a841-4732ed5f9caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-op-quote-form&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-xs-12 target-leg-operator-quotes-group&quot;]/div[@class=&quot;target-leg-quotes-div&quot;]/input[@class=&quot;target-operator-quote-group-select cursor&quot;]</value>
      <webElementGuid>4948f237-3455-42cf-8ff0-4f52f6981b2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[17]</value>
      <webElementGuid>1ae3fd5f-713f-47e4-b8ad-bfbcf9805f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='target-op-quote-form']/div/div/div/div[3]/div[2]/input</value>
      <webElementGuid>7ba31574-68cd-4ce7-9aea-8a6257f3e9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div[3]/div[2]/input</value>
      <webElementGuid>d16c999e-a509-4ff0-8422-958ee59494f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>c7821e19-1f63-42d9-b0b2-7c7857dae8f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
