<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cancel_button</name>
   <tag></tag>
   <elementGuidId>7f7665e0-d81b-4cb0-91f2-6f630f0d747b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Cancel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.target-cancel-modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e71de3d-8a1e-464d-9de8-00a7bc9b534e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4599ae25-bc08-4a50-bf22-4d1caa03d433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>110982ff-6d7f-43be-8316-df98666158ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary target-cancel-modal</value>
      <webElementGuid>8c6a22bd-2f5c-4d16-b1b4-c6001ce79138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-edit-loop-item-form&quot;)/div[@class=&quot;row text-center&quot;]/input[@class=&quot;btn btn-primary target-cancel-modal&quot;]</value>
      <webElementGuid>34b18050-a039-49f1-8120-0176f8f4b787</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Cancel']</value>
      <webElementGuid>41e1bbca-0791-4b97-878b-b65738d84469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='target-edit-loop-item-form']/div[3]/input[2]</value>
      <webElementGuid>fde903d1-11df-4e68-abce-b7870eb78f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/input[2]</value>
      <webElementGuid>7f80fcdb-f670-4107-8f0a-c5e66ce017d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>94211adc-380b-49bf-9d5f-a559f65663ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
