<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>departTo_field</name>
   <tag></tag>
   <elementGuidId>4e36620f-a775-4e3b-be38-21a55e562819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DepartureToDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DepartureToDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b844bd6-a558-45a7-b47e-01e1bd716e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9b37cc1-8329-4754-bda0-a81e235d435e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box input-date target-one-loop-to-date date-picker</value>
      <webElementGuid>1752c68e-7513-427b-b457-6377becc4c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DepartureToDate</value>
      <webElementGuid>ec1312e5-df89-4d22-b8c0-5133dfb2d682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>03/17/2023</value>
      <webElementGuid>81ff7794-d844-4563-866f-e0330d220944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DepartureToDate&quot;)</value>
      <webElementGuid>76a95bb7-c723-46ff-8e66-254f9fd6650a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DepartureToDate']</value>
      <webElementGuid>06d4329c-3f5f-4480-bf78-89186e676ff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LoopTool']/div[2]/div/div/div/div/fieldset[2]/div/div/div[2]/input</value>
      <webElementGuid>f15cec85-c821-4a90-bcfb-285d359ad9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div/div[2]/input</value>
      <webElementGuid>08b0ec79-8635-43ef-9458-04e96790a274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DepartureToDate']</value>
      <webElementGuid>fb07ffea-f91b-4db6-a461-61a42b794aeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
