<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>departFrom_field</name>
   <tag></tag>
   <elementGuidId>bfade446-85ec-4dbf-8472-bb8f263bd2d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DepartureFromDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DepartureFromDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2af2e625-79dc-4013-9038-85eba9b0b867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d4e3564-ee61-4239-87cd-5e22e16a125c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box input-date target-one-loop-from-date date-picker</value>
      <webElementGuid>3d134ef8-3831-411c-ade9-08dcafc0c9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DepartureFromDate</value>
      <webElementGuid>6168dcd5-e9b8-40e9-b21d-f70dc31662eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>03/10/2023</value>
      <webElementGuid>45549762-5b36-4782-8b19-c8f25d452d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DepartureFromDate&quot;)</value>
      <webElementGuid>4ba3f988-024f-4536-b7c0-a7ae1d69aa18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DepartureFromDate']</value>
      <webElementGuid>71b60253-f3b9-4812-832d-643cdef3c38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LoopTool']/div[2]/div/div/div/div/fieldset[2]/div/div/div/input</value>
      <webElementGuid>4431dcb7-9a6f-4d06-b5b2-e86f60e04101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div/div/input</value>
      <webElementGuid>c539899b-ea1b-487a-84b2-728ad839874a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DepartureFromDate']</value>
      <webElementGuid>2e3ac056-1e1b-4ef5-b2d4-59a1cb790aa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
