<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addFStop_icon</name>
   <tag></tag>
   <elementGuidId>f856259f-88ef-481b-92fb-fe0f8ee7fb42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#target-leg_909768-fuel-stops-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='target-leg_909768-fuel-stops-info']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d6ff8206-7257-4ee3-b886-08188059bbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus-circle target-expand-leg-fuel-stops cursor</value>
      <webElementGuid>aca80da1-d598-4b62-b1db-9bdf496394e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-id</name>
      <type>Main</type>
      <value>909768</value>
      <webElementGuid>82b55c8b-8dd0-45ff-84e1-9ab09bdf039e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>target-leg_909768-fuel-stops-info</value>
      <webElementGuid>32e6cc04-765a-4695-9f0e-461ffa95f23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-leg_909768-fuel-stops-info&quot;)</value>
      <webElementGuid>0969ca42-3c55-4a51-9a8b-7b198acdd73c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='target-leg_909768-fuel-stops-info']</value>
      <webElementGuid>ce95833b-6166-412e-90cb-c6b49141a823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909768']/div[5]/span/i</value>
      <webElementGuid>5c4a5fad-183a-4451-af03-3ec202d3759b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/span/i</value>
      <webElementGuid>5758f596-e9f9-4025-9913-4507c05c8167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'target-leg_909768-fuel-stops-info']</value>
      <webElementGuid>9a28d9dc-1f1e-4f1e-864b-9ad161c58ad7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
