<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_textBox</name>
   <tag></tag>
   <elementGuidId>1a0b1a47-a1d1-40f3-bce5-cd1ef3a2ae87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_2__OriginDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_2__OriginDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2259403f-6c9d-4603-bdf7-541feea5930c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-date-picker black-tighter-input target-flight-plan-input-origin-date form-control hasDatepicker</value>
      <webElementGuid>004f7435-69ff-4321-b5d8-f5ba74aa016b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>64bd42f1-7de6-4165-be93-82bce45ef07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Date/Time field is required.</value>
      <webElementGuid>69dfc75d-9d4d-4fe1-ae89-3b4800706c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_2__OriginDate</value>
      <webElementGuid>1cae8372-20d6-4fb2-bed6-2c7a3349434a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[2].OriginDate</value>
      <webElementGuid>0cf49cf7-6976-4c45-8b71-9f48d7bc17fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>371ad1b1-f54b-43cd-9f7d-a09cbf748631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>05/09/2023</value>
      <webElementGuid>1adb24e1-fa07-4e91-baa5-643207e6db10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_2__OriginDate&quot;)</value>
      <webElementGuid>964740cc-e79e-4d76-ad83-eae3f611b8b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_2__OriginDate']</value>
      <webElementGuid>66ef8f67-76ce-40ad-8ada-3f0466568f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909768']/div[6]/input</value>
      <webElementGuid>2e7b3ccd-9d65-4b46-9763-b8c726d71ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/div[6]/input</value>
      <webElementGuid>a44ac420-76d1-4fdf-8e74-16e83c106df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_2__OriginDate' and @name = 'Legs[2].OriginDate' and @type = 'text']</value>
      <webElementGuid>2a24e267-7e5d-4519-8029-63f72186c1f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
