<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>from_textBox</name>
   <tag></tag>
   <elementGuidId>42d50f17-3625-4ed5-b8a0-932a05a67d4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_2__AirportOriginIdent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_2__AirportOriginIdent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41a1175d-4ad5-4682-82a1-c2dbee18100f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-airport-entry black-tighter-input form-control ui-autocomplete-input</value>
      <webElementGuid>87823cef-6a15-42ce-b8f4-30f24205e3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_2__AirportOriginIdent</value>
      <webElementGuid>37d6b49f-cf6f-4663-810d-3b0652f728d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[2].AirportOriginIdent</value>
      <webElementGuid>3c22b467-668c-46ab-9433-0fa1f73f629e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12b25124-b96f-4ddc-a00d-65e6f29c92ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>KDEN</value>
      <webElementGuid>98b1e6a1-c308-41d2-a27e-fe95c3ceb8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9b152f54-c5b6-4026-9091-a6cadfa2917a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_2__AirportOriginIdent&quot;)</value>
      <webElementGuid>1523bd2e-ee00-472b-b7b3-93e03ec58455</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_2__AirportOriginIdent']</value>
      <webElementGuid>f1213ded-06b8-4004-8cd3-88c0b8d328ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909768']/div[3]/input</value>
      <webElementGuid>8038a10b-7a7e-4353-be8f-73c1ade3c338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div[3]/div[3]/input</value>
      <webElementGuid>f5c292c0-1994-4699-a527-d138f275c8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_2__AirportOriginIdent' and @name = 'Legs[2].AirportOriginIdent' and @type = 'text']</value>
      <webElementGuid>8c044693-5f0b-42fb-baa5-f4f2f14328b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
