<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>to_textBox</name>
   <tag></tag>
   <elementGuidId>62031f9d-ab05-43b2-8f31-1e6d22ad2547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_2__AirportDestinationIdent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_2__AirportDestinationIdent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2db21d97-aaa0-458e-8d95-645c1d650be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-airport-entry black-tighter-input form-control ui-autocomplete-input</value>
      <webElementGuid>0faa24c7-d356-407d-803e-d7bacdadaafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_2__AirportDestinationIdent</value>
      <webElementGuid>0aff0799-44fa-44a6-9802-e15d042e8e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[2].AirportDestinationIdent</value>
      <webElementGuid>c9cfce09-2c11-466b-91db-a361cddcb4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39596b6b-829d-4808-b471-852faf4713db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>KMIA</value>
      <webElementGuid>5b65f374-b247-4bed-8cd4-1f5d005bc7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bd9a8a11-cfed-4d59-8dd4-2b0151e49107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_2__AirportDestinationIdent&quot;)</value>
      <webElementGuid>b6ebb732-eb74-43e4-973a-eb8343802356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_2__AirportDestinationIdent']</value>
      <webElementGuid>bd63d338-4fbe-48b2-84ba-9baf2f70d372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909768']/div[4]/input</value>
      <webElementGuid>d0f38d0e-eba5-4e87-a6ed-384940bc804d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div[3]/div[4]/input</value>
      <webElementGuid>ad394e21-de73-4345-a2e3-bcc70b215715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_2__AirportDestinationIdent' and @name = 'Legs[2].AirportDestinationIdent' and @type = 'text']</value>
      <webElementGuid>428fd654-f97d-4f60-be8d-c3464f8c8766</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
