<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>birdDate_dropDown</name>
   <tag></tag>
   <elementGuidId>58378129-744c-4937-87ed-cbefb9e91724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Legs_0__Passengers_1__BirthDate_Month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_1__BirthDate_Month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>291792f4-409b-4fdc-b0b2-c4fabbd54f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control float-left target-birthdate-el target-pax-birthmonth</value>
      <webElementGuid>41ce152c-b555-4b62-b8a1-ca0f9ccc49d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e701161-9fde-4054-824c-3fe2635fe9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The BirthDate_Month field is required.</value>
      <webElementGuid>d3e72bdb-b392-4303-8f01-c58e809d16ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_1__BirthDate_Month</value>
      <webElementGuid>91b1945f-416a-468f-8c2a-2e2c8b756f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[1].BirthDate_Month</value>
      <webElementGuid>4b892d8d-0153-48f8-874a-ec3115c95412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Month
                                        Jan
                                        Feb
                                        Mar
                                        Apr
                                        May
                                        Jun
                                        Jul
                                        Aug
                                        Sep
                                        Oct
                                        Nov
                                        Dec
                            </value>
      <webElementGuid>e1fa1923-bc66-477f-8ea8-ff361b8a04dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_1__BirthDate_Month&quot;)</value>
      <webElementGuid>d1880a65-858b-4ece-897d-382cda46ffcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Legs_0__Passengers_1__BirthDate_Month']</value>
      <webElementGuid>a53f8ea2-c1f3-480a-95d8-8a18b016fca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-2']/div[3]/div[2]/div/div[2]/div/div/div[2]/select</value>
      <webElementGuid>54563e29-c803-4b0c-a93d-734861c8d162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birth Date'])[2]/following::select[1]</value>
      <webElementGuid>73669c6e-b304-4957-9a8e-2d03b0c6dd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[5]/preceding::select[2]</value>
      <webElementGuid>a22e41b4-d2c1-4c7c-b004-f31a123b262a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div/div[2]/div/div/div[2]/select</value>
      <webElementGuid>33ba5033-0da8-48ca-8c01-dd7f741cb0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Legs_0__Passengers_1__BirthDate_Month' and @name = 'Legs[0].Passengers[1].BirthDate_Month' and (text() = '
                                Month
                                        Jan
                                        Feb
                                        Mar
                                        Apr
                                        May
                                        Jun
                                        Jul
                                        Aug
                                        Sep
                                        Oct
                                        Nov
                                        Dec
                            ' or . = '
                                Month
                                        Jan
                                        Feb
                                        Mar
                                        Apr
                                        May
                                        Jun
                                        Jul
                                        Aug
                                        Sep
                                        Oct
                                        Nov
                                        Dec
                            ')]</value>
      <webElementGuid>8140757f-45fa-41c1-813c-d680e29a96ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
