<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>middle_textBox</name>
   <tag></tag>
   <elementGuidId>246e4169-a8dc-4a82-9383-e7510f88214c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__Passengers_1__MiddleName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_1__MiddleName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e08f263d-9897-4938-bce1-90aa52b8e5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>f79510e7-fdac-4687-bdc6-45be5e304ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control target-pax-middlename</value>
      <webElementGuid>09533d0b-d056-40f4-a0fb-205f755637a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f9eb62a-69b1-4c87-b093-d1c7e6b4233f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c0bf0ffc-ee59-433c-bb57-d1aaedc727f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Middle must be a string or array type with a maximum length of '64'.</value>
      <webElementGuid>19c58db7-60d6-4234-a32b-6da06cd3c5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>72fc7aff-933b-44df-a70f-36ad21987cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_1__MiddleName</value>
      <webElementGuid>4f5d4bfb-cae7-4756-949d-177657eda04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>85df656e-4840-48f1-a8a5-3ab81d97089f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[1].MiddleName</value>
      <webElementGuid>3732266b-a2f1-4502-90fb-634ad615cdf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_1__MiddleName&quot;)</value>
      <webElementGuid>7b76143f-0790-4192-b44c-79d5af0f00a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__Passengers_1__MiddleName']</value>
      <webElementGuid>c6e491b2-73ce-404b-aa36-e0218ae76925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-2']/div[3]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>5bddb12e-3a63-4c5c-b1f3-9878fa95fee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>db485848-a827-422d-a49c-e1dae0b39225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Legs_0__Passengers_1__MiddleName' and @name = 'Legs[0].Passengers[1].MiddleName']</value>
      <webElementGuid>c68725a6-8bf5-4bb0-80c2-50fe0e825779</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
