<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pets_checkBox</name>
   <tag></tag>
   <elementGuidId>2fb49be7-7749-4938-8d37-39b423438167</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_2__PetsDescriptionNone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_2__PetsDescriptionNone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22ac6d1d-e5b5-4fd3-898c-3bbf68af7c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom form-check-input target-pets-nonecheckbox</value>
      <webElementGuid>020b7e8a-5bce-4eec-9810-c08d691f70cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1dd9e597-f65d-412c-b2bb-b13a4d7c7f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PetsDescriptionNone field is required.</value>
      <webElementGuid>4bd5e6b6-3bea-49d6-b369-7102247bf4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_2__PetsDescriptionNone</value>
      <webElementGuid>ae4074b7-06eb-4b9e-b277-2aa3593b883e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[2].PetsDescriptionNone</value>
      <webElementGuid>7e846f14-35e8-4da7-8afe-dde614923885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1d23a38a-7035-4517-b7c0-3dcd41574e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6746431f-8328-41ec-a677-09a43361d45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_2__PetsDescriptionNone&quot;)</value>
      <webElementGuid>1feb9291-7b66-4873-abdf-b234a4ae0fdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_2__PetsDescriptionNone']</value>
      <webElementGuid>fd055d3b-087c-4154-be8b-3cfe6bc8d80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div[3]/div[3]/div/div/input)[3]</value>
      <webElementGuid>874d525f-16fa-4196-85fb-d2ee469d54dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/div/div/div/div[3]/div[3]/div/div/input</value>
      <webElementGuid>c5fc08a8-fdc8-4ba4-9015-99eaa34d1d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_2__PetsDescriptionNone' and @name = 'Legs[2].PetsDescriptionNone' and @type = 'checkbox']</value>
      <webElementGuid>9b077fbf-b17a-481a-8df9-38ff2591113c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
