<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pets_textBox</name>
   <tag></tag>
   <elementGuidId>6caa3b3a-c087-4bb8-8c46-875b401f0882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Legs_2__PetsDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_2__PetsDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e48b983d-1df1-4894-8af3-9d6eb7d6207f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-textarea form-control target-pets-description</value>
      <webElementGuid>8045656c-0d70-49aa-a946-d28fe3773d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>442dd6cb-874f-4b8f-b503-e95d5dc162f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_2__PetsDescription</value>
      <webElementGuid>64eea7ef-414d-4085-b442-973a26175f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[2].PetsDescription</value>
      <webElementGuid>6c97a20e-6754-410c-93ff-58df111634ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>5d7d6472-ebbf-4f88-bd57-bff22ac388f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_2__PetsDescription&quot;)</value>
      <webElementGuid>f583be27-4e4c-4685-9dfa-e08f92ae9227</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Legs_2__PetsDescription']</value>
      <webElementGuid>37e57246-8400-475c-a80a-65a3a567c913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div[3]/div[5]/textarea)[3]</value>
      <webElementGuid>2f774b76-fa39-433d-ab6e-7555a9e76a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/div/div/div/div[3]/div[5]/textarea</value>
      <webElementGuid>1379e9bf-ec37-41a3-b277-ca8cf1c384f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Legs_2__PetsDescription' and @name = 'Legs[2].PetsDescription']</value>
      <webElementGuid>f3cd2075-b914-4a87-adcb-0a7c8df15a31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
