<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save_button</name>
   <tag></tag>
   <elementGuidId>1670d9d3-025f-484c-81d9-c5a4d564e2bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Save'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-12.continue-to-concierge.text-center > input.baj-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39efcb0c-2032-46ed-aeff-6b0cfc9ef6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>773e6612-c763-4cac-80da-3e11ecefe19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>afb96a64-f937-4f50-b6f2-8d67beda4634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn</value>
      <webElementGuid>b51d5f9b-5abe-4953-9eb6-942b65e3e8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SaveLuggageFirearmsPets(this);</value>
      <webElementGuid>d04577a0-5750-4a6f-b93d-d2621f8d92ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ams-passenger-form&quot;)/div[@class=&quot;tab-content&quot;]/div[@class=&quot;col-xs-12 continue-to-concierge text-center&quot;]/input[@class=&quot;baj-btn&quot;]</value>
      <webElementGuid>4ebad2d4-89b3-4eab-bc84-c0b096e8e932</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Save'])[2]</value>
      <webElementGuid>337dae9b-c1bf-42c2-9570-5c7b0bd9eddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ams-passenger-form']/div/div[4]/input</value>
      <webElementGuid>9d57ce70-ed88-4ef6-85fc-f332adec2aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[4]/input</value>
      <webElementGuid>ebd8371f-dfd4-4d65-9fed-e487fa2d3ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>eb4d243a-dcbe-4448-8ecc-be7888d671d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
