<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sendClientReminder_button</name>
   <tag></tag>
   <elementGuidId>e291e282-3e1c-48f1-a19e-985004761f6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.btn-flight-plan.target-send-reminder-to-client.margin-left-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Send Client Reminder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>764517a8-4186-4787-9354-e69cdff474a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c0bd2a1-678c-4cbe-a7e1-f045c4bfb9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Send Client Reminder</value>
      <webElementGuid>08b737fd-f677-433c-9427-7ed5f70ed484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flightplanid</name>
      <type>Main</type>
      <value>580433</value>
      <webElementGuid>cfa64e52-3766-4a61-a84c-486bac8cd85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-flight-plan target-send-reminder-to-client margin-left-5</value>
      <webElementGuid>1af08d6d-688f-41e2-ad0e-fc7d99249648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;content target-flight-plan-main&quot;]/div[@class=&quot;row ams-workflow-container&quot;]/div[@class=&quot;col-xs-8 target-flight-plan-trip-request-main&quot;]/div[@class=&quot;content target-flight-plan-trip-request-aircraft-list request-list&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;col-xs-6 target-select-recipients&quot;]/div[@class=&quot;row&quot;]/input[@class=&quot;btn btn-primary btn-flight-plan target-send-reminder-to-client margin-left-5&quot;]</value>
      <webElementGuid>137408fe-3356-498d-b608-59f8f45b771c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Send Client Reminder']</value>
      <webElementGuid>c3d3c34f-693c-4fea-aa87-e995b6f71c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div[2]/div[3]/div/div/div[4]/input</value>
      <webElementGuid>a34ae8c0-bf90-437a-a89c-acb40ea419fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div[4]/input</value>
      <webElementGuid>8bda8cc9-7a30-4abd-b5fe-e8f92991a117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>7d3c039d-8043-4255-aa6e-2233042b66ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
