<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firstFlight_link</name>
   <tag></tag>
   <elementGuidId>64ead313-631a-411f-bd97-00a639bdff77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flight-plan-list']/div/table/tbody/tr/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ams-table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8ca9481c-61f9-405b-bb90-c05a88fff20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flight-plan-id</name>
      <type>Main</type>
      <value>580012</value>
      <webElementGuid>18ae18d8-4ccf-46fa-ad6f-124ce530dd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ams-table</value>
      <webElementGuid>61638cb3-654c-4829-a513-a0c9930f1865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Ams/ClientDetail/67819?loadFlightPlanId=580012&amp;tempApp=app#Flights</value>
      <webElementGuid>d1b83187-9b34-4f32-96ad-72e71216c32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NR23031411</value>
      <webElementGuid>3fc10062-fc48-47ca-9872-78b759229ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Flights&quot;)/div[@class=&quot;target-flight-plan-flight-list&quot;]/div[@class=&quot;target-spf-div&quot;]/div[@class=&quot;member-access-form&quot;]/div[@id=&quot;flight-plan-list&quot;]/div[@id=&quot;flight-plan-list&quot;]/div[@class=&quot;member-access-form&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;target-flight-plan-row&quot;]/td[@class=&quot;no-wrap&quot;]/a[@class=&quot;ams-table&quot;]</value>
      <webElementGuid>c283587f-c9d0-4557-b149-1d53529664c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flight-plan-list']/div/table/tbody/tr/td[3]/a</value>
      <webElementGuid>a085dc82-dbc6-4c8f-8f93-59a7403273c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NR23031411')]</value>
      <webElementGuid>24ca8a13-d9fc-4585-991e-0a04dc3592be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NadyaCL Katalon'])[2]/following::a[1]</value>
      <webElementGuid>41dda2ad-93f0-4c4a-8ed5-b2ab4391d472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page Size:'])[1]/following::a[10]</value>
      <webElementGuid>71e20a50-e9fb-4af2-ab42-fd35296c50e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KAPA'])[1]/preceding::a[1]</value>
      <webElementGuid>2504fb39-b561-43e6-be18-b77431389ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KLAX'])[1]/preceding::a[1]</value>
      <webElementGuid>80531dd8-3561-4fa1-8fb9-dbb6e829bb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NR23031411']/parent::*</value>
      <webElementGuid>10c5afd1-a275-4aa7-a23e-d85d7b91a839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Ams/ClientDetail/67819?loadFlightPlanId=580012&amp;tempApp=app#Flights')]</value>
      <webElementGuid>070ad459-1541-42b8-83ba-350639966809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>08b4b8e3-d349-4b69-a9bc-cf7451ccf216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Ams/ClientDetail/67819?loadFlightPlanId=580012&amp;tempApp=app#Flights' and (text() = 'NR23031411' or . = 'NR23031411')]</value>
      <webElementGuid>f7a07ff4-6199-40e9-bc0d-5f3e38e28f3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
