<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>attachments_checkBox</name>
   <tag></tag>
   <elementGuidId>1b7f93e2-4474-4d66-b538-95c40f1499e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='5aaf75e5-063b-5078-02d2-545b50401128']/div/div/div[8]/div/label/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ms-Checkbox-checkmark.checkmark-401</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8d75adc6-6684-4304-96a6-ccd560ec73ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-name</name>
      <type>Main</type>
      <value>CheckMark</value>
      <webElementGuid>a90b6a1e-e669-4c33-ae40-b7b5252bca6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bd9d9cbc-11af-4f1a-a57c-0fbc3920bf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Checkbox-checkmark checkmark-401</value>
      <webElementGuid>940c2451-d981-4405-a2b7-c0eb8d48deeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>610f2206-8f63-474f-86dc-b6f43b7847e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5aaf75e5-063b-5078-02d2-545b50401128&quot;)/div[@class=&quot;ms-Callout-main calloutMain-370&quot;]/div[@class=&quot;Ivs_N&quot;]/div[@class=&quot;Kjlf6&quot;]/div[@class=&quot;ms-Checkbox reversed is-enabled root-395&quot;]/label[@class=&quot;ms-Checkbox-label label-397&quot;]/div[@class=&quot;ms-Checkbox-checkbox checkbox-398&quot;]/i[@class=&quot;ms-Checkbox-checkmark checkmark-401&quot;]</value>
      <webElementGuid>a62a25f6-7184-42e3-bc0d-e55cff572ce1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5aaf75e5-063b-5078-02d2-545b50401128']/div/div/div[8]/div/label/div/i</value>
      <webElementGuid>cd51fb6c-100e-41fb-ae28-5b81637b847b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachments'])[1]/following::i[1]</value>
      <webElementGuid>b0fb17d2-fa09-4c78-9224-6c2c65083762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a date'])[2]/following::i[2]</value>
      <webElementGuid>7b8e5664-3115-42c5-9a8f-47541d4d7b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::i[1]</value>
      <webElementGuid>1c4ffd0a-9839-4b7f-a070-4d27ecf6342b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear filters'])[1]/preceding::i[1]</value>
      <webElementGuid>312b23c4-482f-4ea0-95ea-65c41908fc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>184b2807-ff57-494d-ae4e-e1687429f193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/i</value>
      <webElementGuid>c5de781b-0ba3-421b-ab23-ecda59f51cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = '' or . = '')]</value>
      <webElementGuid>6a5e7574-29e5-4b16-bbbd-b6146cf30595</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
