<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>keywords_textBox</name>
   <tag></tag>
   <elementGuidId>4772814d-125f-4305-8571-2d8d03510e4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Keywords-ID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Keywords-ID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95d2e419-1c89-4514-b694-b89bde15c7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74a1dae2-4b9d-44b3-bfec-250f265389f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Keywords-ID</value>
      <webElementGuid>59ab7ae6-39c9-4b34-9b0a-866aac05b692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-TextField-field field-406</value>
      <webElementGuid>e129efa2-d486-44ea-a845-5c23817a9e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e9543a10-4df4-497a-a0ea-b0929a771c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Keywords-ID&quot;)</value>
      <webElementGuid>c8c6899b-e9ee-4cce-838a-be9ffd5f0c5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Keywords-ID']</value>
      <webElementGuid>6383d97d-b568-4096-8203-ffafc03d877e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5aaf75e5-063b-5078-02d2-545b50401128']/div/div/div[6]/div/div/div/input</value>
      <webElementGuid>0410a17b-2955-4169-ac50-bb3cbb2c83ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>e40615a6-070d-4af1-9dee-3476aa6e6e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Keywords-ID']</value>
      <webElementGuid>1eb33eb3-3f1c-4517-9f2c-005d3ac29ee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
