<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>account_dropDown</name>
   <tag></tag>
   <elementGuidId>f8c56c16-4ca9-4ecf-ace7-a9c723f3530f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_AccountId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='FlightPlan_AccountId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9a691e10-16c8-4c8c-9efe-777c9c9aca8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input target-baj-results-selected-account-select grayback select-round form-control</value>
      <webElementGuid>09b7dd0b-44a4-4482-a251-e082562baf2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_AccountId</value>
      <webElementGuid>89261c39-409f-47e2-ba9f-1778022715d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.AccountId</value>
      <webElementGuid>4dc3b300-e2ac-44f6-a2c4-b7b16e77b098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>BAJ.ChangeSelectedAccount(this);</value>
      <webElementGuid>b530c9d2-04d7-43dc-8cc1-b3c5e3b80239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Charter Test Rassadina; Charter Charter
</value>
      <webElementGuid>70867dc6-3b9d-4f46-bc6d-ac4f005f1ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_AccountId&quot;)</value>
      <webElementGuid>d469bbaf-1e65-4af3-9642-a1fc16a46dcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='FlightPlan_AccountId']</value>
      <webElementGuid>42314861-0840-4c3d-8ff9-8325dc6eea3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PayForm']/div/div/div/div/select</value>
      <webElementGuid>faf61f91-2837-4fb5-8e42-0875b8a7d048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::select[1]</value>
      <webElementGuid>bd960c37-1e3c-4463-8d78-5fafa0f6a566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='privacy policy'])[1]/following::select[1]</value>
      <webElementGuid>91307dba-b6f1-417e-841a-c1e56ba9f9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/preceding::select[1]</value>
      <webElementGuid>a861d208-5840-446e-9b28-06edffdb151f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMEX Information'])[1]/preceding::select[2]</value>
      <webElementGuid>d76d7b26-3f7c-4c4f-91e9-b663cde2d997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/select</value>
      <webElementGuid>306de62a-422b-4a66-afcc-ed7421fa5199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'FlightPlan_AccountId' and @name = 'FlightPlan.AccountId' and (text() = 'Charter Test Rassadina; Charter Charter
' or . = 'Charter Test Rassadina; Charter Charter
')]</value>
      <webElementGuid>227aec30-b225-4793-b664-d1ff67164849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
