<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>privacyPolicy_checkBox</name>
   <tag></tag>
   <elementGuidId>767689e2-3605-4d5a-b2ca-6d78198ee63a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_UserAgreement_PrivacyPolicy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_UserAgreement_PrivacyPolicy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c466fd5-ae0a-4f53-bdda-45909794a36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eea26ea7-af2d-4b71-abac-9f87f6c57333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Must Agree to Privacy Policy</value>
      <webElementGuid>d4b04d6c-2679-4626-b12d-272bb8b34f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>a782cada-a6a6-47f3-a6c9-445a5cab6d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>af5ba719-8281-4060-8d3d-1df30e60544b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Privacy Policy field is required.</value>
      <webElementGuid>f88f5f45-2749-40e9-9cd5-e6a76e6c00b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_UserAgreement_PrivacyPolicy</value>
      <webElementGuid>2a95528e-3221-4bcd-915c-69c68bed96a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.UserAgreement_PrivacyPolicy</value>
      <webElementGuid>a8d78686-c329-4392-a020-fccf30600bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8f6c5da9-e059-4d9a-b19f-295fd0569b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ffc178fd-f3b0-4d76-b6cc-1663331a446f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_UserAgreement_PrivacyPolicy&quot;)</value>
      <webElementGuid>782d9658-956c-409a-b7cb-cb08ae44842a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_UserAgreement_PrivacyPolicy']</value>
      <webElementGuid>42ab67e0-f6b6-47ac-9e8c-6029b8dacbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PayForm']/div[2]/div/div[6]/div/ul/li/input</value>
      <webElementGuid>6643fa6c-c155-4bfb-a206-ce85f4e4e25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/input</value>
      <webElementGuid>4bd381cf-07db-4b2e-a09e-bb0957b33713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FlightPlan_UserAgreement_PrivacyPolicy' and @name = 'FlightPlan.UserAgreement_PrivacyPolicy' and @type = 'checkbox']</value>
      <webElementGuid>991b8069-174d-4b85-9b91-fdcbb98290ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
