<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sendFlightDocuments_button</name>
   <tag></tag>
   <elementGuidId>6535a3b6-8b4b-4427-ba38-cd55b8121a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.btn-flight-plan.target-flight-plan-senddocs-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Send Flight Documents']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a86a0996-3a62-4da3-9dab-bb90121ae576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f73ab1b9-b4d2-4e9b-b04e-6fafefb2f476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Send Flight Documents</value>
      <webElementGuid>70c2b824-be97-4813-82d3-07b4ff2dc91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-flight-plan target-flight-plan-senddocs-btn</value>
      <webElementGuid>d7712e25-dc7f-4849-9d1b-3e0105fa0dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Ams.SendFlightDocs(this);</value>
      <webElementGuid>adbbfe05-267e-47aa-a502-92fb25e8d3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;content target-flight-plan-main&quot;]/div[@class=&quot;row ams-workflow-container&quot;]/div[@class=&quot;col-xs-8 target-flight-plan-trip-request-main&quot;]/div[@class=&quot;content target-flight-plan-trip-request-aircraft-list request-list&quot;]/div[@class=&quot;flightplanflow-window&quot;]/div[58]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 margin-top-5&quot;]/input[@class=&quot;btn btn-primary btn-flight-plan target-flight-plan-senddocs-btn&quot;]</value>
      <webElementGuid>89e259f6-9583-449c-b179-c03b081a5fd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Send Flight Documents']</value>
      <webElementGuid>3792b189-c8eb-4fb0-9923-47f3c4eb6426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div[2]/div[2]/div[58]/div[3]/div/input</value>
      <webElementGuid>7e7b4ec5-7240-4ffe-8787-3b8fd9aa0e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[58]/div[3]/div/input</value>
      <webElementGuid>691c35a2-7237-480c-bffd-55167494362e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>a4963b23-8f08-4195-b676-0771e1f30bb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
