<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pricingAndDocuments_tab</name>
   <tag></tag>
   <elementGuidId>66eba27a-9d64-483f-9951-60308662885e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='WorkItemRow']/div/label)[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.black-tight-label.target-flight-plan-work-flow-item-label.target-flight-plan-work-flow-item-label-action-28.target-flight-plan-work-flow-item-label-action</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>083a062a-7113-4405-a186-eb8921db603a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-tight-label target-flight-plan-work-flow-item-label target-flight-plan-work-flow-item-label-action-28 target-flight-plan-work-flow-item-label-action</value>
      <webElementGuid>6d496981-07a0-4512-8a7a-8ee29aa575f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flight-plan-id</name>
      <type>Main</type>
      <value>580574</value>
      <webElementGuid>ff300176-faad-4d45-a517-2e898e7c8837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flight-plan-work-flow-id</name>
      <type>Main</type>
      <value>14624442</value>
      <webElementGuid>de686a12-34a9-4132-a9d7-42414ffa652d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-work-flow-item-id</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>410e98cf-44fb-4800-be5c-293fd485b39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>z4624442</value>
      <webElementGuid>15610ff9-89e2-404f-b5aa-fd833c37d40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pricing and Documents</value>
      <webElementGuid>d8a72712-3494-4931-86d9-86f10201cfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;content target-flight-plan-main&quot;]/div[@class=&quot;row ams-workflow-container&quot;]/div[@class=&quot;col-xs-4 target-flight-plan-work-flow-main&quot;]/div[@class=&quot;target-flight-plan-work-flow-task-div&quot;]/div[@id=&quot;WorkItemRow&quot;]/div[@class=&quot;col-xs-6 black-tight-label&quot;]/label[@class=&quot;black-tight-label target-flight-plan-work-flow-item-label target-flight-plan-work-flow-item-label-action-28 target-flight-plan-work-flow-item-label-action&quot;]</value>
      <webElementGuid>b572f781-9917-41c0-aceb-481c7ceaef34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='WorkItemRow']/div/label)[9]</value>
      <webElementGuid>b7c43f2d-d743-41bb-826a-348b96e8b65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FBO Selection'])[1]/following::label[1]</value>
      <webElementGuid>857a8671-f80f-48ee-8312-396ce29586ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aircraft Selection'])[1]/following::label[2]</value>
      <webElementGuid>2922ae45-6205-43bf-ad44-d95b483d6564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Money Confirmed'])[1]/preceding::label[1]</value>
      <webElementGuid>a6a677a5-4b9d-4a08-b47b-3b0f4273f220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Confirmation Issued'])[1]/preceding::label[2]</value>
      <webElementGuid>e168d22b-114b-487f-a696-02c5283b80c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pricing and Documents']/parent::*</value>
      <webElementGuid>e116679e-02dc-419a-860b-ca038e57586e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/label</value>
      <webElementGuid>93ec1a29-ce04-424b-988a-b378797f4b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Pricing and Documents' or . = 'Pricing and Documents')]</value>
      <webElementGuid>58271dbc-49c9-4dc4-b165-58c54bd0a187</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
