<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address 2_textBox</name>
   <tag></tag>
   <elementGuidId>8a37645a-dd99-4af6-b49e-9aff4253069a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Street2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Street2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd511336-8dda-4fec-bc07-2a4218231782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ba42f8bf-9fbf-4076-8473-7a9db6507663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3219e5e4-5d07-48cd-a86b-38381e7ffbc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df1dc1f7-fc6d-4fd7-9ef7-4b8c969b05f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>de1a41b8-401a-4278-b1c5-7aa14ff2546f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Address 2 must be a string or array type with a maximum length of '50'.</value>
      <webElementGuid>b9fa7336-55a1-4447-8be5-594a586fbbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0bd7ff37-4ec3-40a3-aacb-3f7f7db81058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Street2</value>
      <webElementGuid>0da9f991-9238-40dd-921e-573855bb7d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>86fed43e-a7f3-4a2d-8e73-db35d3508b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[2].ActiveConciergeOrder.ExecutivePickupFullAddress.Street2</value>
      <webElementGuid>d541b409-d746-40f0-9fa0-2becb45cffd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Street2&quot;)</value>
      <webElementGuid>c9df716d-e8d0-4d4a-908b-42d5f31f6d85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Street2']</value>
      <webElementGuid>8ef4c628-16b6-4e74-9d0e-5a6210677590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-2-pickupform']/div/div/div[2]/input</value>
      <webElementGuid>3c820d4b-6f21-49c3-aefe-04fedbe28964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>ac72ce85-054e-4480-85ed-8794fbcdf490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Street2' and @name = 'FlightPlan.Legs[2].ActiveConciergeOrder.ExecutivePickupFullAddress.Street2']</value>
      <webElementGuid>4c21fade-fbed-4955-94b1-c2467d2a268a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
