<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zip_textBox</name>
   <tag></tag>
   <elementGuidId>903e4cfc-16ed-4246-b0d9-1f9c4748753f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Zip']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Zip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00b39801-d177-4419-8e25-1a4d58cd30e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d1dd0e3b-38de-45a9-a766-f143ca00b190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c2046609-57ea-42c7-8ecf-ed2621ed8c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-street-address pickup-address ui-autocomplete-input</value>
      <webElementGuid>c32af148-9a8f-4a3d-9cdb-6bf94c08c23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b0e7746-fa7e-45d1-9c9d-73091f9dc4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b9f9e1b7-f1fa-4946-90e1-acfba481f94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Zip must be a string or array type with a maximum length of '20'.</value>
      <webElementGuid>d6fb6084-5fd5-4450-bb18-29e95cdba501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>48a8a3aa-16b5-4c3e-8c05-dd8850a02fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Zip</value>
      <webElementGuid>30160dd1-3d5c-4ff5-a11a-76f4741de53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7bde0bf9-2d17-46d7-9147-203a2a5d4a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[2].ActiveConciergeOrder.ExecutivePickupFullAddress.Zip</value>
      <webElementGuid>44e817c1-24aa-4887-aebb-1792cd78577b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Zip&quot;)</value>
      <webElementGuid>052ae1d5-59d1-4277-8070-0d3d2dca0578</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Zip']</value>
      <webElementGuid>0f097053-6fc1-4e16-97c4-a397aa478b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-2-pickupform']/div/div/div[5]/input</value>
      <webElementGuid>e4147867-36b8-480a-91bc-ee5eafb00e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/div/div[5]/input</value>
      <webElementGuid>d9feb770-a535-47d9-b95f-d1e38183c1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Zip' and @name = 'FlightPlan.Legs[2].ActiveConciergeOrder.ExecutivePickupFullAddress.Zip']</value>
      <webElementGuid>bb89c4ad-393d-4822-a463-bb04c7bf8894</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
