<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saveRequest_button</name>
   <tag></tag>
   <elementGuidId>80683589-4a57-46a5-b282-1d984669612b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Save Request'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-2-leg-909636 > #new-carrental-quote-noorder > #pickup-quote-0 > div.panel-body > div.row > div.col-xs-12.top-margin-15 > div > input.btn.btn-primary.btn-flight-plan.target-save-vendor-quote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9e4fa8e-1102-439b-adb5-22e84cdc5c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47ec2281-7a4d-411b-b929-5381b9080ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save Request</value>
      <webElementGuid>aa838404-f956-4f24-b562-2ae846a682fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-flight-plan target-save-vendor-quote</value>
      <webElementGuid>6b315611-6b26-42d6-bbca-9b7c80f41e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-transportationtype</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>002689b5-16ad-4065-950f-2272456d862d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909636</value>
      <webElementGuid>c34646cd-612c-419c-94c1-117161f66cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quotetypeid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>56c30148-b0ac-4b51-bd12-7600a56b1ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quoteid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7b41b07f-d5f1-4610-98c6-9f64061c806a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-send</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd6ab167-f2db-4ef3-85fe-56c8ee8de0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909636&quot;)/div[@id=&quot;new-carrental-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 top-margin-15&quot;]/div[1]/input[@class=&quot;btn btn-primary btn-flight-plan target-save-vendor-quote&quot;]</value>
      <webElementGuid>27b99e4b-481c-4e6d-8740-6359b6e97128</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Save Request'])[9]</value>
      <webElementGuid>654cde63-5bf5-4135-a89b-47324dbe49d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='pickup-quote-0']/div/div/div[4]/div/input)[4]</value>
      <webElementGuid>491525f3-46c4-4d3d-bb28-bb0e1ee419a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div/div[2]/div[2]/div[3]/div/div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>e29990ec-927f-46a9-ae78-a7e3db271506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>5c22e5e2-7e39-4362-9eeb-01a7ce95629f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
