<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sMSPhone_textBox</name>
   <tag></tag>
   <elementGuidId>025c746a-c9cb-4594-b01b-92d2c06e44a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__Passengers_2__NotificationSMS']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_2__NotificationSMS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>225a572e-9283-4208-a66d-15f1e1097a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>3c61b780-afcf-45d5-b2c7-b02913ce7aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control phoneNumber</value>
      <webElementGuid>20a43135-0e8b-4922-bb21-3057aedbe4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79314c16-8c9f-46d5-992c-845d3782fd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_2__NotificationSMS</value>
      <webElementGuid>066bbcb5-645a-4025-95d2-2aa016c5d6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[2].NotificationSMS</value>
      <webElementGuid>7ac54bb0-549e-45ee-9511-efeaf2551a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_2__NotificationSMS&quot;)</value>
      <webElementGuid>b8b8fc0c-ccf6-4862-898a-7134c2316876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__Passengers_2__NotificationSMS']</value>
      <webElementGuid>d0ff47d4-22e0-49c3-ba9e-b27828a6d196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-3']/div[3]/div[2]/div/div[4]/div[2]/div/input</value>
      <webElementGuid>9bb5d53f-3ffd-4431-b412-2bd2ca45640f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div[2]/div/input</value>
      <webElementGuid>b7a35c89-46b1-4371-93ae-3db7b0f20d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Legs_0__Passengers_2__NotificationSMS' and @name = 'Legs[0].Passengers[2].NotificationSMS']</value>
      <webElementGuid>15ba54c1-b819-4dcd-9862-5a545008a3e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
