<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fuelStop1Leg1</name>
   <tag></tag>
   <elementGuidId>e244d6ec-48bf-4b25-973e-bd89b197359a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='target-stop-airport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-stop-airport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f71d9d8e-41ad-4391-9089-8c917d1a0379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>267c975e-59b8-40d8-a9ec-42ce1df8339a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>target-stop-airport</value>
      <webElementGuid>b023891a-260d-4031-a218-06c6eaf63ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-airport-entry target-stop-airport-ident target-content-editable-stop ui-autocomplete-input</value>
      <webElementGuid>3ada0aac-fd52-4f95-bf8e-0a1a01d78a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c8c93fae-3a67-4b7e-a9a5-dac4836f02aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-leg-910193-fuel-stops-div&quot;)/table[@class=&quot;target-leg-fuel-stops-table table-dragable&quot;]/tbody[1]/tr[@class=&quot;grabable&quot;]/td[@id=&quot;target-stop-airport&quot;]</value>
      <webElementGuid>e06b2d81-834e-4a26-9491-77131d7fd8ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='target-stop-airport']</value>
      <webElementGuid>18a46e9c-786f-4ab2-bce1-93f41fd8e2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-leg-910193-fuel-stops-div']/table/tbody/tr/td[2]</value>
      <webElementGuid>90bbf4f2-1c56-48e1-ba55-a6e9c45f8cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td[2]</value>
      <webElementGuid>0eb54c3e-2c6d-4dd0-89b6-39e71b36aa2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'target-stop-airport']</value>
      <webElementGuid>5912560d-1b68-473f-97b8-53530cdde45f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
