<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fuelStop2Leg1</name>
   <tag></tag>
   <elementGuidId>e7bf4f1a-f272-4775-ae02-a4c78321f57a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//td[@id='target-stop-airport'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4053db23-cfac-45c7-a6cd-b00ac3db4327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>be885330-0057-4aa1-bf2b-abe05f0b029d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>target-stop-airport</value>
      <webElementGuid>bf18c7cf-5eb6-4d03-a1df-99923920ffcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-airport-entry target-stop-airport-ident target-content-editable-stop ui-autocomplete-input</value>
      <webElementGuid>1eb68d98-f12b-4fef-aed4-2766d31eade8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1663f7e0-a2e2-4534-bdca-15f5d936dfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-leg-910193-fuel-stops-div&quot;)/table[@class=&quot;target-leg-fuel-stops-table table-dragable&quot;]/tbody[1]/tr[@class=&quot;grabable&quot;]/td[@id=&quot;target-stop-airport&quot;]</value>
      <webElementGuid>18b4bc1d-5e2d-4838-8cc9-ae849453d17b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//td[@id='target-stop-airport'])[2]</value>
      <webElementGuid>b8ddbfaf-09e4-4d3c-902e-a1b701d95998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-leg-910193-fuel-stops-div']/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>b439be3a-59ed-41c6-9e3a-9d6dba32a097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>ea75f07c-eb7b-4b65-8758-0ae228d2a697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'target-stop-airport']</value>
      <webElementGuid>e7f36c00-737e-48f3-92ac-587e1a0722bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
