<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flightQuality_tab</name>
   <tag></tag>
   <elementGuidId>e4faa7ce-b587-4fc3-839c-66984788aa47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.black-tight-label.target-flight-plan-work-flow-item-label.target-flight-plan-work-flow-item-label-action-33.target-flight-plan-work-flow-item-label-action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='WorkItemRow']/div/label)[25]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2e097ee6-9b51-476e-ad56-806786763472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-tight-label target-flight-plan-work-flow-item-label target-flight-plan-work-flow-item-label-action-33 target-flight-plan-work-flow-item-label-action</value>
      <webElementGuid>47d35240-3442-4348-b620-b78441c4c480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flight-plan-id</name>
      <type>Main</type>
      <value>580433</value>
      <webElementGuid>cc673515-17fb-47cf-86e8-544d4ffc6c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flight-plan-work-flow-id</name>
      <type>Main</type>
      <value>14619663</value>
      <webElementGuid>6dc79974-4368-4672-9502-3880d6293b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-work-flow-item-id</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>1687e6ba-f5c2-44ac-97de-4809d82b8575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>z4619663</value>
      <webElementGuid>378fec7b-0cb0-4b85-b895-61fa6b67101f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flight Quality</value>
      <webElementGuid>a8165989-5548-40ac-994b-74c50942f870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;content target-flight-plan-main&quot;]/div[@class=&quot;row ams-workflow-container&quot;]/div[@class=&quot;col-xs-4 target-flight-plan-work-flow-main&quot;]/div[@class=&quot;target-flight-plan-work-flow-task-div&quot;]/div[@id=&quot;WorkItemRow&quot;]/div[@class=&quot;col-xs-6 black-tight-label&quot;]/label[@class=&quot;black-tight-label target-flight-plan-work-flow-item-label target-flight-plan-work-flow-item-label-action-33 target-flight-plan-work-flow-item-label-action&quot;]</value>
      <webElementGuid>0e579021-a88e-4f40-9885-046d549ee54f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='WorkItemRow']/div/label)[25]</value>
      <webElementGuid>7e04f513-5e39-4067-88c3-e69dd986d608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concierge Checklist'])[1]/following::label[1]</value>
      <webElementGuid>3f0f0844-55b2-4bec-991b-ddf52bd2eb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concierge Orders'])[1]/following::label[2]</value>
      <webElementGuid>97cf5a85-f632-4c25-8f6a-72473418e165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Flight'])[1]/preceding::label[1]</value>
      <webElementGuid>750472c5-c269-4567-8c40-db86d379590b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Details - Itinerary'])[1]/preceding::label[2]</value>
      <webElementGuid>c4fc7f34-1ee3-4922-bed1-0e90384941fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Flight Quality']/parent::*</value>
      <webElementGuid>5db94585-3c2a-46ae-a467-e37c4b07ab1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/div/div/label</value>
      <webElementGuid>66dd3f4d-d283-4032-b657-6e4290f7b580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Flight Quality' or . = 'Flight Quality')]</value>
      <webElementGuid>8fa6899e-1ebd-429f-8bb6-22c251bd8134</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
