<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>openAnotherMailbox_textBox</name>
   <tag></tag>
   <elementGuidId>f8a5299b-e3c6-4cf1-abc1-c50c46257b7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ms-BasePicker-input.pickerInput_9f838726</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92ad3549-db74-4e16-a846-3562dd39a3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0bd4f96b-7e6c-41ae-8f41-276f7f5b521c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>47c434be-ec98-49e3-a8ca-f15a78816ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>5b1696d0-85b8-47e0-a042-5add6f4bc5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-BasePicker-input pickerInput_9f838726</value>
      <webElementGuid>993459c5-f99f-4d6b-84b8-366f44d38b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a00629cb-f058-4086-a48a-56880a3dc726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>230ee0b9-91d7-4a50-94dd-747064dffca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>390e90dc-2753-40d2-bbc3-1e449102e388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cb7cb3b7-2167-476e-bd5c-486541ea8431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1cfdf604-91b9-4e98-9489-5f79d1d07fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalFocusTrapZone461&quot;)/div[@class=&quot;ms-Modal-scrollableContent scrollableContent-384&quot;]/div[@class=&quot;content-390&quot;]/div[@class=&quot;ms-Dialog-inner inner-393&quot;]/div[@class=&quot;ms-Dialog-content innerContent-394&quot;]/form[1]/div[@class=&quot;LqpTj&quot;]/div[@class=&quot;FD8q0&quot;]/div[@class=&quot;w_uWs&quot;]/div[@class=&quot;E_2JE&quot;]/div[@class=&quot;ms-BasePicker ms-BaseExtendedPicker&quot;]/div[@class=&quot;ms-FocusZone css-159&quot;]/div[@class=&quot;ms-SelectionZone&quot;]/div[@class=&quot;ms-BasePicker-text pickerText_9f838726&quot;]/input[@class=&quot;ms-BasePicker-input pickerInput_9f838726&quot;]</value>
      <webElementGuid>ccf7d4e9-21f1-4ab7-aac2-a533b10f789e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[6]</value>
      <webElementGuid>bfea9b2f-289b-4a2d-8313-d2f34b0c8991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone461']/div[2]/div/div[2]/div/form/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>5c11e63c-d6ec-42d1-bbcf-56b950d6549a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>a320fb01-35c6-4906-9a69-554a9f28816d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
