<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>openAnotherMailbox_link</name>
   <tag></tag>
   <elementGuidId>63f39882-4aed-46a8-a790-2c272ad7fb60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mectrl_OwaOpenTargetMailboxLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mectrl_OwaOpenTargetMailboxLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7457193e-b4e0-4220-a336-329b00faa661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mectrl_OwaOpenTargetMailboxLink</value>
      <webElementGuid>531dd74d-f179-4f67-a443-da24718d1179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mectrl_resetStyle mectrl_link mectrl_truncate</value>
      <webElementGuid>beac37d0-e94c-4c93-84a9-d1363197e6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>61d0887d-18d5-4cee-8177-e9941153d9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>5215b84b-c341-45b9-9c31-e3bba04f16b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open another mailbox</value>
      <webElementGuid>24f8514c-026b-4664-99f5-99dc82b248f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mectrl_OwaOpenTargetMailboxLink&quot;)</value>
      <webElementGuid>41543433-5ef2-4ee7-a9f6-017a7971164c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mectrl_OwaOpenTargetMailboxLink']</value>
      <webElementGuid>8d31f267-8ff7-4c93-b34d-b557ca807504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mectrl_main_body']/div/div/div[3]/div/div[4]/a</value>
      <webElementGuid>24455fdb-e8d1-4c98-926e-2c97bbdeed6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Open another mailbox')]</value>
      <webElementGuid>83113827-e4f7-4763-8bea-6b664c92c6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review and manage your work or school account information'])[1]/following::a[1]</value>
      <webElementGuid>5d933619-9fcc-4738-8028-58ea1f17d956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View account'])[1]/following::a[1]</value>
      <webElementGuid>6857c5aa-6f93-4190-9e98-48959ec1a34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Microsoft 365 profile'])[1]/preceding::a[1]</value>
      <webElementGuid>a4eb968c-656a-4d2c-9b6e-64c7c62ccfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign out'])[1]/preceding::a[2]</value>
      <webElementGuid>df4cf3b9-dcf1-42c8-9788-6dc17cbe9f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Open another mailbox']/parent::*</value>
      <webElementGuid>9824c3ee-746c-4f2e-8631-41488164cbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>588a221e-7c64-43bc-8f9f-7c33a8588839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>d74354e8-f268-4608-9c5e-9635a6da1291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'mectrl_OwaOpenTargetMailboxLink' and @href = 'javascript:void(0)' and (text() = 'Open another mailbox' or . = 'Open another mailbox')]</value>
      <webElementGuid>e9e714ec-d9f4-4410-8862-f7ee39bfb752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
