<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightJetPetsWiFiSelect_button</name>
   <tag></tag>
   <elementGuidId>6309ea74-c874-42cc-93f5-eaa743c28a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BAJ_Aircraft']/div[18]/div/div/div/div[3]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3be6da84-4d84-4825-a1d6-467cb8a2d7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>cbc5aaf5-97ef-4d80-8794-12c159a8cfff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn aircraft-select-button target-baj-button-aircraft-select</value>
      <webElementGuid>8cccfb1a-212a-4c02-842a-4a34e7d57377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aircraft-id</name>
      <type>Main</type>
      <value>7118</value>
      <webElementGuid>533a9c0c-9926-44e8-a991-a00d3268c91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Select 
                                </value>
      <webElementGuid>abfa4b8b-5ebb-462b-92ed-e0c87015e506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BAJ_Aircraft&quot;)/div[@class=&quot;col-xs-12 baj-results-aircraft clearfix colNoSideMargins&quot;]/div[@class=&quot;col-xs-12 colNoSideMargins&quot;]/div[@class=&quot;media aircraftList&quot;]/div[@class=&quot;aircraftList-top&quot;]/div[@class=&quot;media-body&quot;]/div[@class=&quot;aircraft-results-right&quot;]/div[@class=&quot;bookingDetails&quot;]/a[@class=&quot;btn aircraft-select-button target-baj-button-aircraft-select&quot;]</value>
      <webElementGuid>0ae41725-d1b0-4032-8a06-2622106ab70b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BAJ_Aircraft']/div[18]/div/div/div/div[3]/div[2]/div/a</value>
      <webElementGuid>8081efb1-9766-4955-aa83-47b0415844f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[18]</value>
      <webElementGuid>a7f57c7a-2fd6-4c30-ae0f-37069f61fb99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$16,355'])[9]/following::a[1]</value>
      <webElementGuid>a9e7f1fa-55ce-467a-8c62-230db97e9223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAFETY RATING'])[18]/following::a[1]</value>
      <webElementGuid>8832976c-faab-4d82-884c-775f49e15ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manufacturer'])[18]/preceding::a[4]</value>
      <webElementGuid>bc807c79-3fde-45c5-9cf3-19d4d410e7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CESSNA'])[11]/preceding::a[4]</value>
      <webElementGuid>2164959b-2a18-4e77-8bf5-9941866782c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[91]</value>
      <webElementGuid>e22de4bb-abd5-46c4-9dea-8de598c4d80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div/div/div[3]/div[2]/div/a</value>
      <webElementGuid>dd18bb2b-ab31-4ff2-a455-3a85bad773d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '
                                    Select 
                                ' or . = '
                                    Select 
                                ')]</value>
      <webElementGuid>14aeb2ef-73ea-4787-b6a0-98072fdb3f52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
