<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>goodToGoSent_tab</name>
   <tag></tag>
   <elementGuidId>2a399994-b566-44df-a143-af92143c0c0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.black-tight-label.target-flight-plan-work-flow-item-label.target-flight-plan-work-flow-item-label-action-17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='WorkItemRow']/div/label)[21]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>378f8f27-1b70-4cc6-8f47-e3324595d21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-tight-label target-flight-plan-work-flow-item-label target-flight-plan-work-flow-item-label-action-17</value>
      <webElementGuid>f71f8a11-a7b7-4f85-9ee8-a10ccfca0698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flight-plan-id</name>
      <type>Main</type>
      <value>580433</value>
      <webElementGuid>7bbceaa5-05f4-4aa8-ae55-e8201a293248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flight-plan-work-flow-id</name>
      <type>Main</type>
      <value>14619667</value>
      <webElementGuid>9b32a19a-55ca-4b31-8389-e8295b42305b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-work-flow-item-id</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>c8d4faf3-9566-4183-9f9b-182e956a2fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>z4619667</value>
      <webElementGuid>6a45f31c-673f-44f3-9299-800a7218e29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Good To Go Sent</value>
      <webElementGuid>678597ef-1aad-4499-9dfa-ae40f4189f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;content target-flight-plan-main&quot;]/div[@class=&quot;row ams-workflow-container&quot;]/div[@class=&quot;col-xs-4 target-flight-plan-work-flow-main&quot;]/div[@class=&quot;target-flight-plan-work-flow-task-div&quot;]/div[@id=&quot;WorkItemRow&quot;]/div[@class=&quot;col-xs-6 black-tight-label&quot;]/label[@class=&quot;black-tight-label target-flight-plan-work-flow-item-label target-flight-plan-work-flow-item-label-action-17&quot;]</value>
      <webElementGuid>bd6c8885-8c7f-4da2-818b-12d06b948b7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='WorkItemRow']/div/label)[21]</value>
      <webElementGuid>f40fad71-26a0-4ce2-9d7a-b109dd075eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trip Sheet'])[1]/following::label[1]</value>
      <webElementGuid>415e3467-d513-424c-9110-77cf2b06faf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounting Finalized'])[1]/following::label[2]</value>
      <webElementGuid>7f6152d2-d69b-4293-b897-ebe5ebf057f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concierge Assigned'])[1]/preceding::label[1]</value>
      <webElementGuid>11b17a97-32e6-4ee0-8c53-f62efa0d4d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concierge Orders'])[1]/preceding::label[2]</value>
      <webElementGuid>66630911-b2f5-4f50-a2ad-82aefd5e34a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Good To Go Sent']/parent::*</value>
      <webElementGuid>467811d9-1ac3-4181-bf91-2d4d01e1f25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div/label</value>
      <webElementGuid>7d133c99-c1e8-4c71-bc0d-19b2209dbfd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Good To Go Sent' or . = 'Good To Go Sent')]</value>
      <webElementGuid>cb1bb71b-5d0c-4f39-bc62-108b9130a993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
