<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>description_textBox</name>
   <tag></tag>
   <elementGuidId>9c12e319-3888-4749-8f3f-d7301f6bf3df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FlightPlanPostConfirmEditLogInput_BillItem_Description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlanPostConfirmEditLogInput_BillItem_Description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>509a63b0-da48-44a6-93bc-ba3392e33f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tight-select padding-left-5</value>
      <webElementGuid>fa9965d1-fc5a-45d3-9ea1-662089b4842e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlanPostConfirmEditLogInput_BillItem_Description</value>
      <webElementGuid>8c337c63-4d5f-42f0-8105-31d1f09cdc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlanPostConfirmEditLogInput.BillItem.Description</value>
      <webElementGuid>0471eea8-b924-4e83-9e83-8d165edd7ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a description</value>
      <webElementGuid>1bd204d9-aa8a-490e-aeb2-637962d22b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91cf7d5a-5f28-4278-a34e-8346cf206c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlanPostConfirmEditLogInput_BillItem_Description&quot;)</value>
      <webElementGuid>206a90f0-1958-437e-95bc-9fddd41a0d54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlanPostConfirmEditLogInput_BillItem_Description']</value>
      <webElementGuid>0aa68b9d-a8d5-462e-a1c7-5f1847a40dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='target-edit-confirmed-flight-form']/div/div/div/div/div[2]/input</value>
      <webElementGuid>f465b197-5bf9-42d0-b3e3-61239e5753f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div[2]/input</value>
      <webElementGuid>cb0e0ea3-273c-4eab-be09-3e0b69ae0e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FlightPlanPostConfirmEditLogInput_BillItem_Description' and @name = 'FlightPlanPostConfirmEditLogInput.BillItem.Description' and @placeholder = 'Enter a description' and @type = 'text']</value>
      <webElementGuid>63590e9f-4207-44ff-9cf5-f2938eb7ec45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
