<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>internalNote_textBox</name>
   <tag></tag>
   <elementGuidId>fa6a1342-130c-4bc1-89e4-feba7c423d89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='LatestNote'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropoff-quote-0 > div.panel-body > div.row > div.col-xs-12.col-sm-6 > #LatestNote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8863ec0b-0224-4171-8cf7-1d31a73c456f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea-small</value>
      <webElementGuid>02b16e71-940a-464d-a2a7-6646e398961f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LatestNote</value>
      <webElementGuid>ddbfaa03-41a8-495c-9dc7-70714e48a1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;concierge-quotes-accoridion-leg-1&quot;)/div[@class=&quot;panel request&quot;]/div[@id=&quot;dropoff-quotes-leg-1&quot;]/div[@class=&quot;panel-body&quot;]/div[@id=&quot;dropoff-quotes-workarea-leg-909842&quot;]/div[@id=&quot;dropoff-quotes-container-leg-909842&quot;]/div[@id=&quot;target-new-quote-type-3-leg-909842&quot;]/div[@id=&quot;new-carrental-quote-noorder&quot;]/div[@id=&quot;dropoff-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6&quot;]/textarea[@id=&quot;LatestNote&quot;]</value>
      <webElementGuid>a64e46bd-d27d-4415-9be5-c8ed95448c35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='LatestNote'])[6]</value>
      <webElementGuid>0ae42d0d-aefa-4a56-850c-e14e67b47b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropoff-quote-0']/div/div/div[3]/textarea</value>
      <webElementGuid>85be480e-9ad3-457c-af56-c0b3d77ce707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div[2]/div[3]/div/div[2]/div/div/div[3]/textarea</value>
      <webElementGuid>a12c124b-c534-4cfe-b223-79e796270437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'LatestNote']</value>
      <webElementGuid>4af2e6a0-a9af-461a-9b72-95126c76b252</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
