<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>membershipNumber_textBox</name>
   <tag></tag>
   <elementGuidId>d2a7c0b6-d064-4c88-9b85-580943814c3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='CustomerNumber'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropoff-quote-0 > div.panel-body > div.row > div.col-xs-12.col-sm-6 > #CustomerNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d74d57eb-5efc-484b-b682-40e647e2b95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ec39923-2ec9-4c50-9163-d5c2b581d42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5eebbaa2-891f-4550-b92e-88fd2d5075cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerNumber</value>
      <webElementGuid>b142c196-6c84-4b77-b627-110fc2e64554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CustomerNumber</value>
      <webElementGuid>4d05b488-82a4-4d0d-802f-931bab8813d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;concierge-quotes-accoridion-leg-1&quot;)/div[@class=&quot;panel request&quot;]/div[@id=&quot;dropoff-quotes-leg-1&quot;]/div[@class=&quot;panel-body&quot;]/div[@id=&quot;dropoff-quotes-workarea-leg-909635&quot;]/div[@id=&quot;dropoff-quotes-container-leg-909635&quot;]/div[@id=&quot;target-new-quote-type-3-leg-909635&quot;]/div[@id=&quot;new-carrental-quote-noorder&quot;]/div[@id=&quot;dropoff-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6&quot;]/input[@id=&quot;CustomerNumber&quot;]</value>
      <webElementGuid>4c987587-a491-4442-8e06-4725b14d0df2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='CustomerNumber'])[2]</value>
      <webElementGuid>79eb5f5d-0132-45f1-a8b8-2fa4b0accb26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropoff-quote-0']/div/div/div[2]/input[2]</value>
      <webElementGuid>5a08ae7a-0be1-412d-99d7-aa3f032fbf79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div[2]/div[3]/div/div[2]/div/div/div[2]/input[2]</value>
      <webElementGuid>2c5c3c87-d4e1-463b-a609-f1a3bb204231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CustomerNumber' and @name = 'CustomerNumber']</value>
      <webElementGuid>bb9b708f-1f7b-4283-bd30-4a1d328254d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
