<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save_button</name>
   <tag></tag>
   <elementGuidId>69c59aba-5956-420a-869a-eadcd1df2aef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Save Request'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropoff-quote-0 > div.panel-body > div.row > div.col-xs-12.top-margin-15 > div > input.btn.btn-primary.btn-flight-plan.target-save-vendor-quote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47b6e039-4119-4fa5-8117-e591cc93ac7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b2bc76fc-daf1-4aad-8239-976f8efc55c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save Request</value>
      <webElementGuid>6eeb50f9-4626-412a-b546-b6033ad55ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-flight-plan target-save-vendor-quote</value>
      <webElementGuid>5d95e0ea-e2e2-421d-8010-f6c9aa2dd6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-transportationtype</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>64833efa-3359-4ead-843c-ec5b23932416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909848</value>
      <webElementGuid>f19a5daf-971e-40de-ae0e-c6d4ea45edcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quotetypeid</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>29f51b38-f895-48b7-9cfb-120e2f3d5650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quoteid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>189526f0-3dbf-4f6b-8f47-1a7f3a3a415b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-send</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd583f9b-1f2b-409e-b052-00c27958bdcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;concierge-quotes-accoridion-leg-1&quot;)/div[@class=&quot;panel request&quot;]/div[@id=&quot;dropoff-quotes-leg-1&quot;]/div[@class=&quot;panel-body&quot;]/div[@id=&quot;dropoff-quotes-workarea-leg-909848&quot;]/div[@id=&quot;dropoff-quotes-container-leg-909848&quot;]/div[@id=&quot;target-new-quote-type-3-leg-909848&quot;]/div[@id=&quot;new-carrental-quote-noorder&quot;]/div[@id=&quot;dropoff-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 top-margin-15&quot;]/div[1]/input[@class=&quot;btn btn-primary btn-flight-plan target-save-vendor-quote&quot;]</value>
      <webElementGuid>6af839ef-e6c9-4f43-a2dc-2b74899cfce7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Save Request'])[6]</value>
      <webElementGuid>371198e5-4c97-4c15-b00a-4b177da96dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropoff-quote-0']/div/div/div[4]/div/input</value>
      <webElementGuid>16943c59-9b59-4e9f-9819-f516a056ec01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div[2]/div[3]/div/div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>7e921029-74f3-4e98-957e-65a66bfa948d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>7aebba8e-59b2-443f-9615-8a89da9d22fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
