<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>serviceFee_textBox</name>
   <tag></tag>
   <elementGuidId>8c8f8b69-891d-4de5-a7e7-b7f312560519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='ClientConciergePayment_ClientConciergePaymentReason_ServiceFee'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba613f05-e071-47b8-bc6f-3b133f5dc503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1a34ca3d-a586-4e15-ae7b-ea58078cf157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>98112de4-db84-4bf7-9ed3-550f020708f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ac966413-9b8b-44eb-86b2-f66eba44ea30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tight-input target-service-fee</value>
      <webElementGuid>4a3f39cb-7631-4ef9-b9f3-f6fd3d8c347f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ClientConciergePayment_ClientConciergePaymentReason_ServiceFee</value>
      <webElementGuid>8ef9dee5-ff42-4814-9b50-1e4e5e6a904b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ClientConciergePayment.ClientConciergePaymentReason.ServiceFee</value>
      <webElementGuid>e6e0d482-09b0-4b14-a2ed-66b7bd0c7f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909636&quot;)/div[@id=&quot;new-carrental-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6&quot;]/div[@class=&quot;row target-concierge-payment-div&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@id=&quot;target-client-concierge-payment-2-0&quot;]/table[1]/tbody[1]/tr[2]/td[2]/input[@id=&quot;ClientConciergePayment_ClientConciergePaymentReason_ServiceFee&quot;]</value>
      <webElementGuid>36847313-b5c6-4947-9410-64f78bd69ae5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='ClientConciergePayment_ClientConciergePaymentReason_ServiceFee'])[9]</value>
      <webElementGuid>476afcb2-7112-4b0d-a4fc-6378a3015055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='target-client-concierge-payment-2-0']/table/tbody/tr[2]/td[2]/input)[3]</value>
      <webElementGuid>6c6d1caa-a5e3-4d70-acce-0e77085a2e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div/div[2]/div[2]/div[3]/div/div[2]/div/div/div[3]/div[6]/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>1061428a-83a0-4ee4-ba4a-aa6b96fafb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'ClientConciergePayment_ClientConciergePaymentReason_ServiceFee' and @name = 'ClientConciergePayment.ClientConciergePaymentReason.ServiceFee']</value>
      <webElementGuid>8281b8fd-7d27-4ae6-b5c1-796b985fcfc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
