<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flightOpsAssigned_tab</name>
   <tag></tag>
   <elementGuidId>f5e85622-f073-45b1-bcd9-a48d99de2a6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='WorkItemRow']/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.black-tight-label.target-flight-plan-work-flow-item-label.target-flight-plan-work-flow-item-label-action-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0181707a-4a9c-439f-828f-abe7e3c01775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-tight-label target-flight-plan-work-flow-item-label target-flight-plan-work-flow-item-label-action-1</value>
      <webElementGuid>5b00c8ea-a74e-4d8d-95d0-2104135f8a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flight-plan-id</name>
      <type>Main</type>
      <value>580422</value>
      <webElementGuid>2e10ab09-dd10-4d11-b9db-f3f85d7d90c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flight-plan-work-flow-id</name>
      <type>Main</type>
      <value>14619300</value>
      <webElementGuid>b6c3f785-495a-40cf-8bc1-ec79ce9e72dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-work-flow-item-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>291b1695-c53a-4f42-8f77-51bfabdc1c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>z4619300</value>
      <webElementGuid>cdd789e5-8481-432c-b91f-291588d344ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flight Ops Assigned</value>
      <webElementGuid>49c3b824-fec1-4d80-bda7-cccbd3012f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;content target-flight-plan-main&quot;]/div[@class=&quot;row ams-workflow-container&quot;]/div[@class=&quot;col-xs-4 target-flight-plan-work-flow-main&quot;]/div[@class=&quot;target-flight-plan-work-flow-task-div&quot;]/div[@id=&quot;WorkItemRow&quot;]/div[@class=&quot;col-xs-6 black-tight-label&quot;]/label[@class=&quot;black-tight-label target-flight-plan-work-flow-item-label target-flight-plan-work-flow-item-label-action-1&quot;]</value>
      <webElementGuid>6a5df3fd-bbc0-4b58-9249-6f6d676ca523</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WorkItemRow']/div/label</value>
      <webElementGuid>5bccfb23-c42e-45cd-b544-850b5ee113c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary Email Override:'])[1]/following::label[1]</value>
      <webElementGuid>702ec7c5-8b5f-4cc8-88cd-403bb49a17ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business'])[2]/following::label[2]</value>
      <webElementGuid>279e9f70-f485-4508-99bd-3df10e5a13e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Folder Ready'])[1]/preceding::label[1]</value>
      <webElementGuid>70d6cb5c-2fa4-427e-8cf3-8a8f7ec90924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options Sent'])[1]/preceding::label[2]</value>
      <webElementGuid>e7fc56b2-36f4-4fbe-95e4-03576104daad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Flight Ops Assigned']/parent::*</value>
      <webElementGuid>61df6938-5bbc-4cce-8b9e-df8a47d6e780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div[2]/div/div/label</value>
      <webElementGuid>3d66c062-e575-4846-a6fc-8076c9667d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Flight Ops Assigned' or . = 'Flight Ops Assigned')]</value>
      <webElementGuid>7e264000-9f3e-4326-9e7e-b1a73c9aa428</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
