<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>membershipNumber_textBox</name>
   <tag></tag>
   <elementGuidId>d52d7f52-3897-4521-9339-b4ccc83465f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustomerNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CustomerNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5dcdd2a-adc0-4c8d-831e-1eb57ce1105d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fce08d75-4dfc-4d81-add4-e8203c4875ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fdf1db6b-d178-43b1-9fcf-58410a8f2261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerNumber</value>
      <webElementGuid>ccaca067-c8fd-4816-a51b-f928c32ee273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CustomerNumber</value>
      <webElementGuid>acc6a27f-bdae-4e73-ae1b-b7eeaa48f1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909635&quot;)/div[@id=&quot;new-carrental-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6&quot;]/input[@id=&quot;CustomerNumber&quot;]</value>
      <webElementGuid>e7fcf5d7-0420-4858-aa1e-5635dd959b49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustomerNumber']</value>
      <webElementGuid>79c2459e-176a-494e-9fee-de761b977e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pickup-quote-0']/div/div/div[2]/input[2]</value>
      <webElementGuid>3a5a215f-3611-4a53-bcdc-d0f467fea12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input[2]</value>
      <webElementGuid>3eeaa918-f9a4-419f-86a7-cafb9efdb737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CustomerNumber' and @name = 'CustomerNumber']</value>
      <webElementGuid>5824f253-c832-4904-98e8-182a8002a8fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
