<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quotedAmount_textBox</name>
   <tag></tag>
   <elementGuidId>a4c172c5-7f7b-4302-9aba-2a3739df9502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='QuotedAmount'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.row > div.col-xs-12.target-div-overage-reason > div.target-quoted-amount-div > #QuotedAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76ee63c6-704d-4ac1-bbe1-3325dde6999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>eb2082c9-44bc-4800-a044-d042c559214b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-budget</name>
      <type>Main</type>
      <value>150.0000</value>
      <webElementGuid>84815f94-b662-498c-b9a8-2df68e82b5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>b95a06cd-be53-45b3-ab6c-9c35b8c0a01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>6ca347b0-2827-4506-a696-48799c1b7076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control target-concierge-quoted-amount</value>
      <webElementGuid>f1cc52b3-f653-4c4c-8ae9-509272f167ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QuotedAmount</value>
      <webElementGuid>0375b05c-89ca-4759-a791-4e1a5c0b9960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QuotedAmount</value>
      <webElementGuid>0012788b-8aa7-4fc3-b089-b7751223bc45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909635&quot;)/div[@id=&quot;new-carrental-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 target-div-overage-reason&quot;]/div[@class=&quot;target-quoted-amount-div&quot;]/input[@id=&quot;QuotedAmount&quot;]</value>
      <webElementGuid>d266d450-6e94-4a51-85c6-f3333ea58479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='QuotedAmount'])[2]</value>
      <webElementGuid>08b943c9-78ec-4c51-b9b1-0f81d18f761f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pickup-quote-0']/div/div/div[3]/div[4]/div/div/input</value>
      <webElementGuid>f6144c39-493e-4c0b-b1ad-33c2fb602e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div[4]/div/div/input</value>
      <webElementGuid>0680c368-9f07-47ae-a6ac-e2043d3f4471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'QuotedAmount' and @name = 'QuotedAmount']</value>
      <webElementGuid>975046c7-1529-41d8-bd55-f2cd47729859</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
