<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>electronicSignature_textBox</name>
   <tag></tag>
   <elementGuidId>98c2d989-44a3-47ba-9b80-822fb68272f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ElectronicSignature']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ElectronicSignature</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc7ea7ae-9363-4a7b-bcc1-c0ff39b70aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38e82c33-b700-4fe4-80de-79601c76a1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>577b3855-c3d8-4f98-8846-cb03fdab5582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>348c038d-8a79-4479-baaa-be91102b598d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Please sign by typing your First and Last name</value>
      <webElementGuid>6fb915b1-9828-4bcb-aa6e-a50e8daa51c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ElectronicSignature</value>
      <webElementGuid>d3fd17c0-e507-4a49-ab87-17510c976960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ElectronicSignature</value>
      <webElementGuid>3230ab6d-4c70-4d0f-8902-144cf0ba9128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ElectronicSignature&quot;)</value>
      <webElementGuid>0f4637ad-2fdd-4f1a-8da0-6b0246eafc5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ElectronicSignature']</value>
      <webElementGuid>ed9d2760-7489-4cdb-ad36-fc4c2d51bbaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='employee-health-declaration-form-0']/div[6]/div/input</value>
      <webElementGuid>50ee0580-b5f5-4db4-9b4f-905743cf8cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>ce4fdc42-d153-4b55-9c30-aa0db3201697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ElectronicSignature' and @name = 'ElectronicSignature']</value>
      <webElementGuid>98a3e64f-f276-4796-b344-296744ed86de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
