<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submit_button</name>
   <tag></tag>
   <elementGuidId>118ca4e5-8155-4cee-978f-ec82097076cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.baj-btn.target-employee-health-declaration-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b83dd036-3ca7-448d-b3ee-d6afcacbbd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07a5a0bd-eb6f-4643-8880-e66a8de04d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>0493e963-3aa4-4136-a904-b38141fe65b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn target-employee-health-declaration-submit</value>
      <webElementGuid>c827616a-8a33-4c6c-81a9-8986208e833f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-record</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c74c08ce-329d-4556-83fd-234a921b4ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employee-health-declaration-form-0&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-6 form-not-submited-0&quot;]/input[@class=&quot;baj-btn target-employee-health-declaration-submit&quot;]</value>
      <webElementGuid>bac6fecc-dede-4310-8d8a-e4e3c6070789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Submit']</value>
      <webElementGuid>b989c076-fb1e-4d94-ad45-7bb7072b00ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='employee-health-declaration-form-0']/div[7]/div/input</value>
      <webElementGuid>2f2358e4-6c68-4fee-abaf-25cfd3309ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>745dc074-43a1-443b-9a30-8663d7771d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>bcd69a50-ffde-4f31-ad68-ff7a90601559</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
