<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>city_textBox</name>
   <tag></tag>
   <elementGuidId>41fc859f-2915-4af9-91ad-3fca9a688334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupFullAddress_City']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupFullAddress_City</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28a81434-e095-48aa-8ec3-c9844d100b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ab7bde46-ed20-4d9c-843a-1c6211db64ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8a5137ae-9a3f-40a6-9a32-0390ffebafa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-street-address pickup-address ui-autocomplete-input</value>
      <webElementGuid>7fd7c38e-8cfb-4e16-af69-8930d45493b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15fcc592-1f7f-46e8-a7bc-6c8f4d8bf508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>28bcde4c-2f29-451c-acb6-968733a3f2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field City must be a string or array type with a maximum length of '30'.</value>
      <webElementGuid>85981475-21ed-4471-ab69-bad25b86e376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>78c3e9b3-08ba-4e10-90d2-86cc659d665f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupFullAddress_City</value>
      <webElementGuid>8bc513f5-a918-494d-8c16-996cbdd7a3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>c84ba566-ac50-4621-ba01-03a63ab9ad8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[0].ActiveConciergeOrder.ExecutivePickupFullAddress.City</value>
      <webElementGuid>d0413328-bc0c-42c0-a93d-af6a6942a953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupFullAddress_City&quot;)</value>
      <webElementGuid>a1e1d162-8469-4d0c-be65-82316ad1ac42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupFullAddress_City']</value>
      <webElementGuid>c542da5c-050a-4921-b105-9afb8e36d95d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-0-pickupform']/div/div/div[3]/input</value>
      <webElementGuid>fcb0502e-3419-4d18-8e9f-2b0b9a8fc764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/input</value>
      <webElementGuid>02dfaf26-159f-407c-95ed-eeb5844b7275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupFullAddress_City' and @name = 'FlightPlan.Legs[0].ActiveConciergeOrder.ExecutivePickupFullAddress.City']</value>
      <webElementGuid>48fe172d-5874-4872-8f68-7feea33a8b80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
