<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>state_textBox</name>
   <tag></tag>
   <elementGuidId>9cdfcf57-0009-447c-b0d9-3b110a1599d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupFullAddress_State_StateCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupFullAddress_State_StateCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ace05f21-eddf-497e-85bc-8157e9ae8a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>43bf0a8c-9778-42ce-9397-8c58c64abf6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3893e269-a4e5-4a12-aa96-57fa848443ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-street-address pickup-address ui-autocomplete-input</value>
      <webElementGuid>d1379215-2eaa-4307-a71a-a8e497776666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a514ecdf-1a9f-4a40-91dd-6f8cd90f5ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f257bd90-ad9b-491f-a511-1ce7507114b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field State must be a string or array type with a maximum length of '2'.</value>
      <webElementGuid>d4e86b90-91a4-4ecf-b3fd-ad43c44ff145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0673a40e-2bb4-4d9c-9cb8-b3a3355c15c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The State field is required.</value>
      <webElementGuid>7860ec63-0a26-4488-909e-9305b2acf16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupFullAddress_State_StateCode</value>
      <webElementGuid>c5c5b1ae-799c-4796-b2af-6a1aabba1d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>507b93a1-f368-48f4-ae7a-81274d8c21a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[0].ActiveConciergeOrder.ExecutivePickupFullAddress.State.StateCode</value>
      <webElementGuid>c78305d8-3bd3-4ad4-ba70-0a28d1877d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupFullAddress_State_StateCode&quot;)</value>
      <webElementGuid>7eb21816-c4ee-4a54-8613-54a0f9bc2fd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupFullAddress_State_StateCode']</value>
      <webElementGuid>0f7e0bc3-6939-401e-9c0a-e92b941a0985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-0-pickupform']/div/div/div[4]/input</value>
      <webElementGuid>3caa6b36-a9a7-4716-948c-5c2ceb440576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[4]/input</value>
      <webElementGuid>0cf11bc0-d4eb-493d-b78a-1c283f9e064f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupFullAddress_State_StateCode' and @name = 'FlightPlan.Legs[0].ActiveConciergeOrder.ExecutivePickupFullAddress.State.StateCode']</value>
      <webElementGuid>8352a589-7ce5-4418-9fd8-dd11daf5629b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
