<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>luggage_textArea</name>
   <tag></tag>
   <elementGuidId>9f30f3ee-52a0-4dca-8579-56c5c0b35b7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__LuggageDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Legs_1__LuggageDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>40b38648-a501-4933-a4cc-7479e627e36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-textarea form-control target-luggage-description</value>
      <webElementGuid>7a77bf28-8b67-4a05-8811-30c905b5cfb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>257f44ed-cd52-4954-a5a4-bc37b06aaa82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__LuggageDescription</value>
      <webElementGuid>eede5bc2-0095-4110-96c6-5416f672b498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].LuggageDescription</value>
      <webElementGuid>96ed2110-f94b-42ca-a451-282d3cc670aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ad642771-3220-47b4-a124-10c38c4a127d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__LuggageDescription&quot;)</value>
      <webElementGuid>49077fd4-b1cd-403e-aa92-e6be2e0eed78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Legs_1__LuggageDescription']</value>
      <webElementGuid>f9264a9a-0670-4227-9872-0275098145f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div/div[5]/textarea)[4]</value>
      <webElementGuid>a7b6b2c1-7682-44d8-bd56-5901f2aee86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/div/div/div/div/div[5]/textarea</value>
      <webElementGuid>7d1317aa-7dfe-4799-8d11-140641b77b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Legs_1__LuggageDescription' and @name = 'Legs[1].LuggageDescription']</value>
      <webElementGuid>3eb350a1-a9b1-45ad-b44b-496f192e6849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
