<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pets_textArea</name>
   <tag></tag>
   <elementGuidId>66fb2f55-4b97-4048-8411-89690b404782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__PetsDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Legs_1__PetsDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4a9fcede-e253-4482-9d65-10af3c1bc4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-textarea form-control target-pets-description</value>
      <webElementGuid>851a7d3c-e610-4f8d-a200-a6e5c7bb55d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>7f01d993-2c9a-45ca-a34c-b1d6d64a2fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__PetsDescription</value>
      <webElementGuid>be0ef72b-7d77-4832-92f7-f04a1b40854a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].PetsDescription</value>
      <webElementGuid>4d8dfd0d-9511-4ee2-8b33-8e8e733e192f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c70fa0a9-0249-4f92-b36e-266be948974c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__PetsDescription&quot;)</value>
      <webElementGuid>343e28c1-37aa-4e32-9976-a57c89fdc3ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Legs_1__PetsDescription']</value>
      <webElementGuid>bf53f2bd-79fc-42a6-a171-beedd0c8d569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div[3]/div[5]/textarea)[2]</value>
      <webElementGuid>2a8bd89a-242c-4dcc-af4a-49bc3484bfd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/div/div/div/div[3]/div[5]/textarea</value>
      <webElementGuid>f61c3bbf-aa2c-45cf-8037-dac303ec10f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Legs_1__PetsDescription' and @name = 'Legs[1].PetsDescription']</value>
      <webElementGuid>72eff61a-8669-4357-b2b9-08b59a43a18d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
