<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pets_checkBox</name>
   <tag></tag>
   <elementGuidId>17ef52e4-9e2b-4f1a-9d4c-8d98faed8e84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__PetsDescriptionNone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_1__PetsDescriptionNone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0389289-d7a2-4ec2-b06b-fe98aef3be59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom form-check-input target-pets-nonecheckbox</value>
      <webElementGuid>38e8bb61-20ba-469b-beb3-590a6ff59428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4c7c74c-18d0-41c3-8b0a-e8a1622f0a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PetsDescriptionNone field is required.</value>
      <webElementGuid>4d56aece-36dc-44cf-af47-bdb091cb9432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__PetsDescriptionNone</value>
      <webElementGuid>851aaae1-e263-48f6-bca3-7070992fac39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].PetsDescriptionNone</value>
      <webElementGuid>f76f3670-1da6-4b6b-bfac-ac7b3a862760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f3e1fd96-219c-465a-9058-ae217bdf174e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2697aec0-a577-43ad-b676-0a9d873ed014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__PetsDescriptionNone&quot;)</value>
      <webElementGuid>83970b3a-deab-4acd-b7a1-97d434491400</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_1__PetsDescriptionNone']</value>
      <webElementGuid>44015e88-fcf3-4e67-b0f4-f547cf33d0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div[3]/div[3]/div/div/input)[2]</value>
      <webElementGuid>85f212e2-b99e-4caf-9ec4-1da82df530cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/div/div/div/div[3]/div[3]/div/div/input</value>
      <webElementGuid>78df5545-efdf-4d6a-8b35-5f057b39ab9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_1__PetsDescriptionNone' and @name = 'Legs[1].PetsDescriptionNone' and @type = 'checkbox']</value>
      <webElementGuid>bb7ab0c2-b5fc-4fc4-a96d-869a67743124</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
