<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pickUpInstructions_textBox</name>
   <tag></tag>
   <elementGuidId>04fecaac-ba5d-49db-91ec-4e0b4e1882f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutivePickupInstructions']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_1__ActiveConciergeOrder_ExecutivePickupInstructions</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>61b5ce1c-82ff-40f7-a29a-4b5ed699911e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fa6b408c-ddfb-4b33-aa3c-119b58c40619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>92bb38b9-fb42-45f4-ac9c-ff936975cc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_1__ActiveConciergeOrder_ExecutivePickupInstructions</value>
      <webElementGuid>23d8e9c1-20db-41f4-89d4-6e69816fc87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[1].ActiveConciergeOrder.ExecutivePickupInstructions</value>
      <webElementGuid>70d8f176-9ecb-4611-89d0-feca6825675a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_1__ActiveConciergeOrder_ExecutivePickupInstructions&quot;)</value>
      <webElementGuid>4d5a6f01-7c32-4d80-8b94-d1187c341d84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutivePickupInstructions']</value>
      <webElementGuid>b0463301-5889-49f8-ba83-459d7556761b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-1-pickupform']/div/textarea</value>
      <webElementGuid>3324c415-2e56-45e7-ac06-03dc1d705902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/textarea</value>
      <webElementGuid>5df41575-e7b8-48fe-967c-392f38fcaa7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'FlightPlan_Legs_1__ActiveConciergeOrder_ExecutivePickupInstructions' and @name = 'FlightPlan.Legs[1].ActiveConciergeOrder.ExecutivePickupInstructions']</value>
      <webElementGuid>348faab8-2547-445f-b6e8-8985a18ad4d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
