<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>phone_textBox</name>
   <tag></tag>
   <elementGuidId>7555f0bc-cb0f-4c54-83b2-b0817dc07cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AmsFilterViewModel_FilterPhone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AmsFilterViewModel_FilterPhone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8e0df2d-65ee-4fc7-a8f9-9e13316cac01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control target-filter-element</value>
      <webElementGuid>492c1712-43a1-48e7-ab75-f086b2558aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a118d87-67f2-47bc-8807-cc96e6179e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmsFilterViewModel_FilterPhone</value>
      <webElementGuid>0434116c-cd82-43dd-bc30-42df533efa1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmsFilterViewModel.FilterPhone</value>
      <webElementGuid>c3bd60de-f9ac-4fcd-a360-93143fcf155e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmsFilterViewModel_FilterPhone&quot;)</value>
      <webElementGuid>fb452aa6-6341-47af-9943-a64c63548b60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AmsFilterViewModel_FilterPhone']</value>
      <webElementGuid>fba00ef0-b47e-416f-bc2f-a7fb5f4076a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/div[5]/div/input</value>
      <webElementGuid>344f387b-8052-4945-a437-049bc2e12883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>13470487-602d-4af1-9bac-6560a26cc0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'AmsFilterViewModel_FilterPhone' and @name = 'AmsFilterViewModel.FilterPhone']</value>
      <webElementGuid>8c1335e3-5cfc-4677-97eb-d7828d7ee55d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
