<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>timeZone_dropDown</name>
   <tag></tag>
   <elementGuidId>3d3288a5-1507-4bb8-a856-298c0d8962b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AmsFilterViewModel_FilterTimeZoneTypeId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AmsFilterViewModel_FilterTimeZoneTypeId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7678424d-3f19-4e2b-9f9e-6b8ca18f9fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control target-filter-element</value>
      <webElementGuid>a56178bf-89ad-4f58-a9fd-63ef83d1981c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmsFilterViewModel_FilterTimeZoneTypeId</value>
      <webElementGuid>d5f61d55-bd75-4f64-a98b-c6beae754f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmsFilterViewModel.FilterTimeZoneTypeId</value>
      <webElementGuid>8b456c27-debc-4d48-a09c-dff7e8eac916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All
EST
CST
MST
PST
Samoa Standard Time
Chamorro Standard Time
ATC
AKST
HST
NST
</value>
      <webElementGuid>0b780f2b-f181-49cd-81ea-0a6ea648b81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmsFilterViewModel_FilterTimeZoneTypeId&quot;)</value>
      <webElementGuid>8cb6f825-6005-4e34-b628-6d85462b6cb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AmsFilterViewModel_FilterTimeZoneTypeId']</value>
      <webElementGuid>86ebf8d1-8390-40fe-8874-be9fec951393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/div[6]/div/select</value>
      <webElementGuid>a5091e69-8822-4c9b-b08a-716005a37e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Zone'])[1]/following::select[1]</value>
      <webElementGuid>3c131de0-d376-4be0-912a-83ae34f2c4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::select[1]</value>
      <webElementGuid>f0effcef-40c1-48fe-8c08-c25e9d3b6a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source'])[1]/preceding::select[1]</value>
      <webElementGuid>ced0d1fc-35f0-47b4-a0d4-b416c1d5e5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Owner'])[1]/preceding::select[2]</value>
      <webElementGuid>35f79050-d55e-49e8-92f2-1347ae0dbf36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>92856a0d-65f3-4076-ad69-e3625a5aebd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AmsFilterViewModel_FilterTimeZoneTypeId' and @name = 'AmsFilterViewModel.FilterTimeZoneTypeId' and (text() = 'All
EST
CST
MST
PST
Samoa Standard Time
Chamorro Standard Time
ATC
AKST
HST
NST
' or . = 'All
EST
CST
MST
PST
Samoa Standard Time
Chamorro Standard Time
ATC
AKST
HST
NST
')]</value>
      <webElementGuid>7f330dad-1f39-4d5d-a7be-79a90f272e30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
