<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>internalNote_textBox</name>
   <tag></tag>
   <elementGuidId>39da750c-52ba-4c88-8b7a-3ed14e41b5a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='LatestNote'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-3-leg-909636 > #new-carrental-quote-noorder > #dropoff-quote-0 > div.panel-body > div.row > div.col-xs-12.col-sm-6 > #LatestNote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>419627e8-3dd7-4915-b95f-d122d058a3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea-small</value>
      <webElementGuid>e05163a0-7480-4f42-974c-b0cd6c62de3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LatestNote</value>
      <webElementGuid>e70d87ec-7714-4578-94d6-9d522224386b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;concierge-quotes-accoridion-leg-2&quot;)/div[@class=&quot;panel request&quot;]/div[@id=&quot;dropoff-quotes-leg-2&quot;]/div[@class=&quot;panel-body&quot;]/div[@id=&quot;dropoff-quotes-workarea-leg-909636&quot;]/div[@id=&quot;dropoff-quotes-container-leg-909636&quot;]/div[@id=&quot;target-new-quote-type-3-leg-909636&quot;]/div[@id=&quot;new-carrental-quote-noorder&quot;]/div[@id=&quot;dropoff-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6&quot;]/textarea[@id=&quot;LatestNote&quot;]</value>
      <webElementGuid>51f7306d-b241-4364-8ae7-65d4f57e1e99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='LatestNote'])[11]</value>
      <webElementGuid>9690fe2a-06b3-4aa2-bf49-897a1effa3cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='dropoff-quote-0']/div/div/div[3]/textarea)[3]</value>
      <webElementGuid>d042a5a3-49ff-4200-b73d-b460a0ac131a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div[2]/div/div[2]/div[2]/div[3]/div/div[2]/div/div/div[3]/textarea</value>
      <webElementGuid>05b45a94-8462-4b2d-a4ae-738e4d969319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'LatestNote']</value>
      <webElementGuid>717a33c5-aae2-4309-b05b-c0641449c954</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
