<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quotedAmount_textBox</name>
   <tag></tag>
   <elementGuidId>c474931e-5651-46f4-8694-df984e3f2e35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='QuotedAmount'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-3-leg-909636 > #new-carrental-quote-noorder > #dropoff-quote-0 > div.panel-body > div.row > div.col-xs-12.col-sm-6 > div.row > div.col-xs-12.target-div-overage-reason > div.target-quoted-amount-div > #QuotedAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3eb0263-907d-4237-8ec6-fb74985e0378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>531f46a7-ac12-4d21-aac3-c35bbb28037b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-budget</name>
      <type>Main</type>
      <value>150.0000</value>
      <webElementGuid>2a613ee0-cef7-4506-9cca-fe38fb9d5947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>1d5ba291-8d26-4498-8f27-3191e32432dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>a9fc4275-1739-4241-91bb-de832935ba2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control target-concierge-quoted-amount</value>
      <webElementGuid>8ab2de64-e444-49b6-b2e2-117e885aba98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QuotedAmount</value>
      <webElementGuid>6ed319dd-8c0f-43f7-bc8d-df3003e4f77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QuotedAmount</value>
      <webElementGuid>6d302b2d-75e2-4bf2-b050-9e08944add46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;concierge-quotes-accoridion-leg-2&quot;)/div[@class=&quot;panel request&quot;]/div[@id=&quot;dropoff-quotes-leg-2&quot;]/div[@class=&quot;panel-body&quot;]/div[@id=&quot;dropoff-quotes-workarea-leg-909636&quot;]/div[@id=&quot;dropoff-quotes-container-leg-909636&quot;]/div[@id=&quot;target-new-quote-type-3-leg-909636&quot;]/div[@id=&quot;new-carrental-quote-noorder&quot;]/div[@id=&quot;dropoff-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 target-div-overage-reason&quot;]/div[@class=&quot;target-quoted-amount-div&quot;]/input[@id=&quot;QuotedAmount&quot;]</value>
      <webElementGuid>ea233906-4a3f-402c-9141-6225b3b4c2bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='QuotedAmount'])[11]</value>
      <webElementGuid>b6ad016f-0371-4a57-9eda-6dc1968b1a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='dropoff-quote-0']/div/div/div[3]/div[4]/div/div/input)[3]</value>
      <webElementGuid>968921d8-c56d-48af-b90a-ec905f3149a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div[2]/div/div[2]/div[2]/div[3]/div/div[2]/div/div/div[3]/div[4]/div/div/input</value>
      <webElementGuid>abe3e331-619e-49fd-9a49-3e76ecf02de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'QuotedAmount' and @name = 'QuotedAmount']</value>
      <webElementGuid>ba836a90-acda-4439-bcd3-ed88ff1a0d4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
