<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clear_button</name>
   <tag></tag>
   <elementGuidId>a018d348-0a31-481c-9684-bf066933e9b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ClearLeg_1 > span.add-leg-verbiage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ClearLeg_1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0e85dbda-30aa-4b24-a7ca-65ec2d86e70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-leg-verbiage</value>
      <webElementGuid>d4b1dcae-3aba-4669-8fe2-7d0db00fa5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear</value>
      <webElementGuid>7304c8df-f8c0-455b-b9fe-35181bdd8a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ClearLeg_1&quot;)/span[@class=&quot;add-leg-verbiage&quot;]</value>
      <webElementGuid>798c3ee9-87a0-40c8-a731-875e1bb9876e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ClearLeg_1']/span</value>
      <webElementGuid>d8c75c50-5ef9-4c37-8aa7-9eb2ab0f1b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::span[1]</value>
      <webElementGuid>25a981a6-54e0-49f1-a713-31c70be68df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return'])[1]/following::span[2]</value>
      <webElementGuid>4f995a37-a2f5-4e99-827b-7b27b2ee056b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::span[1]</value>
      <webElementGuid>e27f8468-4979-4c92-b871-ba8db40c04d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To navigate, press the arrow keys.'])[1]/preceding::span[2]</value>
      <webElementGuid>fb1d3739-bc9a-4ca7-be9b-e058f49ce815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clear']/parent::*</value>
      <webElementGuid>119fd502-3ab6-4d44-bc65-0981671dabf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/span</value>
      <webElementGuid>83f4007f-199e-4f23-a571-fe4e939df505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Clear' or . = 'Clear')]</value>
      <webElementGuid>e8fc775c-88cb-4cba-90b1-6bab4654da9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
