<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>departureAirportLeg1_textBox</name>
   <tag></tag>
   <elementGuidId>2d763c34-7ecf-4468-8e0d-057e010420e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leg_AirportOriginIdent1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_AirportOriginIdent1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0c513e0-1c9c-4e78-b04f-96ea9550985d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6c6bbc6-31cc-4205-aca8-782eb7ee3504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_AirportOriginIdent1</value>
      <webElementGuid>27ece596-2600-4e46-93d9-9d6b6f1ec347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_AirportOriginIdent1</value>
      <webElementGuid>ca84185b-0a59-437f-9c04-a6628f4c85ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>From</value>
      <webElementGuid>7148bbeb-02f4-45ce-9852-aefd5b164e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control transparrentbg target-airport-entry airport-entry-style target-baj-origin-airport target-baj-action-update-expanded-info flight-search-airport-field baj-airport-input-hl ui-autocomplete-input</value>
      <webElementGuid>5a4bf4de-44eb-4858-b1bd-0ef7f03d3248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>91529171-5bfa-4ac1-a02e-819c20eb3705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3b66bb69-c54b-4424-8d61-b205ab0a7a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_AirportOriginIdent1&quot;)</value>
      <webElementGuid>34277d0f-1bd0-427c-a1da-03e215b9d84d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_AirportOriginIdent1']</value>
      <webElementGuid>7214e1a4-69fe-472f-970b-b1f52cc4bba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flightSearchFormRow_1']/div[2]/div/div/input[3]</value>
      <webElementGuid>6c82ade0-1d25-4412-b651-e43c1b1492f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[3]</value>
      <webElementGuid>64d2a8c4-ff6d-4408-9b68-a7f7c227f7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leg_AirportOriginIdent1' and @name = 'leg_AirportOriginIdent1' and @placeholder = 'From']</value>
      <webElementGuid>8220c895-b4d9-4ccc-914b-3ed4693f36f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
