<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>departureDateLeg5_textBox</name>
   <tag></tag>
   <elementGuidId>2b0a6243-b5a8-47b3-89ea-d25163324ddd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_OriginDate5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leg_OriginDate5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d7f8d77-9c3b-4dd3-a88f-c1a4538c1189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a198c0f-85db-4c75-9ed0-05525c8f4e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_OriginDate5</value>
      <webElementGuid>58cb7bb9-929c-40ad-978e-58fd26ee9679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_OriginDate5</value>
      <webElementGuid>b2457005-6449-4376-ba80-11a2a7c4c35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>528fc469-ccb4-4357-8d5d-548a42810648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control transparrentbg timepickerControl baj-input-depart-date target-date-picker target-baj-action-draw-trip target-baj-action-update-expanded-info</value>
      <webElementGuid>4a6579e4-b1a6-4e3a-8877-b5e502a20f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>a5f452bc-e166-4f17-b9f8-70f867686c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>a71beb4b-0deb-449c-ab14-92e51a9a0e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Depart Date</value>
      <webElementGuid>1a0582bd-6745-4c6d-b10e-d6696919285d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>03/30/2023</value>
      <webElementGuid>a9326eff-34c9-4a1f-8afc-6f2f51855616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>6f506f14-0eeb-42e7-bac6-2e5d5650a65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_OriginDate5&quot;)</value>
      <webElementGuid>50b19513-92fa-40eb-beb4-2a2604fcd64f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_OriginDate5']</value>
      <webElementGuid>0796b70a-5643-4818-bd09-cdb86a1d1d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flightSearchFormRow_5']/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>5039131d-ead8-4626-adab-4b751141b38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>cf3b171b-4587-43e8-93be-43825e50b4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leg_OriginDate5' and @name = 'leg_OriginDate5' and @placeholder = 'Depart Date']</value>
      <webElementGuid>eebca74c-7df9-47aa-a6fa-b17f18dc0b53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
