<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>numberOfPaxLeg2_textBox</name>
   <tag></tag>
   <elementGuidId>7e874852-ab46-45ff-afd0-0f67d7fecce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leg_NumberOfPax2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_NumberOfPax2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b44fa652-2864-4330-ae30-09e34a222ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32859dad-93f3-4c85-aa22-ea5269c6f5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_NumberOfPax2</value>
      <webElementGuid>7092d2f9-cfc7-47b6-b385-fbb30f466fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_NumberOfPax2</value>
      <webElementGuid>582739c8-dfa2-4f3e-927d-4c30eb859a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control transparrentbg target-number-pax maskNumber target-baj-action-draw-trip target-baj-action-update-expanded-info</value>
      <webElementGuid>ef1ec3ac-3210-4b65-8ed5-98b826a8f9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b42efeb8-cca4-4977-8268-13f401f1b633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>575cbbbb-90e9-4526-88ef-9439ec610828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data_v_max</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>dd70141d-b8e5-4a6c-a9d3-2ed9ac297640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data_v_min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e87dfd90-e1cd-45e5-9f2b-c0a564a2098b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>PAX</value>
      <webElementGuid>acde488d-ce1a-4ea2-95fa-113690e148a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d8ba2bc9-a1e6-4941-83c8-e0829dd9927d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8c086c6f-10aa-44c2-8a85-835ff37c6206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_NumberOfPax2&quot;)</value>
      <webElementGuid>978b7704-7203-41d5-aa16-d243d65cd9e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_NumberOfPax2']</value>
      <webElementGuid>ef701d9b-32da-4b53-8664-81bf00a16822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flightSearchFormRow_2']/div[3]/div[3]/div/div/div[2]/input</value>
      <webElementGuid>662069be-a046-4c64-996e-0edace43cb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[3]/div/div/div[2]/input</value>
      <webElementGuid>a1ebb8b5-35da-44e7-b25b-1501e6546c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leg_NumberOfPax2' and @name = 'leg_NumberOfPax2' and @placeholder = 'PAX']</value>
      <webElementGuid>931acfc2-bfb2-47cf-941b-333f85470f16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
