<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>savingGuestYes_button</name>
   <tag></tag>
   <elementGuidId>ac91c4a4-132d-4cd2-b82b-1dde11361705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Yes'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#propagatepassengermodal-leg-1-passenger-3 > div.modal-dialog > div.modal-content > div.modal-body > div.row > div.col-xs-4 > #Yes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7dcdc1c-3b02-4dce-a073-f56b891b1e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn-small</value>
      <webElementGuid>c8a32310-195d-4a2f-9421-23f3ceaf01bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2caf97df-5d3a-4875-9b99-0bcd6e0723e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>d4167675-dc9b-43cc-9b4e-af0b0a4741b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>eefd9300-d300-4c4c-aa34-5ab321cb3cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propagatepassengermodal-leg-1-passenger-3&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4&quot;]/input[@id=&quot;Yes&quot;]</value>
      <webElementGuid>2f0d8d96-361c-471a-80a2-c5a309fbeaff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Yes'])[3]</value>
      <webElementGuid>a894b3e8-45df-4a72-9680-69243a20d320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='propagatepassengermodal-leg-1-passenger-3']/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>d9419120-fe2a-492c-9593-194d55548d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>92517ff2-1c42-4a5f-a14b-f412bdea5e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'Yes']</value>
      <webElementGuid>a4c28db7-aaa4-441c-b66b-bb1122d93c5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
