<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firearms_checkBox</name>
   <tag></tag>
   <elementGuidId>63cc4421-e7c4-4899-91d8-07ab69022338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_1__FirearmsDescriptionNone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__FirearmsDescriptionNone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a07ef1b7-46b4-45d4-b62e-8b77b94e2311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom form-check-input target-firearms-nonecheckbox</value>
      <webElementGuid>22c4742d-1ff4-4aee-83b4-2bc8044fe3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fd5e3a86-305b-4690-b43e-b70708998c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The FirearmsDescriptionNone field is required.</value>
      <webElementGuid>457d51f9-f99a-440e-bd39-1fc43cbf33b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__FirearmsDescriptionNone</value>
      <webElementGuid>4db167c2-de28-4197-aab3-ce492eb21749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].FirearmsDescriptionNone</value>
      <webElementGuid>f472662f-40a1-431b-9cee-a356fc8e1bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>daef3e11-177b-4eb7-8bfd-25872712ab6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ddd6ba6e-d8f8-4d2f-a04d-e8f04605bf45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__FirearmsDescriptionNone&quot;)</value>
      <webElementGuid>1ae541dd-c795-48b9-8008-6871c0a699cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_1__FirearmsDescriptionNone']</value>
      <webElementGuid>43f8f5c7-86c7-453b-a089-6dbbcfea4aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div[2]/div[3]/div/div/input)[2]</value>
      <webElementGuid>01a5b9fd-ed9f-49cb-a612-d110db643ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>a1440782-ecba-49cc-af08-b88763c8113a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_1__FirearmsDescriptionNone' and @name = 'Legs[1].FirearmsDescriptionNone' and @type = 'checkbox']</value>
      <webElementGuid>de07ee80-233d-4bf2-9d7a-cf7937073db4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
