<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>luggage_textBox</name>
   <tag></tag>
   <elementGuidId>d2268a2d-4b44-434f-a196-20ec0d168242</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Legs_1__LuggageDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__LuggageDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0c8e80c6-3b4c-4305-9fbb-4d5f235b7208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-textarea form-control target-luggage-description</value>
      <webElementGuid>4c9123c7-25d8-4349-8c34-0060bbe63595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>21514282-9c6e-41b8-91d7-97629e0768f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__LuggageDescription</value>
      <webElementGuid>6baf77c1-b722-43ea-9f50-de38d0ad3a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].LuggageDescription</value>
      <webElementGuid>7286bab0-c1cb-4fe6-b9d4-98ae56a60ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0a3d5974-b03a-4907-bada-9c270d88351e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__LuggageDescription&quot;)</value>
      <webElementGuid>f5887f77-2a4b-4233-81fc-8874a3468352</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Legs_1__LuggageDescription']</value>
      <webElementGuid>f72ccce2-3dfb-4439-a680-1f50673144c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div/div[5]/textarea)[4]</value>
      <webElementGuid>976faea9-5c48-407a-b441-b19260813aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/div/div/div/div[5]/textarea</value>
      <webElementGuid>a8c689ed-4341-4ed7-b559-cdf50bba80f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Legs_1__LuggageDescription' and @name = 'Legs[1].LuggageDescription']</value>
      <webElementGuid>c71b68cf-7533-4e18-95ba-4f1dca5ea642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
