<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>luggage_checkBox</name>
   <tag></tag>
   <elementGuidId>338eb21d-fc3b-4f49-beca-342f9c27b8f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_1__LuggageDescriptionNone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__LuggageDescriptionNone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d3c3e7d-fc21-4e34-ad6f-611701a8b178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom form-check-input target-luggage-nonecheckbox</value>
      <webElementGuid>9c26c368-0de2-468f-b5f3-ff10276b3b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>83e57ed8-22cf-4f12-b1a8-c164b3096a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The LuggageDescriptionNone field is required.</value>
      <webElementGuid>718c6a19-2094-430f-bd9d-ebbb403d170b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__LuggageDescriptionNone</value>
      <webElementGuid>102fbf85-68cd-4955-9198-67bfdc3afe45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].LuggageDescriptionNone</value>
      <webElementGuid>dc165c19-a984-49ee-92f7-0a80d385b779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c6e0f593-0ccf-4994-9c5f-e83bdcb00b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc35f804-0e36-4e6a-9211-1cff768e9bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__LuggageDescriptionNone&quot;)</value>
      <webElementGuid>dbce32b2-1998-421c-b85c-878de8e7d257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_1__LuggageDescriptionNone']</value>
      <webElementGuid>5b69769d-b970-44e1-9723-3a4daade868e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div/div[3]/div/div/input)[4]</value>
      <webElementGuid>dba8872e-86dd-45d4-b98b-2a4b2b7a158e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>4647347a-17f8-40e3-b4da-766a87eb6c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_1__LuggageDescriptionNone' and @name = 'Legs[1].LuggageDescriptionNone' and @type = 'checkbox']</value>
      <webElementGuid>86e288f3-58cd-48dc-932a-5b1119e5b2e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
