<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dateFilterColumn_closeButton</name>
   <tag></tag>
   <elementGuidId>486ea369-304b-4e8a-a81a-822e08fef3ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='one-loop-search']/fieldset/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>fieldset > div.loop-plan-filter > div.target-clear-loop-search.clear-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2b4c490-b6d7-4a9a-b1ff-1e18d53d6ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-clear-loop-search  clear-icon</value>
      <webElementGuid>0723c3e0-3004-4be4-bf49-b123f7aaa622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-loop-search&quot;)/fieldset[1]/div[@class=&quot;loop-plan-filter&quot;]/div[@class=&quot;target-clear-loop-search  clear-icon&quot;]</value>
      <webElementGuid>3783f512-1077-4cfc-8c03-bc7250ff1aa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='one-loop-search']/fieldset/div/div</value>
      <webElementGuid>694b05e4-aeb7-4857-95b6-ccbb2ac8c203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div</value>
      <webElementGuid>b44c814f-bcd8-4406-bb39-248a1d4519df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
