<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loopName_textBox</name>
   <tag></tag>
   <elementGuidId>cbf7ff76-66ca-4b07-ac39-76cb6bf12d1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoopPlanSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LoopPlanSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5add894-c19b-4460-969e-ae096dce82eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e1a27ba-ce32-4428-a079-96c3104166af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoopPlanSearch</value>
      <webElementGuid>658d6ca7-ab3a-4bae-97f6-e5bc706784d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Loop Plan</value>
      <webElementGuid>4540095e-4dfd-4b65-ab69-bf356379ce2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoopName</value>
      <webElementGuid>10213cd8-e928-43ef-a825-a6e47e583b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-one-loop-plan-autocompelete target-filter-element input-with-clear-button ui-autocomplete-input</value>
      <webElementGuid>28da3225-8234-4fea-89b2-54412d539a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d91c0f30-efdf-4c0e-bf86-43f8803b92f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoopPlanSearch&quot;)</value>
      <webElementGuid>9cc47dab-babc-4033-9b5d-a092bee37647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoopPlanSearch']</value>
      <webElementGuid>eb550fa0-53d3-4882-acc8-55a58201a208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='one-loop-search']/div/div/input</value>
      <webElementGuid>ea2cbb43-2911-40dd-89e6-535e7611adae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>fd9a8ac2-a8d4-417f-ac5f-05a7fedac936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'LoopPlanSearch' and @placeholder = 'Search Loop Plan' and @name = 'LoopName']</value>
      <webElementGuid>8f0d9e5a-c9c2-4cba-95f8-af7b26b2a8b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
