<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>budgetOverageReason_textBox</name>
   <tag></tag>
   <elementGuidId>918b4e7d-7a21-4541-9e38-79eed98c657e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='OverageReason'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropoff-quote-0 > div.panel-body > div.row > div.col-xs-7 > div.row > div.target-enter-quoted-amount > div.col-xs-12.target-div-overage-reason > div.target-quoted-amount-div > #OverageReason</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cb687ae5-e61c-4fce-a135-69a07250c72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OverageReason</value>
      <webElementGuid>60664b49-84d4-42cb-8460-8fed73027c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OverageReason</value>
      <webElementGuid>3701af4f-2615-4480-bbfa-c104834763e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;concierge-quotes-accoridion-leg-1&quot;)/div[@class=&quot;panel request&quot;]/div[@id=&quot;dropoff-quotes-leg-1&quot;]/div[@class=&quot;panel-body&quot;]/div[@id=&quot;dropoff-quotes-workarea-leg-909635&quot;]/div[@id=&quot;dropoff-quotes-container-leg-909635&quot;]/div[@id=&quot;target-new-quote-type-3-leg-909635&quot;]/div[@id=&quot;new-executive-quote-noorder&quot;]/div[@id=&quot;dropoff-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;target-enter-quoted-amount&quot;]/div[@class=&quot;col-xs-12 target-div-overage-reason&quot;]/div[@class=&quot;target-quoted-amount-div&quot;]/textarea[@id=&quot;OverageReason&quot;]</value>
      <webElementGuid>36ca7ac5-b696-42ff-bd81-06fe169149a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='OverageReason'])[5]</value>
      <webElementGuid>051c8fcf-1504-4bf7-a290-3d9b9fc9e543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropoff-quote-0']/div/div/div[3]/div/div[10]/div/div/textarea</value>
      <webElementGuid>f5f2bb7c-ddf0-4c22-968c-ea13c923308f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[10]/div/div/textarea</value>
      <webElementGuid>c40bde57-c0fd-4c8d-8ff2-47ffb1e19aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'OverageReason' and @name = 'OverageReason']</value>
      <webElementGuid>8e503695-5de8-4686-abbd-4e9aa6a31561</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
