<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu2</name>
   <tag></tag>
   <elementGuidId>d48f951a-18fb-40d6-b10e-48c3e29f34d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Leg_1 > div.panel-body.no-padding > div.col-xs-12.no-padding.no-margin > div.col-xs-12.col-md-4.catering-formfiled > label > span > button.target-menu-link.menu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>906a69f0-1758-4f1c-8c6f-d0143df2529a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-menu-link menu-link</value>
      <webElementGuid>b87fa483-09fa-45fb-8167-75968abdb85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6a88977e-29a0-4195-b0b4-351d1dc91f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e600b79-0e1b-424e-9d93-a3e2b16a4293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>c02da60a-bbe7-4c74-85c5-82dc6d2b56af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Leg_1&quot;)/div[@class=&quot;panel-body no-padding&quot;]/div[@class=&quot;col-xs-12 no-padding no-margin&quot;]/div[@class=&quot;col-xs-12 col-md-4 catering-formfiled&quot;]/label[1]/span[1]/button[@class=&quot;target-menu-link menu-link&quot;]</value>
      <webElementGuid>cd004daa-7f28-42d3-ad3b-798192b3be00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>c28b8666-530d-4f18-811d-9a062602148b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg_1']/div/div/div/label/span/button</value>
      <webElementGuid>650e2459-e129-4436-ae08-27e536cdd73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leg 2'])[2]/following::button[1]</value>
      <webElementGuid>a2a2f986-c859-4e46-8d4d-476a866ff55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KLAX Pick Up Details'])[1]/preceding::button[1]</value>
      <webElementGuid>a9de4a82-e804-4dd0-ae0d-61d8a64325fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[5]/preceding::button[1]</value>
      <webElementGuid>76b268d7-ef56-4a00-ac72-26344e085668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/label/span/button</value>
      <webElementGuid>728a83c9-91b4-4616-8bf5-3abdebd1827e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>737c17b3-9955-4e7e-8f22-fd2563dc3204</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
