<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu1</name>
   <tag></tag>
   <elementGuidId>660b9f0e-1d22-4e33-97bd-d5cd4f05bedd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.target-menu-link.menu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa84022f-b8d6-4426-9009-f1db1ced297e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-menu-link menu-link</value>
      <webElementGuid>7a8ac4f7-438a-4947-bcd1-5c11de043750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5a38049e-c3c2-42f3-8f34-8bab34329af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b83321f4-ec5c-4742-b974-e35e5397303f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>9e5d3dce-9130-457b-990b-d0d9fd61caf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Leg_0&quot;)/div[@class=&quot;panel-body no-padding&quot;]/div[@class=&quot;col-xs-12 no-padding no-margin&quot;]/div[@class=&quot;col-xs-12 col-md-4 catering-formfiled&quot;]/label[1]/span[1]/button[@class=&quot;target-menu-link menu-link&quot;]</value>
      <webElementGuid>270b1b22-8631-4e31-9c69-d14ca8b94ee5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>1eb96e74-0942-4127-b042-b8e6110a2608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg_0']/div/div/div/label/span/button</value>
      <webElementGuid>d26233a0-81f1-4710-a18f-db1e09561420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leg 1'])[2]/following::button[1]</value>
      <webElementGuid>3f481790-611c-4c16-81ca-7cff414af1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KAPA Pick Up Details'])[1]/preceding::button[1]</value>
      <webElementGuid>17e0e4a2-a82c-4073-881a-7f5c144487c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::button[1]</value>
      <webElementGuid>e640a3c4-2992-416d-b8d9-15c8ad83dad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menu']/parent::*</value>
      <webElementGuid>3889b9bc-2211-4d54-b675-f5268a573a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>e50a56b3-d2e0-4100-a1b8-d3d2c4b1a209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>6a355d59-826a-4b27-987a-ce7aa0a9dcab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
