<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>activateLoopPlan_button</name>
   <tag></tag>
   <elementGuidId>5adf24ff-a69a-46e6-a458-a3a16696fe4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='activateLoopItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#activateLoopItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26eedbcc-0c2e-4d2a-9b9e-3b92bffc6f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6fb21d98-4cb1-4bf0-a219-4038cee23de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-one-loop-small target-activate-loop-item</value>
      <webElementGuid>5087299f-cb8f-461a-bacb-0a64a497b361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>activateLoopItem</value>
      <webElementGuid>bc8247e4-894f-40e5-9938-77044651c535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Activate Loop Plan</value>
      <webElementGuid>f528ee42-2dac-4915-b34d-93cda9881b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loop-id</name>
      <type>Main</type>
      <value>165</value>
      <webElementGuid>f4bfd5f2-7143-48ec-8fed-4218ea88a045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loop-name</name>
      <type>Main</type>
      <value>Anya Test 1:25</value>
      <webElementGuid>6ad4c6d6-14a0-425b-99ec-e01e2028141f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>Activated</value>
      <webElementGuid>37c50943-f327-4afe-83d8-25b3d7e22b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;activateLoopItem&quot;)</value>
      <webElementGuid>4c510699-6df8-4921-9ebd-5519cff7c72b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='activateLoopItem']</value>
      <webElementGuid>3ff92813-d7a9-4620-bc3c-37fc6a1b33d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='one-loop-detail']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>81378273-2dc9-4c8f-82cf-504b86c25418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>2c0d0f0f-804c-40ba-b4ca-5627308c9c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'activateLoopItem']</value>
      <webElementGuid>4134cc27-9e6d-45e9-9a43-ad88ebbc2141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
