<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>removeFromLoop_button</name>
   <tag></tag>
   <elementGuidId>9a5073f4-b92f-4937-b3ef-f568e62f7b1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='one-loop-selected-legs-tbody']/tr[2]/td/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>18f38abb-fbdb-41c7-9350-4e10a75600f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-loop-selected-legs-tbody&quot;)/tr[2]/td[@class=&quot;one-loop-tool-tip move-to&quot;]/label[1]</value>
      <webElementGuid>85ed13d1-7a36-49b2-96b6-e92770ab59a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='one-loop-selected-legs-tbody']/tr[2]/td/label</value>
      <webElementGuid>ad7c1b36-7aea-4e4b-aadd-4b225ce70ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/table/tbody/tr[2]/td/label</value>
      <webElementGuid>d1ad0902-980b-4892-9455-ca970a5e8980</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
