<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>country_textBox</name>
   <tag></tag>
   <elementGuidId>bf7bc0a6-b208-46cb-8422-28c18646e115</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffFullAddress_Country']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffFullAddress_Country</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a541edf5-0514-456f-92d1-19312c06d455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7ffe1da0-847c-40fe-9b74-e3776570ecd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>26ed9a60-cac1-49bc-b769-0ed3457f35f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-street-address dropoff-address ui-autocomplete-input</value>
      <webElementGuid>77bdb0d2-5279-439e-ad7b-4bf1e7dccb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db98ebe7-9896-48bf-ad56-c73e2a1051a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f6f06836-988f-4bd6-b5ca-4b4d595eeb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Country must be a string or array type with a maximum length of '30'.</value>
      <webElementGuid>4853f74a-ff43-4515-93fe-ff2731f90884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>6757ead9-9309-4cc7-ae63-48a8435ba323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffFullAddress_Country</value>
      <webElementGuid>d23cf132-532c-4702-a2ba-b19e896b650e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>7b2e8aa4-f46e-4730-8b14-e9b09dd57c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[0].ActiveConciergeOrder.ExecutiveDropoffFullAddress.Country</value>
      <webElementGuid>f245d8d9-1e7a-405b-b972-a17fbde61121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffFullAddress_Country&quot;)</value>
      <webElementGuid>6cdbe68a-cbeb-48cc-acfb-90d3928eb11a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffFullAddress_Country']</value>
      <webElementGuid>81405556-4007-4057-b0ec-b3a839944554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-0-dropoffform']/div/div/div[6]/input</value>
      <webElementGuid>68d9cc75-a0f7-49c2-a84b-c89c174f584c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[6]/input</value>
      <webElementGuid>8f325891-584a-4ff7-a738-37f1583c6b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffFullAddress_Country' and @name = 'FlightPlan.Legs[0].ActiveConciergeOrder.ExecutiveDropoffFullAddress.Country']</value>
      <webElementGuid>02084b7c-4bf4-4ae1-ac7f-24019f88953d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
