<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropOffTime_textBox</name>
   <tag></tag>
   <elementGuidId>0f46be1e-2f15-4e20-9c0e-af674d291cc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffTime']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffTime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a356625-45eb-49d7-9629-161b5d0d6569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10:13 AM</value>
      <webElementGuid>41bd2d9f-f131-45e1-aebf-91eef7334c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f4daaddf-db0d-4dd1-9d32-a00e9e839c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ce49e2bf-89ba-4ad2-9ff0-d45bae74c388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>catering-formfiled-dropdown target-executive-time</value>
      <webElementGuid>eb468660-f42b-4175-b193-8839cd478815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d317d4b1-4cee-4702-ad24-7c4f19b7028a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffTime</value>
      <webElementGuid>d82355de-4874-4e23-9bde-96a13d649c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[0].ActiveConciergeOrder.ExecutiveDropoffTime</value>
      <webElementGuid>d89bbb2a-feb7-4ecd-ac46-be821fd09810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffTime&quot;)</value>
      <webElementGuid>62335c50-4ef9-4bb8-9832-bd75d73ec07b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffTime']</value>
      <webElementGuid>07df0233-ac2b-45b1-8f76-ca699c8789e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-0-dropoffform']/div/div/div[7]/input</value>
      <webElementGuid>3df7026e-2c96-4aa2-9b31-941a6d6ee949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[7]/input</value>
      <webElementGuid>c71c97c8-13f0-4a69-a5e5-a79f4c78f9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffTime' and @name = 'FlightPlan.Legs[0].ActiveConciergeOrder.ExecutiveDropoffTime']</value>
      <webElementGuid>05a1aa53-a448-4080-a37d-a58766539142</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
