<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clientAssignment_dropDownTab</name>
   <tag></tag>
   <elementGuidId>20e098f6-963d-4476-bbfd-08ecb73f6c5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div[2]/nav/ul/li[8]/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Client Assignment&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>60c41c92-57dc-460d-8b15-b833d7d6a5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ams/ClientAssignment</value>
      <webElementGuid>0660d40e-fe08-47d9-ace3-9f5e56184342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Client Assignment</value>
      <webElementGuid>167b8604-d170-455d-8659-f8afe1dd2192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Client Assignment</value>
      <webElementGuid>4d45ac26-3f37-4437-b047-89b8d34910d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;top_wrapper&quot;]/header[@id=&quot;header&quot;]/header[@id=&quot;header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row header flex-bottom&quot;]/div[@class=&quot;col-md-12&quot;]/nav[1]/ul[@class=&quot;navigation&quot;]/li[8]/ul[@class=&quot;show-sub-menu&quot;]/li[5]/a[1]</value>
      <webElementGuid>602d93a7-0b53-4460-83d2-3afc653eece9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div[2]/nav/ul/li[8]/ul/li[5]/a</value>
      <webElementGuid>4d72c135-3d4f-43a7-b42c-3354fb442713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Client Assignment')]</value>
      <webElementGuid>7af3ac27-10a8-4bf5-89a9-2dc042cc4375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add User'])[1]/following::a[1]</value>
      <webElementGuid>058bee36-a7d4-4b3e-8dea-8fedf06774d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Module Access'])[1]/following::a[2]</value>
      <webElementGuid>dbd980ee-c87f-485e-ab30-9281d86c8500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aircraft Mapping Tool'])[1]/preceding::a[1]</value>
      <webElementGuid>83f03155-9672-4c12-80f3-784fbf59da54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aircraft Manager'])[1]/preceding::a[2]</value>
      <webElementGuid>1e98c3e5-e4ed-4bce-8571-4dc186012a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Client Assignment']/parent::*</value>
      <webElementGuid>92b45791-8453-42d5-838b-2414d6560c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ams/ClientAssignment')]</value>
      <webElementGuid>2ce1df13-2631-4052-b5af-09e8141f0a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[5]/a</value>
      <webElementGuid>70423b31-1735-40a9-a613-95ffcf1aa035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ams/ClientAssignment' and @title = 'Client Assignment' and (text() = 'Client Assignment' or . = 'Client Assignment')]</value>
      <webElementGuid>f0ec196b-12ee-4e11-ae28-f21c2ae15c2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
