<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>back_button</name>
   <tag></tag>
   <elementGuidId>23238d9e-bba1-43c0-a5f0-9e88fddc27a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.target-pager-back.target-pager-input.target-pager-back-new.btn.btn-default.btn-xs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='one-loop-saved-loops']/div[2]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5c850ab5-1821-4b26-bdf4-b244e5947f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-pager-back target-pager-input target-pager-back-new btn btn-default btn-xs</value>
      <webElementGuid>b8386ce0-3f7d-4131-959d-87661d1005d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt; Back</value>
      <webElementGuid>c75c657b-87f8-4272-9c68-e594f54c6569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-loop-saved-loops&quot;)/div[2]/div[@class=&quot;float-right&quot;]/button[@class=&quot;target-pager-back target-pager-input target-pager-back-new btn btn-default btn-xs&quot;]</value>
      <webElementGuid>046a994d-9529-4080-8921-58b1a837b70d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='one-loop-saved-loops']/div[2]/div[2]/button</value>
      <webElementGuid>ee19e766-abde-4c16-8b7f-3709d7a7b2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add new Loop'])[1]/following::button[1]</value>
      <webElementGuid>cbf4e89b-e921-4c0c-8e66-e8f62e445888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date To'])[1]/following::button[1]</value>
      <webElementGuid>0dc3e9aa-753d-4e43-bfa7-58ec2ba07443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 4'])[1]/preceding::button[1]</value>
      <webElementGuid>514c6e5b-004e-4dac-bdc9-21d7c1ae93a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forward >'])[1]/preceding::button[1]</value>
      <webElementGuid>9e5a622b-059c-4a82-be61-2349a0576ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt; Back']/parent::*</value>
      <webElementGuid>978b6288-eba2-492f-948c-259792e6441d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>4b81bf3b-8186-4d2d-b752-e078d0cf31a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '&lt; Back' or . = '&lt; Back')]</value>
      <webElementGuid>633943c1-b3a8-4f15-a8a0-57fc48c19419</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
