<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>forward_button</name>
   <tag></tag>
   <elementGuidId>f513a95c-9983-4d86-bd81-e0a19d85fd0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.target-pager-forward.target-pager-input.target-pager-forward-new.btn.btn-default.btn-xs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='one-loop-saved-loops']/div[2]/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>663156be-c0a9-4792-85c1-cbab34e3376f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-pager-forward target-pager-input target-pager-forward-new btn btn-default btn-xs</value>
      <webElementGuid>fe5f0498-0619-4eb9-a20e-b8840c9359fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forward ></value>
      <webElementGuid>bc7c8188-6569-4e05-99ca-156e44247255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-loop-saved-loops&quot;)/div[2]/div[@class=&quot;float-right&quot;]/button[@class=&quot;target-pager-forward target-pager-input target-pager-forward-new btn btn-default btn-xs&quot;]</value>
      <webElementGuid>675ec155-9343-4585-a046-2c1ec416145e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='one-loop-saved-loops']/div[2]/div[2]/button[2]</value>
      <webElementGuid>10ff60f3-9b59-45b2-bb1b-bb35d6b6ff90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 4'])[1]/following::button[1]</value>
      <webElementGuid>8bd7a77c-0fb1-4966-84af-4e48d409a684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt; Back'])[1]/following::button[1]</value>
      <webElementGuid>bf5b93ca-386a-4cc9-9015-1da373ab80df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nadya Rassadina'])[2]/preceding::button[1]</value>
      <webElementGuid>5031f9ef-8d17-41b8-a4ff-c9b02ef26524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Challenger 601'])[2]/preceding::button[1]</value>
      <webElementGuid>90f2763d-6d5d-4c52-ab03-f397e918f2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forward >']/parent::*</value>
      <webElementGuid>3815ef77-802b-4a8e-bc08-cbed95185bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>854a64cc-c7aa-41b3-b953-1b9baa02face</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Forward >' or . = 'Forward >')]</value>
      <webElementGuid>7860b532-748d-4878-8903-e7e8a107caaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
