<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputPageNumber_textBox</name>
   <tag></tag>
   <elementGuidId>af4cd86b-c4f6-4dfe-8ce7-d3e4671142b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.target-current-page-new.target-pager-input.pager-page-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='1'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>140ca00f-27c2-49bc-92d1-72db405e04b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-current-page-new target-pager-input pager-page-number</value>
      <webElementGuid>ad772143-3abe-475b-9e43-04c42310e235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7225aaef-9c20-4735-b42f-6275b0cae59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>17f35582-f955-47ff-b70a-1ddf2de270ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-loop-saved-loops&quot;)/div[2]/div[@class=&quot;float-right&quot;]/input[@class=&quot;target-current-page-new target-pager-input pager-page-number&quot;]</value>
      <webElementGuid>51007632-36ff-4056-a5c8-9bf62c182c46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='1'])[2]</value>
      <webElementGuid>2a82f712-f502-41e0-a4b9-57d89e6056cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='one-loop-saved-loops']/div[2]/div[2]/input[2]</value>
      <webElementGuid>f75e1451-ccc7-4323-af9a-d85b8a56f09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>1106fe5f-77ab-447f-80ed-86b70f9e7d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
