<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>accountBalance_value</name>
   <tag></tag>
   <elementGuidId>14d2b7cf-9e47-4bdf-80d5-a0f194c7e025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='FlightPlan']/div/div/div[2]/div/div[2]/div[2]/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-4.black-tighter-label.bold > span.font-black</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a474b89-520c-4611-bb22-1616602ee33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-black</value>
      <webElementGuid>c0924a85-5b68-4db6-bbf0-4702476240c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$901,426.60</value>
      <webElementGuid>65cf2376-0752-4b74-b58c-d9fa0eb0c6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;content target-flight-plan-main&quot;]/div[@class=&quot;row ams-workflow-container&quot;]/div[@class=&quot;col-xs-8 target-flight-plan-trip-request-main&quot;]/div[@class=&quot;content target-flight-plan-trip-request-input&quot;]/div[@class=&quot;trip-details&quot;]/div[@class=&quot;row ams-itinerary-row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;col-xs-4 black-tighter-label bold&quot;]/span[@class=&quot;font-black&quot;]</value>
      <webElementGuid>f5390f5e-4de1-40ce-9ec6-2a248262576f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div/div[2]/div[2]/div/div[2]/span</value>
      <webElementGuid>a9212968-b691-4d2b-ae5a-3ae576a0c076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$901,426.60']/parent::*</value>
      <webElementGuid>c9cdf66d-ad96-4e46-bb03-7344a0d6f616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span</value>
      <webElementGuid>68274301-bd4f-41d1-bd34-ceaa1cd516c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$901,426.60' or . = '$901,426.60')]</value>
      <webElementGuid>38508492-0b22-4e38-a394-118282e35877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
