<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pdf_icon</name>
   <tag></tag>
   <elementGuidId>0568b62b-f9d2-4b0d-b6e8-7802922b4f0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='FlightPlan']/div/div/div[2]/div[2]/div[3]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-file-pdf.target-tripsheet-download.target-preview-pdf.cursor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>06a8e200-7872-4da0-8d56-a067d53c2cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-file-pdf target-tripsheet-download target-preview-pdf cursor</value>
      <webElementGuid>b263489b-4eba-401d-9899-741da8a29bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>31d1f6fa-4a30-4078-afa0-d7cd8026d2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Preview Trip Sheet Pdf</value>
      <webElementGuid>33dd8244-e996-406a-9daf-2fe7a5e009dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flightplanid</name>
      <type>Main</type>
      <value>580423</value>
      <webElementGuid>b14281a6-1b9f-4cdb-97d2-8e2b16b0a7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;content target-flight-plan-main&quot;]/div[@class=&quot;row ams-workflow-container&quot;]/div[@class=&quot;col-xs-8 target-flight-plan-trip-request-main&quot;]/div[@class=&quot;content target-flight-plan-trip-request-aircraft-list request-list&quot;]/div[@class=&quot;col-xs-12 download-ts-pdf-button&quot;]/i[@class=&quot;fa fa-file-pdf target-tripsheet-download target-preview-pdf cursor&quot;]</value>
      <webElementGuid>b1e4af88-42b6-466d-8ac9-02da4e5cc960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div[2]/div[3]/i</value>
      <webElementGuid>dffd74da-0449-4201-ab09-fb088e9bb4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/i</value>
      <webElementGuid>994da87a-28b4-4501-b0df-c9eaf0fa49ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Preview Trip Sheet Pdf']</value>
      <webElementGuid>272559e0-252e-4b31-9790-239096b551e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
