<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_textBox</name>
   <tag></tag>
   <elementGuidId>59d1f20a-3a2f-45b5-a62f-f1a8e93213e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__OriginDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__OriginDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b622f772-165c-4b89-90a3-a36699e035c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-date-picker black-tighter-input target-flight-plan-input-origin-date form-control hasDatepicker</value>
      <webElementGuid>09fc7ccf-ea95-4c41-9a22-16400b18d25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>38354c3f-2ff6-4b92-a46f-ab97579514c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Date/Time field is required.</value>
      <webElementGuid>407164f8-d789-407d-ab33-f177f5b309ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__OriginDate</value>
      <webElementGuid>001a8844-01b8-4c01-8ac7-61fbecccfd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].OriginDate</value>
      <webElementGuid>5f70ccd5-eb84-48c9-a1b2-710a11e1d0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae15e04e-7ac5-43a4-ade0-8dfafd18b15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>05/03/2023</value>
      <webElementGuid>ff075499-7273-4f58-815e-096bcf657fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__OriginDate&quot;)</value>
      <webElementGuid>de7a2d93-6242-46de-af81-6d44aef6c58a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__OriginDate']</value>
      <webElementGuid>9751e05f-cdd3-4666-b59f-5cef137e33e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909766']/div[6]/input</value>
      <webElementGuid>64861803-47ba-40d4-a8a7-0f2b9275483c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[6]/input</value>
      <webElementGuid>f3ad39b8-efad-4d38-bac7-992c3a341f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_0__OriginDate' and @name = 'Legs[0].OriginDate' and @type = 'text']</value>
      <webElementGuid>15c361d6-627d-4dc8-8f76-a293fb5cd8e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
