<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>from_textBox</name>
   <tag></tag>
   <elementGuidId>c2afc893-a80d-46fd-bfa4-fb9e3cbb9c7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__AirportOriginIdent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__AirportOriginIdent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e80086d2-588f-43d2-8067-f49ae6ce57e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-airport-entry black-tighter-input form-control ui-autocomplete-input</value>
      <webElementGuid>d1250d59-5a62-42ae-991d-d9c931ff1cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__AirportOriginIdent</value>
      <webElementGuid>f8caca43-92d7-476f-b3bb-312d647a7b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].AirportOriginIdent</value>
      <webElementGuid>3adbc44d-0937-4444-9541-801a7bdfe5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>663755cb-1a62-45ee-a329-e060793daf42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>KAPA</value>
      <webElementGuid>62ca770d-aa42-491a-91be-5e9bf0b7081e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c2ce90c0-e485-4fc4-a987-99be366561a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__AirportOriginIdent&quot;)</value>
      <webElementGuid>23d718a5-b696-40bc-be84-cacfb97e7781</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__AirportOriginIdent']</value>
      <webElementGuid>92d3d9bf-4f2c-47e0-956c-f482b93761dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909766']/div[3]/input</value>
      <webElementGuid>bee7afb9-56d8-477c-8413-733a3d2cf862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div/div[3]/input</value>
      <webElementGuid>152ee76e-b039-4857-9e5b-161541b84e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_0__AirportOriginIdent' and @name = 'Legs[0].AirportOriginIdent' and @type = 'text']</value>
      <webElementGuid>1f340020-6528-4459-8267-726990d5b047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
