<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>time_textBox</name>
   <tag></tag>
   <elementGuidId>bd983a1e-f4d0-4ed2-9013-017406a23b08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__OriginHour</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__OriginHour']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe1541d9-9d58-4d7b-b463-4788f58ba7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-time-picker black-tighter-input target-flight-plan-input-origin-time form-control</value>
      <webElementGuid>0d53ab14-443e-4cd8-800e-080fc55ea8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d070adcf-ff6d-47a8-aaba-13ab8a6139e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Time field is required.</value>
      <webElementGuid>270370e7-b14a-43e0-87f0-896065f478f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__OriginHour</value>
      <webElementGuid>fa3406ea-9d04-41bf-b74d-43d9acbd0617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].OriginHour</value>
      <webElementGuid>21abddff-968e-408f-a4ad-7346c9dfe258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a74cb4f-9c28-4b45-9915-dac25f76c2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>09:00</value>
      <webElementGuid>1c1757e1-2302-4954-a975-1c3c8420a58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__OriginHour&quot;)</value>
      <webElementGuid>72e24f6a-66bf-4878-8810-50eaca7e8317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__OriginHour']</value>
      <webElementGuid>06295345-e9c8-44f0-90f5-eb3fcdb4de07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909766']/div[7]/input</value>
      <webElementGuid>a5eca83d-73df-4923-bc78-9c679a67dea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[7]/input</value>
      <webElementGuid>7f8c6822-76f6-49bb-bb96-4de23ce6faf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_0__OriginHour' and @name = 'Legs[0].OriginHour' and @type = 'text']</value>
      <webElementGuid>b1288ffd-c7f0-4d09-b07a-10d6fff0233f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
