<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>first_textBox</name>
   <tag></tag>
   <elementGuidId>e8d08f41-b5cf-4b0e-8bad-3b9f54a42b34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__Passengers_1__FirstName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_1__FirstName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>806207fb-3e2d-407b-beb2-7b04f2495f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>a6e5c9fd-cd35-4534-8fd7-2e90cef16861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control target-pax-firstname</value>
      <webElementGuid>75cec425-fcef-40a6-bea8-cd9259017004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e15b953-3858-4779-a3c7-1aeb8200a297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5a041ea8-7652-4b70-b0ae-e07e4b6a0085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field First must be a string or array type with a maximum length of '64'.</value>
      <webElementGuid>ec8acf3e-9533-4c18-992d-d7a984253b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>06533138-07b7-431d-8f03-f5484a188315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The First field is required.</value>
      <webElementGuid>752178c8-3623-4121-9896-3b3165fe437c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_1__FirstName</value>
      <webElementGuid>d30a7205-7ea1-4ea2-9cab-9ebbd0e30187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>75b4528e-de18-44bb-9276-e76b4832eec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[1].FirstName</value>
      <webElementGuid>3719c288-dbc3-4586-b15b-aca3bc3c3f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_1__FirstName&quot;)</value>
      <webElementGuid>63c922ce-389b-42b5-8864-b79d6d0001cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__Passengers_1__FirstName']</value>
      <webElementGuid>298448e0-2e09-4c56-a688-14034495d9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-2']/div[3]/div[2]/div/div/div/div/input</value>
      <webElementGuid>79690772-44b9-491f-853c-a75bb1d16a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/input</value>
      <webElementGuid>88d00df0-3f9d-4042-96be-b082ded3edd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Legs_0__Passengers_1__FirstName' and @name = 'Legs[0].Passengers[1].FirstName']</value>
      <webElementGuid>b1f9fb0d-54b2-401f-9789-cd11b8004e8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
