<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>passport_textBox</name>
   <tag></tag>
   <elementGuidId>b9b8efd5-48fd-488c-b464-f793b59a14b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__Passengers_1__PassportNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_1__PassportNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ac406df-2b8a-4f25-bf9f-6b5b7a73d17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>16ceaaca-27ce-43f3-80e0-c13bf19b6199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control</value>
      <webElementGuid>46a81c52-ebb1-484b-aa3d-2502233367f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e951b16-748b-4384-96cc-97e07aa8604e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_1__PassportNumber</value>
      <webElementGuid>4413e9d6-fa28-4d72-bd82-cb0bd1ec1664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[1].PassportNumber</value>
      <webElementGuid>33d6c598-4bfa-41dd-b7c9-bc89c41e75d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_1__PassportNumber&quot;)</value>
      <webElementGuid>ca647dda-51d5-44fe-8fbb-7357843a5a97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__Passengers_1__PassportNumber']</value>
      <webElementGuid>e1a3d169-a652-4e6a-aa85-398a449c2375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-2']/div[3]/div[2]/div/div[6]/div/div/input</value>
      <webElementGuid>45023b77-0cf1-4dd9-8f90-0eb1eb4dfb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[6]/div/div/input</value>
      <webElementGuid>fd1b9db1-aea0-4348-918e-368a405e56b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Legs_0__Passengers_1__PassportNumber' and @name = 'Legs[0].Passengers[1].PassportNumber']</value>
      <webElementGuid>4fa010ec-02d2-49b0-9a4d-7611b06a9c14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
