<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>savePassenger_button</name>
   <tag></tag>
   <elementGuidId>de966f4e-3d04-4b9c-8f0e-ad170378e5e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Save Passenger'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.baj-btn.target-baj-results-button-save-passenger.l1p2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2e1f5f3-8c5e-47e2-8b8f-0a4593036819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn target-baj-results-button-save-passenger l1p2</value>
      <webElementGuid>28aad5bd-5681-48eb-b6be-053e4ad14bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-number</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>50d58f92-0f4e-4062-b0a7-4661528a5fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>500f6c9b-6d47-48f4-92f7-fa57a192b425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-id</name>
      <type>Main</type>
      <value>1861836</value>
      <webElementGuid>d5de95e6-4858-4147-8eea-c911b0285489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-class</name>
      <type>Main</type>
      <value>l1p2</value>
      <webElementGuid>6cf8632f-0540-4108-827f-09406409d2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-number-of-legs</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1454b932-09dc-4055-b4c0-ba0713325478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dab6db54-02f7-4fb1-9cf4-07b6739a43e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save Passenger</value>
      <webElementGuid>fc71bade-f7d3-47ea-af96-3ac58f618c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passengercontainer-leg-1-number-2&quot;)/div[@class=&quot;clearfix baj-results-pax-grid-box&quot;]/div[@class=&quot;save-passenger-container   no-margin&quot;]/div[@class=&quot;row clearfix&quot;]/div[@class=&quot;col-xs-12 text-center&quot;]/input[@class=&quot;baj-btn target-baj-results-button-save-passenger l1p2&quot;]</value>
      <webElementGuid>e6cf54c7-ce59-438a-85b4-896776a70bad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Save Passenger'])[2]</value>
      <webElementGuid>c1bb0da2-b23a-493a-9abe-e591f0c1d445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-2']/div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>e2afd6c8-7a2f-4e09-b553-45c1a3ffa9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>0bceef5e-d1bf-4820-8a47-e8f7731232e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>fe9ba453-8a6f-4adf-ba29-1a1e1c4c084d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
