<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modifiedDate_filter</name>
   <tag></tag>
   <elementGuidId>8ead9150-f15a-4649-9e23-e83bc2152685</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='one-loop-saved-loops-table']/thead/tr/td[9]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td[name=&quot;LastUpdatedDate&quot;] > div.thead-arrow-div > a.target-new-sort-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb06b5af-738c-4a36-95c8-79878f57b26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f45c222d-c84b-4e0a-9e38-16c1373caa1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-new-sort-header</value>
      <webElementGuid>b405e877-d303-4235-bd6f-59b6cbf6eb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sort</name>
      <type>Main</type>
      <value>LastUpdatedDate</value>
      <webElementGuid>71b690cb-e9db-4805-bfe1-d6f6bf106588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Modified Date
                        </value>
      <webElementGuid>567ba8c8-59ea-47c9-8909-d8995a139cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-loop-saved-loops-table&quot;)/thead[1]/tr[1]/td[9]/div[@class=&quot;thead-arrow-div&quot;]/a[@class=&quot;target-new-sort-header&quot;]</value>
      <webElementGuid>d2f50c3f-3e5c-41c8-bc22-73f0a2396993</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='one-loop-saved-loops-table']/thead/tr/td[9]/div/a</value>
      <webElementGuid>745ec182-e9a9-4958-9f09-1dfdaab07a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Modified Date')]</value>
      <webElementGuid>1264ccdb-ef2a-4c14-8ab4-647291dfd0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forward >'])[1]/following::a[9]</value>
      <webElementGuid>d12e9f14-9f6a-4260-9c5a-8c0b1949a111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 4'])[1]/following::a[9]</value>
      <webElementGuid>638cf420-23f7-4823-949d-9023518b684f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(SLC) 11/28 - 11/30'])[1]/preceding::a[3]</value>
      <webElementGuid>d0fb963f-2c77-4187-9391-0827f5e78cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eugene Trujillo'])[2]/preceding::a[3]</value>
      <webElementGuid>6da8f092-736d-4f8a-bae6-d3a470340187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Modified Date']/parent::*</value>
      <webElementGuid>99aa3703-36e3-4102-a4f0-f6c4939d2633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[21]</value>
      <webElementGuid>506b4e5f-874a-4247-a245-ee64c5951ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/a</value>
      <webElementGuid>581291d4-780a-4012-af87-45568a0c2c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '
                            Modified Date
                        ' or . = '
                            Modified Date
                        ')]</value>
      <webElementGuid>5ba23934-f0ea-49f5-9708-20db3d7080a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
