<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tailN_filter</name>
   <tag></tag>
   <elementGuidId>383eb83e-73d7-46fb-aca6-2b5e91569a7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='one-loop-saved-loops-table']/thead/tr/td[5]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td[name=&quot;OperatorAircraftTailN&quot;] > div.thead-arrow-div > a.target-new-sort-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>39c89008-134b-49d9-be1b-9632cf84f6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>118d1f29-9415-4226-a75e-bd9d12aa2c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-new-sort-header</value>
      <webElementGuid>e0eaa565-bebe-4536-ae26-a62234c0a5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sort</name>
      <type>Main</type>
      <value>OperatorAircraftTailN</value>
      <webElementGuid>fe949d7b-25e0-44a8-9bb8-92b4da66582a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Tail N
                        </value>
      <webElementGuid>11aecbc6-1418-49a8-84db-fb4dc5aa981a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-loop-saved-loops-table&quot;)/thead[1]/tr[1]/td[5]/div[@class=&quot;thead-arrow-div&quot;]/a[@class=&quot;target-new-sort-header&quot;]</value>
      <webElementGuid>b414bce5-4d7d-43d2-8646-f0ad280b1b63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='one-loop-saved-loops-table']/thead/tr/td[5]/div/a</value>
      <webElementGuid>e0a905aa-d50f-4735-a157-08b2c01933b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tail N')]</value>
      <webElementGuid>3dd2bc8a-e448-45bb-a0d1-4492137ba5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forward >'])[1]/following::a[5]</value>
      <webElementGuid>864bc5fa-6181-4a9b-b321-0423f0b9a6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 4'])[1]/following::a[5]</value>
      <webElementGuid>5c2d6748-3483-4084-bd0d-ca73b5f8cf9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(SLC) 11/28 - 11/30'])[1]/preceding::a[7]</value>
      <webElementGuid>fcaa2dd5-3e0a-4330-9156-da6577164d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eugene Trujillo'])[2]/preceding::a[7]</value>
      <webElementGuid>d831aa05-17e0-4944-a4d3-32722b8099f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tail N']/parent::*</value>
      <webElementGuid>b1e07e43-1ef0-4229-8aa4-261c5b760f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[17]</value>
      <webElementGuid>18116a78-3c73-4086-a23f-cf314bb6a6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/a</value>
      <webElementGuid>c58b99c6-5cd2-419b-88e6-2134f0752498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '
                            Tail N
                        ' or . = '
                            Tail N
                        ')]</value>
      <webElementGuid>c5d90a09-8f4e-463c-acd6-c3c6df1d24ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
