<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>street_textBox</name>
   <tag></tag>
   <elementGuidId>f41652a4-9d93-4dd0-8e5d-99944a0ad6da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AmericanExpressRequest_billing_address_street</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AmericanExpressRequest_billing_address_street']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15620bf3-6ee9-4578-a526-112f58af1911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>28ff44f5-ba69-4acb-bdd5-daa0197c5691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control font-weight-normal</value>
      <webElementGuid>26f8b067-3517-4486-a672-7b0e95e01e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street</value>
      <webElementGuid>0c4e9e8f-5a2a-429a-bb47-520e44a1d6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>08e859a5-5e92-420e-9efd-085538147e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Street field is required.</value>
      <webElementGuid>f315d9b6-2323-44ed-80d7-24d9f8159fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmericanExpressRequest_billing_address_street</value>
      <webElementGuid>6a9fde6c-bfbb-4188-af6d-a22686dfe88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmericanExpressRequest.billing.address.street</value>
      <webElementGuid>56641195-622b-46a4-aecf-a9667e79a0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmericanExpressRequest_billing_address_street&quot;)</value>
      <webElementGuid>940328c1-e541-4b79-999b-b0f22355942f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AmericanExpressRequest_billing_address_street']</value>
      <webElementGuid>77ea95dc-2b1a-46e5-be52-b148bf749cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-itinerary-amex-data']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>6386578d-d847-4aac-8132-e5634cfe2eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>158df1f8-56ec-4b37-b952-07600bfb4d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Street' and @id = 'AmericanExpressRequest_billing_address_street' and @name = 'AmericanExpressRequest.billing.address.street']</value>
      <webElementGuid>210028b1-f527-41b9-be39-fb31c98e82ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
