<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>year_dropDown</name>
   <tag></tag>
   <elementGuidId>0fd805e0-8554-44ea-985f-bfd25b9d6b08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AmericanExpressRequest_sourceOfFunds_provided_card_expiry_year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AmericanExpressRequest_sourceOfFunds_provided_card_expiry_year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d0021ab3-059e-4508-9074-b2bdd588ddae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control font-weight-normal</value>
      <webElementGuid>0e72d8aa-7a2e-413c-ab1b-5f54115296d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ee20565d-8757-4d38-8a9f-dc5dec86c2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Year field is required.</value>
      <webElementGuid>720a2ed6-5065-46ad-beaf-0cd9686d37fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmericanExpressRequest_sourceOfFunds_provided_card_expiry_year</value>
      <webElementGuid>dd2419e1-cfa8-4745-83ec-98b8e5631124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmericanExpressRequest.sourceOfFunds.provided.card.expiry.year</value>
      <webElementGuid>c1ac10cc-b97f-4dcc-94ac-734e77d9c16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YY</value>
      <webElementGuid>8acffe35-7715-410d-bd39-e376dbdf5516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Year
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
</value>
      <webElementGuid>edb995c3-c923-4469-88ea-8aa56be71b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmericanExpressRequest_sourceOfFunds_provided_card_expiry_year&quot;)</value>
      <webElementGuid>e943e1d7-5505-4b93-9f9a-3b562a35bb14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AmericanExpressRequest_sourceOfFunds_provided_card_expiry_year']</value>
      <webElementGuid>7139761e-4b56-4cc9-8eaf-0486f7f2e0c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-itinerary-amex-data']/div[2]/div/div[3]/div[2]/div/select</value>
      <webElementGuid>e60a3074-1dda-4d11-abac-a762267cfb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/following::select[1]</value>
      <webElementGuid>c48b4dd4-52f4-47a6-bca9-ed12c81889e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expire Month'])[1]/following::select[2]</value>
      <webElementGuid>7c64b74a-cede-4f69-b7ac-8144b42cac18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CVC/CVV'])[1]/preceding::select[1]</value>
      <webElementGuid>9c500a8d-4784-4da4-a98d-d056586854a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BILLING ADDRESS'])[1]/preceding::select[1]</value>
      <webElementGuid>d2b83c5f-76a2-4e8f-92f3-f19c88abac2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/select</value>
      <webElementGuid>82fea764-710a-4a06-9ee0-bbafaa0ccedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AmericanExpressRequest_sourceOfFunds_provided_card_expiry_year' and @name = 'AmericanExpressRequest.sourceOfFunds.provided.card.expiry.year' and @placeholder = 'YY' and (text() = 'Year
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
' or . = 'Year
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
')]</value>
      <webElementGuid>a8b841de-6454-4c8f-a85d-7a7788cd320c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
