<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pets_textBox</name>
   <tag></tag>
   <elementGuidId>29a07893-838f-4428-ac15-7b1bb7b3d288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Legs_0__PetsDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__PetsDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2a8d7d10-ef23-47f5-8f9a-119b56248cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-textarea form-control target-pets-description</value>
      <webElementGuid>ce0b59cb-9e2a-4d43-b703-2a8b84b18a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>734d7efe-0976-40fe-890f-bfcddf3eb63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__PetsDescription</value>
      <webElementGuid>8b8c5a7b-103a-4e31-b053-8b4ae4c00eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].PetsDescription</value>
      <webElementGuid>a6ca72cf-1ec8-4738-a00d-ec717ec11ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>05ee59ca-e4f6-4917-97c3-7b7b82abc7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__PetsDescription&quot;)</value>
      <webElementGuid>09ce135e-86b6-4a8f-bf32-b10dde50ccb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Legs_0__PetsDescription']</value>
      <webElementGuid>c8de757a-0c1c-4c64-91c8-472d9ae84edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='baj-results-leg-luggage-div']/div/div[3]/div[5]/textarea</value>
      <webElementGuid>a463e6ac-5016-4147-9440-a575e495da40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/textarea</value>
      <webElementGuid>30174421-5fc7-446d-a225-0e99f9592212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Legs_0__PetsDescription' and @name = 'Legs[0].PetsDescription']</value>
      <webElementGuid>d766e3e7-27eb-4a02-8915-f7358b64477a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
