<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>showAll7Attachments_button</name>
   <tag></tag>
   <elementGuidId>258029c3-5040-4d65-a5cc-07c95dfa6471</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ms-Button-icon.ZO5ez.icon-419</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div/span/button/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>45ae337b-57ae-4356-8f15-656d40b58966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-name</name>
      <type>Main</type>
      <value>DoubleChevronDown</value>
      <webElementGuid>717a0157-bd62-4ee3-bc23-efec03f01311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ed7188e2-cc76-4de8-976c-844ecdbc2481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Button-icon ZO5ez icon-419</value>
      <webElementGuid>6e15ad19-a9a7-4927-8f3b-0ad9f3e07f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>b339065e-d4e1-47a9-90ac-b9629168367b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReadingPaneContainerId&quot;)/div[1]/div[@class=&quot;g_zET&quot;]/div[@class=&quot;MtujV&quot;]/div[@class=&quot;L72vd&quot;]/div[@class=&quot;Q8TCC yyYQP customScrollBar&quot;]/div[1]/div[@class=&quot;aVla3&quot;]/div[1]/div[1]/div[@class=&quot;wide-content-host&quot;]/div[@class=&quot;SlLx9 isFirstCard byzS1&quot;]/div[@class=&quot;l8Tnu T3idP&quot;]/div[@class=&quot;RrjjU disableTextSelection&quot;]/span[@class=&quot;h7gZn&quot;]/button[@class=&quot;ms-Button ms-Button--action ms-Button--command dwpQ_ I7a1P fj52V root-418&quot;]/span[@class=&quot;ms-Button-flexContainer flexContainer-406&quot;]/i[@class=&quot;ms-Button-icon ZO5ez icon-419&quot;]</value>
      <webElementGuid>1edcc60e-e96f-4299-a108-76ef67ca13bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div/span/button/span/i</value>
      <webElementGuid>5e631472-bf97-42da-bce6-59560a9acbe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Confirmation for NadyaCL Katalon.pdf'])[1]/following::i[2]</value>
      <webElementGuid>42c0c041-e2bb-4d37-a6ad-47d60a2916f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATT00005.bin'])[1]/following::i[6]</value>
      <webElementGuid>799d9ef7-00a8-47f7-9a51-41c418977a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show all 7 attachments (1 MB)'])[1]/preceding::i[1]</value>
      <webElementGuid>d07e045b-dd75-45b9-9762-26e06a69e05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save all to OneDrive - ONEflight International'])[1]/preceding::i[2]</value>
      <webElementGuid>56f4b005-b876-4852-b31f-6523cc15881f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>a54c07a6-7091-494f-aaa7-2735eb0b9fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/button/span/i</value>
      <webElementGuid>a83a1d1f-5fce-408c-93ce-da709559fddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = '' or . = '')]</value>
      <webElementGuid>41504b5b-8835-4688-957b-2885ac457e6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
