<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cheese_checkBox</name>
   <tag></tag>
   <elementGuidId>b0dd05a2-9114-402a-a0fa-91f9ee283a43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Pizza-options']/li[4]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2c27a12e-3ff9-4b25-b20b-09a01153772c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>PizzaCheese</value>
      <webElementGuid>3f49d53a-1ed9-45a1-8e54-b595554f1bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cheese</value>
      <webElementGuid>d64d3f49-cf8a-42d6-8567-c9d336c4e6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pizza-options&quot;)/li[4]/label[1]</value>
      <webElementGuid>2ebddc16-99e8-40fc-a60c-0f7ad4b69cf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Pizza-options']/li[4]/label</value>
      <webElementGuid>377048ad-264c-4a66-b235-3b796f4d8197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pepperoni'])[1]/following::label[1]</value>
      <webElementGuid>f8410bef-737b-4abd-8249-63718911f2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sausage'])[2]/following::label[2]</value>
      <webElementGuid>339884b2-7e5c-43bc-9ba1-800d6afaf14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[4]/preceding::label[1]</value>
      <webElementGuid>ec6e20b2-32d5-4460-bd0b-42131860883f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cheese']/parent::*</value>
      <webElementGuid>6be90bed-e461-487f-8c6f-e54a12bb25f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4[3]/ul/li[4]/label</value>
      <webElementGuid>d8f3b1f7-2f32-404b-89c1-c0361ced690e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Cheese' or . = 'Cheese')]</value>
      <webElementGuid>407ab29e-d0c2-458f-97cc-b6cb5499b630</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
