<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>customerPickupAddress1_textBox</name>
   <tag></tag>
   <elementGuidId>d75e533b-d84e-4235-b530-2be2f51fc64d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Address_Street1'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-2-leg-909637 > #new-executive-quote-noorder > #pickup-quote-0 > div.panel-body > div.row > div.col-sm-5 > div.row.auto-complete-address > div.col-xs-12 > #Address_Street1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa87678d-97ac-4269-a2b4-7cb532539be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ef7d3fc-1401-4d6c-ac94-0ed75b2f2e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control auto-complete-street-address ui-autocomplete-input</value>
      <webElementGuid>82b27732-9b4e-4441-ab35-0583e50e14c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_Street1</value>
      <webElementGuid>2bcbc69a-c466-46b5-ac31-234f7a9456b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0ff3a024-13d2-4f68-91df-0da8c9a0a237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address.Street1</value>
      <webElementGuid>6d353738-5c2b-4d7c-a56e-3cd496580205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>337e5a7d-e7d0-48ef-9f96-6cc3f83ecaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909637&quot;)/div[@id=&quot;new-executive-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-5&quot;]/div[@class=&quot;row auto-complete-address&quot;]/div[@class=&quot;col-xs-12&quot;]/input[@id=&quot;Address_Street1&quot;]</value>
      <webElementGuid>aa632188-ce19-48f3-ad73-0ae7aecb777d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Address_Street1'])[7]</value>
      <webElementGuid>a1efaac1-0bf8-460e-b7e1-5c36e2f8f68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='pickup-quote-0']/div/div/div[2]/div[2]/div/input)[9]</value>
      <webElementGuid>cfc2aec2-d428-46ef-af06-fd2b76b95d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[2]/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>b8898897-012e-4bd2-bfb8-50be26799579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Address_Street1' and @name = 'Address.Street1']</value>
      <webElementGuid>c35a3528-ca5e-4650-8e8c-16133edef616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
