<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>americanExpressPaymentAuthorization_checkBox</name>
   <tag></tag>
   <elementGuidId>f8900a3f-8f93-44d0-b072-780a3c73b88c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_UserAgreement_AmericanExpress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_UserAgreement_AmericanExpress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07433338-7ce8-4535-8724-790ce6e6d50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error</value>
      <webElementGuid>33e1109e-549e-47ff-b907-70faea01862c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a21c76e6-d8cd-4741-b696-d024ba6e67f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Must Agree to American Express Authorization</value>
      <webElementGuid>8f46c990-9332-4513-8501-4e773929b553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>2054d837-b2ad-459e-aa6b-2e9645e735c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>ffab0c87-38c4-4dcb-b70b-9242d183c471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The American Express Authorization field is required.</value>
      <webElementGuid>71bbdd41-34d4-44b8-a789-dacd73363d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_UserAgreement_AmericanExpress</value>
      <webElementGuid>b232b2e3-a945-4161-85fe-aae2776f9a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.UserAgreement_AmericanExpress</value>
      <webElementGuid>050c556a-299d-4f7e-958b-75ca8fd5a3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>19713d49-6e49-4067-b262-984a4df699f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0cec37f3-910a-4fc3-9b55-ecf3970b18c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_UserAgreement_AmericanExpress&quot;)</value>
      <webElementGuid>b7b089cc-1a52-4866-8960-926e5dbaa766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_UserAgreement_AmericanExpress']</value>
      <webElementGuid>ead5fad8-2f5e-4bd3-b258-7ae8287023b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PayForm']/div[2]/div/div/div/div[4]/div/ul/li[3]/input</value>
      <webElementGuid>f2b4c955-2811-436d-9546-6afa462351fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/input</value>
      <webElementGuid>df1777b8-720c-472e-a3c7-354b3f161130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FlightPlan_UserAgreement_AmericanExpress' and @name = 'FlightPlan.UserAgreement_AmericanExpress' and @type = 'checkbox']</value>
      <webElementGuid>ba870fe2-5768-45ab-8e1f-c426b09a15c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
