<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>securityCode_textBox</name>
   <tag></tag>
   <elementGuidId>98dbbb64-72cf-46f7-8a76-217dde2ba672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AmericanExpressRequest_sourceOfFunds_provided_card_securityCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AmericanExpressRequest_sourceOfFunds_provided_card_securityCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>baa6220b-2bdc-4936-bf8f-40854182d54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9a0b3984-ceae-4c72-bf97-c2840599fe03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc7fdf0f-65dd-4add-b6bc-37ab7674b06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Security Code field is required.</value>
      <webElementGuid>35be57da-c2fc-4fd8-9898-6a19355ae348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmericanExpressRequest_sourceOfFunds_provided_card_securityCode</value>
      <webElementGuid>b5cf4737-b17b-40a3-bb75-57e3c3338138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmericanExpressRequest.sourceOfFunds.provided.card.securityCode</value>
      <webElementGuid>2656ce8b-f7c8-4dc0-8610-8e5f37a4d12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>48830c41-3e0c-46d1-bc1e-f080af082332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c7f4181-f519-460a-8187-26e470044fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmericanExpressRequest_sourceOfFunds_provided_card_securityCode&quot;)</value>
      <webElementGuid>4f394530-fada-4b5a-8f33-362696afd79c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AmericanExpressRequest_sourceOfFunds_provided_card_securityCode']</value>
      <webElementGuid>042f34c6-024f-4727-a99b-8ebb02b6317e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-tabContent']/div[2]/div[5]/div/input</value>
      <webElementGuid>50263065-4290-4338-86c5-c1fa4f5e533c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/input</value>
      <webElementGuid>844b4132-9300-44f1-bcf3-43c3dac3c7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AmericanExpressRequest_sourceOfFunds_provided_card_securityCode' and @name = 'AmericanExpressRequest.sourceOfFunds.provided.card.securityCode' and @type = 'text']</value>
      <webElementGuid>6d79d864-c410-4ede-b580-ec0d19d65d0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
