<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>street_textBox</name>
   <tag></tag>
   <elementGuidId>1039ab38-ef47-40cd-90e9-60b5bf15dbe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AmericanExpressRequest_billing_address_street']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AmericanExpressRequest_billing_address_street</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32c03527-7f7b-4c67-9211-1b2c053cd992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d312e46c-8cd9-496f-ab36-5f90046a79d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6eca309d-420b-47ce-9418-de6d8e3b71f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Street field is required.</value>
      <webElementGuid>c8d6fb72-32c2-43fb-86bf-69252b51bdaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmericanExpressRequest_billing_address_street</value>
      <webElementGuid>6e37f278-132b-44f6-8da1-72b32f74d1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmericanExpressRequest.billing.address.street</value>
      <webElementGuid>fac2d5c2-d523-4bef-b1d6-fac73ceabe34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dae5655d-91bb-492e-be81-14363698ebe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmericanExpressRequest_billing_address_street&quot;)</value>
      <webElementGuid>035a9110-8e2e-4868-9265-321555068905</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AmericanExpressRequest_billing_address_street']</value>
      <webElementGuid>cb8836d1-0153-4598-9512-878546788d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-tabContent']/div[4]/div/div/input</value>
      <webElementGuid>7f206ee5-dd01-4865-a071-1fa7c1d0349f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[4]/div/div/input</value>
      <webElementGuid>76f24aa1-289f-4484-b257-d2c2a421d59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AmericanExpressRequest_billing_address_street' and @name = 'AmericanExpressRequest.billing.address.street' and @type = 'text']</value>
      <webElementGuid>29ad39c1-e146-4f13-a9e4-b6802f38077e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
