<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>street2_textBox</name>
   <tag></tag>
   <elementGuidId>5fde09bc-42ff-460b-b311-1b010f9fcb7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AmericanExpressRequest_billing_address_street2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AmericanExpressRequest_billing_address_street2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8585e479-d951-4fd6-a13f-55d5390dbef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9d2b3562-208c-4345-b59d-a6218cd974e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmericanExpressRequest_billing_address_street2</value>
      <webElementGuid>907df6e1-133f-4105-befa-17d4929ca837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmericanExpressRequest.billing.address.street2</value>
      <webElementGuid>c7b8386e-9807-42dc-ad7d-818e365b2b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8647165b-2838-471e-adcd-4af5c00e2ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmericanExpressRequest_billing_address_street2&quot;)</value>
      <webElementGuid>31b4071b-9029-4de9-9ab7-3ac260c5fd7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AmericanExpressRequest_billing_address_street2']</value>
      <webElementGuid>9c520766-aae5-40ef-9714-04d453060319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-tabContent']/div[4]/div[2]/div/input</value>
      <webElementGuid>6025550e-23ff-405e-89f0-1e913b7e72e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[4]/div[2]/div/input</value>
      <webElementGuid>1cb3ac33-af1c-4065-8a88-778386ee9e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AmericanExpressRequest_billing_address_street2' and @name = 'AmericanExpressRequest.billing.address.street2' and @type = 'text']</value>
      <webElementGuid>a84091ee-ffac-45e0-aa12-9f4313393d5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
