<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>luggage_textBox</name>
   <tag></tag>
   <elementGuidId>851e76b9-879f-4b64-9e09-300b416b923d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='LuggageDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LuggageDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cf262974-616a-4bd2-bb7c-2ff255d78da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea-small</value>
      <webElementGuid>b43d1ae1-0963-47d8-b31b-261144106e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LuggageDescription</value>
      <webElementGuid>2da948e0-175d-41fe-936f-c35d67f6f2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909635&quot;)/div[@id=&quot;new-executive-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/textarea[@id=&quot;LuggageDescription&quot;]</value>
      <webElementGuid>41281d41-05db-4b42-b290-1ecdfd8f27a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='LuggageDescription']</value>
      <webElementGuid>8df6eb5f-7b80-48db-bcaf-a9547d3b5797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pickup-quote-0']/div/div/div[2]/div[7]/div/textarea[2]</value>
      <webElementGuid>ddc93d00-15af-4f19-98fc-bc3bfe1eada8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/textarea[2]</value>
      <webElementGuid>a82dd464-0ac5-4818-9e6d-c9def6289778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'LuggageDescription']</value>
      <webElementGuid>8c585870-789a-4aef-a1da-d06191c5a914</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
