<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saveRequest_button</name>
   <tag></tag>
   <elementGuidId>3a108868-4cad-48b3-b909-d6d42ac7ba90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Save Request'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#new-executive-quote-noorder > #pickup-quote-0 > div.panel-body > div.row > div.col-xs-12.top-margin-15 > div > input.btn.btn-primary.btn-flight-plan.target-save-vendor-quote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db680339-c2a4-416a-8fe7-96bcd665843f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9aea121b-1f11-4502-9d03-0103ff2d133d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save Request</value>
      <webElementGuid>23928b34-77c2-42b0-a24b-96f6b451c345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-flight-plan target-save-vendor-quote</value>
      <webElementGuid>f78a7aa9-4bfe-47ea-b6fb-3d01a35efaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-verbalquote</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2af15f37-9938-47fe-9e4a-27d7bfda11cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909834</value>
      <webElementGuid>5546d599-4455-4efe-ad32-be181701c57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quotetypeid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4c537e87-2df6-44ad-898a-0edaeebda86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-transportationtype</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>48da424f-d606-4c2b-ba34-5cec96d50541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quoteid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b7bc7291-73f5-4e55-ae20-678ec3cbbe0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-send</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>89a938af-ce47-4eca-bbde-2bff8852d027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909834&quot;)/div[@id=&quot;new-executive-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12  top-margin-15&quot;]/div[1]/input[@class=&quot;btn btn-primary btn-flight-plan target-save-vendor-quote&quot;]</value>
      <webElementGuid>3d7838a9-805f-4416-a794-067f665fa101</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Save Request'])[4]</value>
      <webElementGuid>ba66f876-648c-423b-bd29-9a02828e2056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='pickup-quote-0']/div/div/div[4]/div/input)[2]</value>
      <webElementGuid>09072ca2-2865-46e5-b464-d33541ea0fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>d93c4022-e53c-446d-81a3-c5126d329077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>761654e6-5f77-4644-9210-45f3b4d4d2ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
