<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>birthDate_dropDown</name>
   <tag></tag>
   <elementGuidId>cf5c1f3d-6179-40c2-877a-5b4773a21def</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Legs_0__Passengers_2__BirthDate_Month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_2__BirthDate_Month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6b44c42b-6219-4688-853a-a5bd0611df4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control float-left target-birthdate-el target-pax-birthmonth</value>
      <webElementGuid>547241b0-3591-462c-a9d6-ffc721f682a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8b2cff1b-a756-4748-bbc9-80e02eabaeea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The BirthDate_Month field is required.</value>
      <webElementGuid>0b9f5efb-b646-43b9-91ee-e3c9230827b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_2__BirthDate_Month</value>
      <webElementGuid>1cb0b914-f3ec-461d-9fd1-1409002a2a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[2].BirthDate_Month</value>
      <webElementGuid>1d321329-f4de-427e-9643-9eebb51af743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Month
                                        Jan
                                        Feb
                                        Mar
                                        Apr
                                        May
                                        Jun
                                        Jul
                                        Aug
                                        Sep
                                        Oct
                                        Nov
                                        Dec
                            </value>
      <webElementGuid>78d541a4-81bd-4a9f-ae5e-b81a8cc9f373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_2__BirthDate_Month&quot;)</value>
      <webElementGuid>59492fd3-edf5-4c56-93a2-c0dbca9ec265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Legs_0__Passengers_2__BirthDate_Month']</value>
      <webElementGuid>447a6a75-482d-4be5-b7e3-4880de22c5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-3']/div[3]/div[2]/div/div[2]/div/div/div[2]/select</value>
      <webElementGuid>ff8bffb2-54c0-48bb-8c32-6f1916fdcd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birth Date'])[3]/following::select[1]</value>
      <webElementGuid>5a4104a2-66f4-4234-bcd0-8b56c74b5cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[6]/preceding::select[2]</value>
      <webElementGuid>36e725e8-a2f7-47fd-893a-50f0ae8dca95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/div/div[2]/div/div/div[2]/select</value>
      <webElementGuid>f8252962-0960-49eb-ba52-31115d1b67ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Legs_0__Passengers_2__BirthDate_Month' and @name = 'Legs[0].Passengers[2].BirthDate_Month' and (text() = '
                                Month
                                        Jan
                                        Feb
                                        Mar
                                        Apr
                                        May
                                        Jun
                                        Jul
                                        Aug
                                        Sep
                                        Oct
                                        Nov
                                        Dec
                            ' or . = '
                                Month
                                        Jan
                                        Feb
                                        Mar
                                        Apr
                                        May
                                        Jun
                                        Jul
                                        Aug
                                        Sep
                                        Oct
                                        Nov
                                        Dec
                            ')]</value>
      <webElementGuid>40eea0d4-735c-463d-b6b1-d86f4269e363</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
