<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>savePassenger_button</name>
   <tag></tag>
   <elementGuidId>29f35c1d-3e3f-41a4-b347-4db758587453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Save Passenger'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.baj-btn.target-baj-results-button-save-passenger.l1p3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d65d759-ec59-47a8-a2f5-8c090a9c7fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn target-baj-results-button-save-passenger l1p3</value>
      <webElementGuid>102d0f26-f67c-4a86-a45b-38052e92ba13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-number</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d8592c82-19a1-4f55-8fc9-4d3962f65a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8d061f9c-41ae-45b6-be62-dfaf1b27049d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-id</name>
      <type>Main</type>
      <value>1861065</value>
      <webElementGuid>aab13f8c-f18c-4164-8add-31b5da3a1cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-class</name>
      <type>Main</type>
      <value>l1p3</value>
      <webElementGuid>86435429-ae8f-426c-86e6-c12d7d5be747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-number-of-legs</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>60900ea0-bf77-42fc-9ca7-76659f73bc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f82728c-c4e7-46d2-991f-528c05ff0f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save Passenger</value>
      <webElementGuid>ef6b499a-90e3-4089-b694-58cf3e94ee34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passengercontainer-leg-1-number-3&quot;)/div[@class=&quot;clearfix baj-results-pax-grid-box&quot;]/div[@class=&quot;save-passenger-container   no-margin&quot;]/div[@class=&quot;row clearfix&quot;]/div[@class=&quot;col-xs-12 text-center&quot;]/input[@class=&quot;baj-btn target-baj-results-button-save-passenger l1p3&quot;]</value>
      <webElementGuid>41271c40-5923-4134-aa6c-53f6db0c4b4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Save Passenger'])[3]</value>
      <webElementGuid>2e19c33c-57b2-43b9-9710-a2587b800a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-3']/div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>e9920c52-d039-475a-b97f-0baeaec33c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>3530a6cf-0506-4353-a850-b0fd4ea9aab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>4941434d-3536-4490-a088-c74b5b52da2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
