<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>smsPhone_textBox</name>
   <tag></tag>
   <elementGuidId>d2ff89de-0a34-457b-91ab-1645090ffd07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__Passengers_2__NotificationSMS']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_2__NotificationSMS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6be7ffd7-3241-4c43-a6f5-e68f1949c7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>ab1a5971-768e-474e-8712-77443fd946a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control phoneNumber</value>
      <webElementGuid>8b931c53-3ed2-402a-a38d-fb57df2dc659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>afcf848d-ccdb-495d-adeb-e38498949ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_2__NotificationSMS</value>
      <webElementGuid>70fe3f05-1568-4af6-87ce-6115047d7f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[2].NotificationSMS</value>
      <webElementGuid>a6805bb8-c8a0-48d8-b79e-7af83ea641be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_2__NotificationSMS&quot;)</value>
      <webElementGuid>a47a6069-a856-461b-92ec-cdb60d84ffcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__Passengers_2__NotificationSMS']</value>
      <webElementGuid>9ea8df97-255d-4841-8ef7-fa46892ab017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-3']/div[3]/div[2]/div/div[4]/div[2]/div/input</value>
      <webElementGuid>80ce4cb7-209a-4fff-a4db-3889e3b497b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/div/div[4]/div[2]/div/input</value>
      <webElementGuid>8db7d931-1936-45e3-b954-98ae1a0dad86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Legs_0__Passengers_2__NotificationSMS' and @name = 'Legs[0].Passengers[2].NotificationSMS']</value>
      <webElementGuid>1ad5502a-9d8f-43c4-a9f6-4316ea6182ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
