<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firstName_textBox</name>
   <tag></tag>
   <elementGuidId>974665e4-117a-4f73-b4dd-b58576cdf3c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AmsFilterViewModel_FilterClientFirstName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AmsFilterViewModel_FilterClientFirstName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18a76987-cf88-4218-9b1b-6405be371f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control target-filter-element</value>
      <webElementGuid>b1d6c45e-1305-465a-8f1f-515e658ad0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmsFilterViewModel_FilterClientFirstName</value>
      <webElementGuid>7b851903-963a-4eb1-bc05-dc3c4cb2b920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmsFilterViewModel.FilterClientFirstName</value>
      <webElementGuid>82d29797-b408-45ee-9d58-3749ea41048c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49a971dc-fc3b-4e08-8675-bad6677fff61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmsFilterViewModel_FilterClientFirstName&quot;)</value>
      <webElementGuid>20122e48-cec6-480b-ac9a-18931d4bfaea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AmsFilterViewModel_FilterClientFirstName']</value>
      <webElementGuid>208ed958-fd17-421f-a263-a71811bbc4b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>416317b7-a462-4388-8481-f7481736b1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>06241b67-d52a-4909-a457-55e63edca4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AmsFilterViewModel_FilterClientFirstName' and @name = 'AmsFilterViewModel.FilterClientFirstName' and @type = 'text']</value>
      <webElementGuid>c972f6f6-6aed-46d9-819d-1112845a6bd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
