<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchHomePage_field</name>
   <tag></tag>
   <elementGuidId>c9133d30-1250-4a7f-975a-102a22ddda2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SearchBy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SearchBy&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23299f3b-985c-4669-b884-8dcfbaef3940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-label black-tight-input</value>
      <webElementGuid>268b599c-db97-471f-8dee-32427bdbcb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchBy</value>
      <webElementGuid>bbce3896-51e6-4833-b363-bb793c10dcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client-search-form&quot;)/input[@class=&quot;form-control black-label black-tight-input&quot;]</value>
      <webElementGuid>97399636-3c53-432e-8601-2d5fbd9c78b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SearchBy']</value>
      <webElementGuid>641897b0-b4eb-4b2e-bc4f-2822da0ed707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='client-search-form']/input</value>
      <webElementGuid>65171163-a14a-4f59-b42d-05a226585771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/form/input</value>
      <webElementGuid>d8de3810-26e5-4d8c-989f-286646ed2ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'SearchBy']</value>
      <webElementGuid>9308ed94-f790-4d2b-a356-28ab851eedcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
