<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addFStop_icon</name>
   <tag></tag>
   <elementGuidId>8753cebd-9022-4ef9-becd-46f2fe7e3230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#target-leg_909767-fuel-stops-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[5]/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b7b744e3-fee8-40e7-a475-a668d9ddcd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus-circle target-expand-leg-fuel-stops cursor</value>
      <webElementGuid>7236ef31-11f7-40ac-bdd5-2630562a9a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-id</name>
      <type>Main</type>
      <value>909767</value>
      <webElementGuid>38c43234-2307-447f-9bf0-a414a7ab1192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>target-leg_909767-fuel-stops-info</value>
      <webElementGuid>40577dae-911b-4943-80c6-5fcc2eda3f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-leg_909767-fuel-stops-info&quot;)</value>
      <webElementGuid>19fbcbec-e801-4254-8264-a43bfc4c569f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='target-leg_909767-fuel-stops-info']</value>
      <webElementGuid>0de1549d-b39a-4fdd-9ab5-7a0cd3b24b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909767']/div[5]/span/i</value>
      <webElementGuid>fb40dab8-e095-4af3-9ce8-91f382cc2f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/span/i</value>
      <webElementGuid>30cf51d9-58a1-4a6d-a748-e969795f156c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'target-leg_909767-fuel-stops-info']</value>
      <webElementGuid>acb78d8c-d86d-410c-9367-dab34f2fd82f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
