<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>time_textBox</name>
   <tag></tag>
   <elementGuidId>32993655-82ef-4bec-b073-a895e768b457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__OriginHour</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_1__OriginHour']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>961291cc-ba48-44bf-9128-7541a6d9cd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-time-picker black-tighter-input target-flight-plan-input-origin-time form-control</value>
      <webElementGuid>086d51fc-c111-4d47-a109-74d48f73efbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>15dde8b8-5642-44ec-9917-f6af4ac31be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Time field is required.</value>
      <webElementGuid>6f54efeb-5027-4503-94f7-03b37ca22be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__OriginHour</value>
      <webElementGuid>6b36711f-cf5b-4aed-8726-20e6cc17593e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].OriginHour</value>
      <webElementGuid>6190a99f-55b8-4165-94eb-b463fdabaebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78d2dd9e-65e2-4f1d-a6e9-31723779f6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>09:00</value>
      <webElementGuid>7702b7cb-29e0-45fc-a911-7da37e77977d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__OriginHour&quot;)</value>
      <webElementGuid>40ad3231-3e14-4fa3-bbc6-da1f8252c28b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_1__OriginHour']</value>
      <webElementGuid>2c08ca99-d998-4298-89d2-f5f318bc53ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909767']/div[7]/input</value>
      <webElementGuid>4a0831ef-74dd-476d-abea-aea80b7f6be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[7]/input</value>
      <webElementGuid>788e2153-3a8c-44a7-a02c-e515f3673161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_1__OriginHour' and @name = 'Legs[1].OriginHour' and @type = 'text']</value>
      <webElementGuid>dc770870-cf07-4fd5-9664-f54289824b95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
