<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>to_textBox</name>
   <tag></tag>
   <elementGuidId>6ac6fcae-3076-458f-a24c-0c949f780466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__AirportDestinationIdent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_1__AirportDestinationIdent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04fdf43d-b597-4290-a92c-ce8925302917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-airport-entry black-tighter-input form-control ui-autocomplete-input</value>
      <webElementGuid>1cc42c9c-c970-48a5-8fb5-044e00d1fcee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__AirportDestinationIdent</value>
      <webElementGuid>6bd745b7-26d2-43f0-b865-7ad472beeeba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].AirportDestinationIdent</value>
      <webElementGuid>cc474e40-6e19-4ccf-a363-05d97af6cee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eadc68b0-b6da-43ac-a84a-97f2f1f5cb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>KDEN</value>
      <webElementGuid>75645461-c6d6-47eb-b6ac-8f91f62d85ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e895c4ea-4a0d-4bde-b181-908a853d090b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__AirportDestinationIdent&quot;)</value>
      <webElementGuid>f8836df3-ec48-4d09-9dbd-ee221143391e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_1__AirportDestinationIdent']</value>
      <webElementGuid>70951af3-04ec-47ef-b2cd-1fcf3469f993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909767']/div[4]/input</value>
      <webElementGuid>895daff9-b9cf-4217-b3b1-3f3a2be02dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div[2]/div[4]/input</value>
      <webElementGuid>0434687b-5ebc-4b5c-9ecf-e2a757385126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_1__AirportDestinationIdent' and @name = 'Legs[1].AirportDestinationIdent' and @type = 'text']</value>
      <webElementGuid>89e72c61-6ca1-4e67-8935-52e4c1fdcce9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
