<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>noteForVendor_textBox</name>
   <tag></tag>
   <elementGuidId>2400023b-25ba-4f10-ac55-4ed770647d4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-1-leg-909596 > #catering-quote-0 > div.panel-body > div.row > div.col-xs-12.col-sm-5 > div.target-vendor-note > div.row > div.col-xs-12 > #VendorNote</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='VendorNote'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>81fcada7-779a-43aa-ba52-343ec395500e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea-small</value>
      <webElementGuid>48d3ec53-566c-4f06-85f7-a4cb6098e5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VendorNote</value>
      <webElementGuid>cba86706-31fc-4493-a62b-2d2b649c954e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VendorNote</value>
      <webElementGuid>e14ee2b2-a4dd-4424-83da-da1cbf92b6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-1-leg-909596&quot;)/div[@id=&quot;catering-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-5&quot;]/div[@class=&quot;target-vendor-note&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/textarea[@id=&quot;VendorNote&quot;]</value>
      <webElementGuid>5dd1181d-e3d1-47eb-a80c-b84c2e03b143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='VendorNote'])[5]</value>
      <webElementGuid>feaa5a3f-52ac-414e-9a06-05864443b24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='catering-quote-0']/div/div/div[2]/div[3]/div[2]/div/textarea)[2]</value>
      <webElementGuid>a422d59b-bed3-48fa-9b95-2fd7b6c7fef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div[2]/div[2]/div[3]/div[3]/div/div/div[2]/div[3]/div[2]/div/textarea</value>
      <webElementGuid>cdf69ecc-7553-4a79-93d3-21c14967d419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'VendorNote' and @name = 'VendorNote']</value>
      <webElementGuid>a3331856-ab6e-459c-9e94-b84c1426b035</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
