<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>state_textBox</name>
   <tag></tag>
   <elementGuidId>e81a3518-cfda-4711-ab12-ad45ee78616f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_State_StateCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_State_StateCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adc0015f-7c95-435b-a1af-1791f8ad3cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0688e6cf-2a85-4d3e-a6cb-5e0be7abce28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>caf622a0-9865-464c-b440-97ba77df8093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-street-address dropoff-address ui-autocomplete-input</value>
      <webElementGuid>dc90cfe7-96fb-4f54-a5db-32e6983506b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08793a0f-861d-478b-b45e-f9144fde4873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a9b8c7b1-9abe-412c-93de-d6bf05ec4498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field State must be a string or array type with a maximum length of '2'.</value>
      <webElementGuid>20fd0d01-21cb-4275-8e38-f3138cb525cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>91edfcba-9135-48ba-aefb-88a62194d635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The State field is required.</value>
      <webElementGuid>dcda962d-6103-44f9-9d97-eb3bed10f7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_State_StateCode</value>
      <webElementGuid>505a9ad8-76f3-4e63-b9f1-8d40c084ae50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>bc5e8795-c764-4fd1-8d44-42a24d168773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[1].ActiveConciergeOrder.ExecutiveDropoffFullAddress.State.StateCode</value>
      <webElementGuid>ee692aeb-1162-44cd-8669-d95e96c562bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_State_StateCode&quot;)</value>
      <webElementGuid>ce1256a4-3838-4992-9402-7553c2b2a953</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_State_StateCode']</value>
      <webElementGuid>ad256b34-9810-4690-9b58-3a55ebc83cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-1-dropoffform']/div/div/div[4]/input</value>
      <webElementGuid>8de44776-2444-454b-84b1-ed69bfce23cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div/div/div/div[4]/input</value>
      <webElementGuid>eda61682-0cad-4c3a-a0a4-ab27f418b033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_State_StateCode' and @name = 'FlightPlan.Legs[1].ActiveConciergeOrder.ExecutiveDropoffFullAddress.State.StateCode']</value>
      <webElementGuid>f0fd65c2-34ff-4961-8c67-d9f42f3d9937</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
