<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firearms_textArea</name>
   <tag></tag>
   <elementGuidId>ce3ad81e-3576-41da-a22d-79f65ffa9260</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__FirearmsDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Legs_0__FirearmsDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2d65062e-ff58-4012-ba27-1c6bc7f08673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-textarea form-control target-firearms-description</value>
      <webElementGuid>cb120bc3-b9fa-4f1a-ab17-117addd7b50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>7c6fcb3e-e103-4141-934f-0ab0d9e329f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__FirearmsDescription</value>
      <webElementGuid>614d260a-c9b8-4caf-bb6f-e2bf69578243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].FirearmsDescription</value>
      <webElementGuid>e4119b82-0dfb-4f18-ba44-245d76894245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f7fd1e7b-2384-4c63-9275-e9d5e4acdc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__FirearmsDescription&quot;)</value>
      <webElementGuid>cb6073e8-cc94-40f5-9b32-06ec1273c3b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Legs_0__FirearmsDescription']</value>
      <webElementGuid>74b4fc2c-d089-4844-93aa-7543df21b066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='baj-results-leg-luggage-div']/div/div[2]/div[5]/textarea</value>
      <webElementGuid>69217409-99b7-489e-bfd0-3034be57bd69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/textarea</value>
      <webElementGuid>18940729-51a3-4317-8560-b746f9c3fcf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Legs_0__FirearmsDescription' and @name = 'Legs[0].FirearmsDescription']</value>
      <webElementGuid>d8d632bc-7836-4393-815c-29fa88d8b02b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
