<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firearms_checkBox</name>
   <tag></tag>
   <elementGuidId>06fc3c4e-b95e-46f2-8a7b-015b83058e91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__FirearmsDescriptionNone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__FirearmsDescriptionNone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4aab047c-4cf0-487d-9ab2-e31b3f3fafc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom form-check-input target-firearms-nonecheckbox</value>
      <webElementGuid>301a8aeb-c47d-4f51-a316-8395aa069a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ab8da214-6f8d-44db-81da-9552930bd719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The FirearmsDescriptionNone field is required.</value>
      <webElementGuid>2710d827-c26e-4441-9844-b8b0de95c60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__FirearmsDescriptionNone</value>
      <webElementGuid>e1d6b1f0-0bc1-438b-acfd-61617df35149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].FirearmsDescriptionNone</value>
      <webElementGuid>2925165b-ee34-4573-887a-0ef8e5ec8bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>74d1cc01-6ca5-4b9e-9d71-4af1bc425dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>796f05fd-a4ea-4524-8726-9ebc44ce5c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__FirearmsDescriptionNone&quot;)</value>
      <webElementGuid>0de16540-1e45-4377-a3f4-5ae1e76e525e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__FirearmsDescriptionNone']</value>
      <webElementGuid>3f3174c7-ed63-451c-b3f7-4aed7ef6bdcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='baj-results-leg-luggage-div']/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>2999032f-5315-4bcd-a43f-a627cdb67cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>3678f9c9-b777-4241-b3b0-07f2ed811eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_0__FirearmsDescriptionNone' and @name = 'Legs[0].FirearmsDescriptionNone' and @type = 'checkbox']</value>
      <webElementGuid>50cc56fe-e375-47aa-911b-7a4064936ccb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
