<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>luggage_checkBox</name>
   <tag></tag>
   <elementGuidId>3686d918-6ea4-4544-aec6-431a643c5981</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__LuggageDescriptionNone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__LuggageDescriptionNone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>452a6270-4bee-4366-99d8-b0f8e5b0833a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom form-check-input target-luggage-nonecheckbox</value>
      <webElementGuid>7dfdc2be-a70d-433f-905c-5413ccaaa63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ba4a8701-f7f6-40a0-8ee2-5e052c6cac1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The LuggageDescriptionNone field is required.</value>
      <webElementGuid>6b66d5e5-b34f-4457-bd73-d3d43a333dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__LuggageDescriptionNone</value>
      <webElementGuid>5aa5e676-8761-4463-8235-d29bed41ad0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].LuggageDescriptionNone</value>
      <webElementGuid>37a19421-ee84-4e18-9353-2bcdbe25d78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c593b4ca-fc00-4c5e-9a8b-935e73d37532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>759414f4-59c7-43cb-82cb-83ae260b8119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__LuggageDescriptionNone&quot;)</value>
      <webElementGuid>dbc9b366-c388-4e48-bcb5-9143b81802b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__LuggageDescriptionNone']</value>
      <webElementGuid>bb767510-2013-4e40-98fa-472bbdc9702c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='baj-results-leg-luggage-div']/div/div/div[3]/div/div/input</value>
      <webElementGuid>e5cac67d-10aa-4a45-97f1-c25a2745268a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>1081ae22-fab5-4b46-aff0-0dd19172cd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_0__LuggageDescriptionNone' and @name = 'Legs[0].LuggageDescriptionNone' and @type = 'checkbox']</value>
      <webElementGuid>82d04332-5fee-4d37-93a5-6fd661b966d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
