<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>done_button</name>
   <tag></tag>
   <elementGuidId>d4fd6e17-e3e4-4dff-9fbb-56eacf5cf974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='GardenSalad-optionsclose']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GardenSalad-optionsclose</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>28e917ea-71d6-4f6a-8342-e5eaeb02c774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>finished-catering-selectons-button</value>
      <webElementGuid>41889eec-5301-47d1-81e2-79c8650d7525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909215</value>
      <webElementGuid>e104dd42-fafb-440f-8c12-61c1d71539fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GardenSalad-optionsclose</value>
      <webElementGuid>0fab0fb8-b18d-4adf-a710-ec4d7cce450f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemid</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>b80e799a-74ad-4b6b-bba1-ee27770591d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Garden Salad</value>
      <webElementGuid>c6084ee5-4298-4a10-a6a3-e037f5ab9732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>f12b12ee-a0b9-4efe-b328-5c1a980cb503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        Done
                                                                    </value>
      <webElementGuid>bbad97d7-4fef-4ff7-a244-8ea33ac80764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GardenSalad-optionsclose&quot;)</value>
      <webElementGuid>ef27249f-970a-4499-b9e5-b297e66122ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='GardenSalad-optionsclose']</value>
      <webElementGuid>18f42185-9499-40c6-8404-16412a0cc12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='GardenSalad-options']/li[6]/button</value>
      <webElementGuid>a351f0b7-f0cf-473e-847e-7d7b442adac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vinaigrette Dressing'])[2]/following::button[1]</value>
      <webElementGuid>e75e7e75-83b5-4d0b-bad6-67d10fb7df9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blue Cheese Dressing'])[2]/following::button[1]</value>
      <webElementGuid>f80d1cee-8d4f-4f37-b29a-8579b3282f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lunch'])[1]/preceding::button[1]</value>
      <webElementGuid>ef55788d-359b-4a2f-a0f5-39364cb89e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/button</value>
      <webElementGuid>32a31249-4549-4de0-a2f6-2734fa0de849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'GardenSalad-optionsclose' and (text() = '
                                                                        Done
                                                                    ' or . = '
                                                                        Done
                                                                    ')]</value>
      <webElementGuid>9268221c-4230-482e-9b6a-a44abd23dba1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
