<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>budgetOverageReason_textBox</name>
   <tag></tag>
   <elementGuidId>3d026633-ff9a-49de-af5c-e24b167f95a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OverageReason</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='OverageReason']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2467c2a1-0ab4-4050-8214-75c415e1190f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OverageReason</value>
      <webElementGuid>f54caa52-005f-432b-b5b0-81b829ebf1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OverageReason</value>
      <webElementGuid>74374b63-a9f4-4a1f-8c1c-242acb826159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-1-leg-909595&quot;)/div[@id=&quot;catering-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;target-enter-quoted-amount&quot;]/div[@class=&quot;col-xs-12 target-div-overage-reason&quot;]/div[@class=&quot;target-quoted-amount-div&quot;]/textarea[@id=&quot;OverageReason&quot;]</value>
      <webElementGuid>6306caca-1f70-4b64-8fef-ae67fdbd0fa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='OverageReason']</value>
      <webElementGuid>8545ccae-5b48-486f-83fd-a542a534f050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='catering-quote-0']/div/div/div[3]/div[3]/div[3]/div/div/textarea</value>
      <webElementGuid>09abf3c3-914c-4100-accb-519de5459e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/textarea</value>
      <webElementGuid>9a195bf4-dc09-4baa-a4a2-cbe95bca92da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'OverageReason' and @name = 'OverageReason']</value>
      <webElementGuid>659ac296-65ed-40b7-a2c7-19b0bf8795c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
