<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>noteForVendor_textBox</name>
   <tag></tag>
   <elementGuidId>d71083bb-3f88-4bc0-881e-bfacb9139564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VendorNote</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='VendorNote']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>90756d0d-e9e1-49fa-b63f-4f4420672a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea-small</value>
      <webElementGuid>bdbfe2e7-4246-4109-b791-5be8ae13478f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VendorNote</value>
      <webElementGuid>b0def19c-d0ac-4b31-bcb6-0f517ac92a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VendorNote</value>
      <webElementGuid>379072bf-dc16-4f17-b7d0-f0565a31e8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-1-leg-909595&quot;)/div[@id=&quot;catering-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-5&quot;]/div[@class=&quot;target-vendor-note&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/textarea[@id=&quot;VendorNote&quot;]</value>
      <webElementGuid>81d1d73e-c151-4be8-97c9-bdf985730867</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='VendorNote']</value>
      <webElementGuid>6c00f5c2-3d0b-4921-a605-4f878ab74a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='catering-quote-0']/div/div/div[2]/div[3]/div[2]/div/textarea</value>
      <webElementGuid>02e0ff04-1ae0-48f2-ae37-45d04b134bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/textarea</value>
      <webElementGuid>e5a60974-f90f-46f1-b75b-58a47a5e534f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'VendorNote' and @name = 'VendorNote']</value>
      <webElementGuid>06f3b356-2152-4f83-adea-e674c545cc76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
