<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gardenSaladRequest_button</name>
   <tag></tag>
   <elementGuidId>51968987-2fc6-41ae-a867-983b97f25a71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='GardenSalad']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GardenSalad > button.catering-select-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a7396689-7c3d-4550-bcab-6f0a7e70ba96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>catering-select-button</value>
      <webElementGuid>3e98f571-9fda-48bb-8167-e88f6dc02664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Garden Salad</value>
      <webElementGuid>223c4048-eff4-474e-b185-56c7f91ef3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909215</value>
      <webElementGuid>83f3767e-f002-4bff-9a98-893438c09fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemid</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>c1859556-c903-48c6-be5e-7ea5f55d04b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>173c8b00-3f17-4c96-96f8-8f3c35b8ee62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request for Leg 1</value>
      <webElementGuid>4948ce50-b406-49d7-876d-27409b706e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GardenSalad&quot;)/button[@class=&quot;catering-select-button&quot;]</value>
      <webElementGuid>cd23f9e5-1ce4-48f9-8d4f-a0016179f7f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h4[@id='GardenSalad']/button</value>
      <webElementGuid>f61a6092-8976-48a5-92c0-4248e48e7e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request for Leg 1'])[8]/following::button[1]</value>
      <webElementGuid>a9320f21-0d7e-4a7c-a143-8ad2c82f55e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[15]/preceding::button[1]</value>
      <webElementGuid>9267ed82-edd5-4d7f-89ef-1aa92c18757f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ranch Dressing'])[2]/preceding::button[1]</value>
      <webElementGuid>c39f091e-b13b-4e42-8b03-87f3d934ce7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/h4[4]/button</value>
      <webElementGuid>6b3070ee-aaf4-4f5c-8160-a86b1f2dd2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Request for Leg 1' or . = 'Request for Leg 1')]</value>
      <webElementGuid>c83ab068-ca38-4a25-9303-9e6bbcb41d6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
