<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>savingGuestNo_button</name>
   <tag></tag>
   <elementGuidId>5f90b33d-6196-4341-9061-60c2bb256914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='No'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#propagatepassengermodal-leg-1-passenger-2 > div.modal-dialog > div.modal-content > div.modal-body > div.row > div.col-xs-4 > #No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fef8b34c-201a-4eb5-a73c-0f90caba6a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn-small</value>
      <webElementGuid>daf58251-1f7a-4c25-9a22-bb48704f5c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf632e5e-0bf0-484f-9e2c-356e2454f553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>3507406d-f9ac-4479-b235-18f036e6201b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>e27a8363-b509-435f-acdb-77d8c2fa2519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propagatepassengermodal-leg-1-passenger-2&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4&quot;]/input[@id=&quot;No&quot;]</value>
      <webElementGuid>6b99a81e-3dc2-4ed8-91e2-c56330fb5666</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='No'])[2]</value>
      <webElementGuid>974f598b-430c-4253-88c1-5fc47570e004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='propagatepassengermodal-leg-1-passenger-2']/div/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>0788b7e7-c718-44b1-9b44-2ba3e4230cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div[4]/div/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>110b0b48-ae6d-4242-aaa4-01c3642bbc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'No']</value>
      <webElementGuid>7d8a0add-1ed8-4057-b846-5508f0d72548</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
