<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lunch_tab</name>
   <tag></tag>
   <elementGuidId>87490257-f9bf-4f31-affc-974a851ac4ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CateringMenuAccordion']/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0ce4ae7-c514-4a13-8e7e-5ae007ffecdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-heading accordion-toggle collapsed</value>
      <webElementGuid>31a0fb6c-ec92-4f06-b2cb-3f27fe3401f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0cf21816-f3d0-4310-adb5-0a49537c8538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Lunch</value>
      <webElementGuid>6c587fe5-305f-49de-9066-571071bd4000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>2e7d2296-cbfe-4b20-be52-c3caeb3ff66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#CateringMenuAccordion</value>
      <webElementGuid>c1ee191e-5bc5-43e9-bdfc-7be1d2d06fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Lunch
                                        </value>
      <webElementGuid>21dce238-26f4-4669-896b-ce114951a6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CateringMenuAccordion&quot;)/div[@class=&quot;panel panel-default&quot;]/a[@class=&quot;panel-heading accordion-toggle collapsed&quot;]</value>
      <webElementGuid>fc26d259-4df0-4f45-9a29-5ef1d4fd8e6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CateringMenuAccordion']/div[3]/a</value>
      <webElementGuid>5655b2c1-dc42-4439-98a7-07be12890be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[3]/following::a[1]</value>
      <webElementGuid>a7359db2-ce4f-4b6d-be2f-c9607cf871fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vinaigrette Dressing'])[2]/following::a[1]</value>
      <webElementGuid>f9aa21ca-0b65-4006-a1bf-23d3464af2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#Lunch')]</value>
      <webElementGuid>790582f5-748c-4420-afb5-4101bbc6db6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/a</value>
      <webElementGuid>ab8a9270-66dc-4e28-964d-8bc6a9c46d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#Lunch' and (text() = '
                                            Lunch
                                        ' or . = '
                                            Lunch
                                        ')]</value>
      <webElementGuid>28468ee7-7299-49ab-9de6-ea1758a3be41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
