<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addPassenger_button</name>
   <tag></tag>
   <elementGuidId>bccda2cd-da7a-4bdc-8806-2cc8d129f9e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PaxTab-0']/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.target-add-passenger-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>721b3ca4-5986-4042-bd00-88fb112af1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-add-passenger-button</value>
      <webElementGuid>35cdc1a0-aaf4-41b9-bbc2-8c3688f4a6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-total-passengers</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f85ebb32-a981-4413-ad1f-a0cea5cd2abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recommended-passengers</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>2473f2d6-a04f-4a57-b2b6-151dc95dc6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909577</value>
      <webElementGuid>db52ff06-a779-4658-874d-6313d284cf0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f1482625-09cf-4fd1-a552-0c34a5a5b062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-numberoflegs</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>fe2a8477-4bdb-4dc0-b747-977082981c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        ADD A PASSENGER
                                    </value>
      <webElementGuid>818c8099-a402-4357-ab26-6941bcd33a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PaxTab-0&quot;)/div[@class=&quot;ams-passenger-container center-text&quot;]/a[@class=&quot;target-add-passenger-button&quot;]</value>
      <webElementGuid>366aae51-11a1-4890-9e66-5214f7f95afc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PaxTab-0']/div[4]/a</value>
      <webElementGuid>ca11d362-d399-4c28-8775-8dfb7ab77937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ADD A PASSENGER')]</value>
      <webElementGuid>1dfc8836-8ce6-4f2f-b686-05f33f4e7c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save to My Passengers'])[3]/following::a[1]</value>
      <webElementGuid>389e4c38-31f8-46c6-9495-1688f820d18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* Required'])[3]/following::a[1]</value>
      <webElementGuid>7ead4a48-d664-42e5-9ea1-f75f5fdd2221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Luggage'])[1]/preceding::a[1]</value>
      <webElementGuid>84f72321-c68a-4dac-bdbe-f2cc86bfe169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check for None'])[1]/preceding::a[1]</value>
      <webElementGuid>0bbb1f3f-6cc0-4dcf-abf6-86c9ff872f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADD A PASSENGER']/parent::*</value>
      <webElementGuid>5df0cf32-2d64-45a3-839c-9b54962321c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>73c4634a-b283-4108-9f7f-fb555b2b57c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
                                        ADD A PASSENGER
                                    ' or . = '
                                        ADD A PASSENGER
                                    ')]</value>
      <webElementGuid>2c4b2ee4-ac3f-4e99-a937-ec646c02fb01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
