<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>done_button</name>
   <tag></tag>
   <elementGuidId>f16f8544-fb3a-479e-b7f7-b3c3a2f15771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CoffeeandTea-optionsclose']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CoffeeandTea-optionsclose</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9db1f6e-cee6-4e5a-864a-9dbd076baf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>finished-catering-selectons-button</value>
      <webElementGuid>b3dfa4db-e8e1-4c80-a9d8-d9935ad7d126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909215</value>
      <webElementGuid>e67a2463-93a1-4dc4-8c7a-a52e720dab95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CoffeeandTea-optionsclose</value>
      <webElementGuid>54f3fe57-2848-4480-9b85-4f83906ed16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemid</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>d139700b-04ca-41f8-a696-fdf8e05e4684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Coffee and Tea</value>
      <webElementGuid>908ccce2-396a-4372-9bb0-825b924a0200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>a35cdd29-1db8-4b6c-9fb4-3fa2b3898368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        Done
                                                                    </value>
      <webElementGuid>b6d8b35d-ea06-4de0-9ddf-771df2ef862c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoffeeandTea-optionsclose&quot;)</value>
      <webElementGuid>2d58a2c1-a9aa-45fa-8465-63227a95eea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CoffeeandTea-optionsclose']</value>
      <webElementGuid>cab7b385-8f88-43ed-97de-910abed1c805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='CoffeeandTea-options']/li[4]/button</value>
      <webElementGuid>f2cc5fcc-989f-4931-9388-589880a0ec36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tea'])[1]/following::button[1]</value>
      <webElementGuid>8296223b-90e5-4046-aa59-e4ba10d6380e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coffee'])[1]/following::button[1]</value>
      <webElementGuid>43926f63-831a-4359-9b22-dc3583635b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request for Leg 1'])[20]/preceding::button[1]</value>
      <webElementGuid>b98a296c-69af-49eb-a8b1-d8b20df2aacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button</value>
      <webElementGuid>7d8d1424-20b9-4d01-a2a6-70d10f897bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'CoffeeandTea-optionsclose' and (text() = '
                                                                        Done
                                                                    ' or . = '
                                                                        Done
                                                                    ')]</value>
      <webElementGuid>9b431a06-f1f2-4966-a3b5-af8775faa476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
