<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tea_checkBox</name>
   <tag></tag>
   <elementGuidId>c1464baa-b646-4ba7-861e-c2fdaffdd1ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='CoffeeandTea-options']/li[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e25c6ee9-009c-4e8d-b789-f63c1372bf3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>CoffeeandTeaTea</value>
      <webElementGuid>f87a757d-93af-4a6a-bd28-dbde82ee858b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tea</value>
      <webElementGuid>1f20595c-d0a5-47fd-9b86-473f7a5588bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoffeeandTea-options&quot;)/li[3]/label[1]</value>
      <webElementGuid>01cf060c-a14b-4adc-a754-a2f5cdbb5d60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='CoffeeandTea-options']/li[3]/label</value>
      <webElementGuid>ab1e14d9-f7c0-4409-a422-92385ff912a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coffee'])[1]/following::label[1]</value>
      <webElementGuid>7df28e0d-a94c-4138-8c16-91eb6505c1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[18]/following::label[2]</value>
      <webElementGuid>4fae8c2d-3b29-4a27-9ad9-b9066b4755f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[6]/preceding::label[1]</value>
      <webElementGuid>5abb0864-26ce-4883-92ad-9cdb5eb53deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tea']/parent::*</value>
      <webElementGuid>d22661c3-d504-4f3c-b77e-5c9e4d616751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/h4/ul/li[3]/label</value>
      <webElementGuid>945d2100-39c8-4fa0-be89-d6db23c5c70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Tea' or . = 'Tea')]</value>
      <webElementGuid>f142f4a1-a26c-4f47-8fdf-44d686604661</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
