<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>done_button</name>
   <tag></tag>
   <elementGuidId>f4ccfd62-7afc-44e9-8204-923ace99b730</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Pasta-optionsclose']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pasta-optionsclose</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e14b13f-ab0c-4cc0-b5fc-5505a8c7a07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>finished-catering-selectons-button</value>
      <webElementGuid>bff7dc3d-bf66-40d1-b2da-32ae17d2c520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909215</value>
      <webElementGuid>5ad0f907-f1be-4a43-bbfb-f9abe2e0cfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pasta-optionsclose</value>
      <webElementGuid>63878e26-fe07-4e4e-9ea2-588a4f34e948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemid</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>df166bc7-5822-4eb5-aa4c-554e39ae93d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Pasta</value>
      <webElementGuid>33ce4388-89e6-406c-8917-fdc671401f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>b069fa8e-fb9b-4d25-b702-89e49baa8586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        Done
                                                                    </value>
      <webElementGuid>32731fc1-7c22-430d-a0fa-f4975e278b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pasta-optionsclose&quot;)</value>
      <webElementGuid>58fe97b5-25be-423e-85cd-490cce65d5cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Pasta-optionsclose']</value>
      <webElementGuid>c0c22ca1-874c-4028-a425-0735c7804842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Pasta-options']/li[6]/button</value>
      <webElementGuid>6b8098bd-8650-4ed5-bbac-4049022421b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesto Sauce'])[1]/following::button[1]</value>
      <webElementGuid>acc5822e-d719-40f1-8626-b11f3f867f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alfredo Sauce'])[1]/following::button[1]</value>
      <webElementGuid>24db22ac-abd7-45f7-8618-362ca4db9cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platters'])[1]/preceding::button[1]</value>
      <webElementGuid>09d81eab-c93b-4088-9b5b-91ad3ce99da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/h4[4]/ul/li[6]/button</value>
      <webElementGuid>46036ea1-1f74-43f4-b710-057942dde64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Pasta-optionsclose' and (text() = '
                                                                        Done
                                                                    ' or . = '
                                                                        Done
                                                                    ')]</value>
      <webElementGuid>297a974a-20f0-4f6d-8e9d-bd3d4eb93bee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
