<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>marinaraSauce_checkBox</name>
   <tag></tag>
   <elementGuidId>1d089547-bdb3-4317-a261-4afa8f226890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Pasta-options']/li[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>233c3f10-f0bb-462b-abaf-290d18d26fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>PastaMarinara Sauce</value>
      <webElementGuid>bfa0badb-f50c-4695-a19d-c191b498ead4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marinara Sauce</value>
      <webElementGuid>630e873d-2f9c-4e50-b0f6-2cf4c65e656b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pasta-options&quot;)/li[3]/label[1]</value>
      <webElementGuid>44400d58-084c-47b7-a154-8f882ca3a323</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Pasta-options']/li[3]/label</value>
      <webElementGuid>a148ce5f-523b-42cb-9ef2-f43a9a7194a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Butter'])[1]/following::label[1]</value>
      <webElementGuid>8dd1867f-3d05-4644-ae8d-e1e66047decb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[17]/following::label[2]</value>
      <webElementGuid>993b3c64-28a6-4fd1-b93c-8d218b264864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alfredo Sauce'])[1]/preceding::label[1]</value>
      <webElementGuid>d566e4fc-42cc-4819-9c99-9e5995ccba88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesto Sauce'])[1]/preceding::label[2]</value>
      <webElementGuid>2c5a0351-c273-452f-b0bf-ea999b87d5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Marinara Sauce']/parent::*</value>
      <webElementGuid>cad38840-d9c2-4a5d-8bb3-54b3d153215f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/h4[4]/ul/li[3]/label</value>
      <webElementGuid>366a9702-cc62-4441-9b01-221588d9cc97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Marinara Sauce' or . = 'Marinara Sauce')]</value>
      <webElementGuid>9dedf493-3932-49aa-a091-15f539698cd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
