<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yesApply_button</name>
   <tag></tag>
   <elementGuidId>6fa6ddb0-ac1b-42e1-aaf2-57aecb41cfd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Yes'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-body > div.row > div.col-xs-12.col-xs-offset-10 > #Yes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b652f75c-4e27-47c9-b9ab-269699ee8a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>confirm-btn-small</value>
      <webElementGuid>8e7b6386-a679-42e4-bfa7-11294910534b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f1300aa-5795-4a8c-b5bb-bc9f911bb657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>7deffed3-5d22-4a17-be02-4914e75dfb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>5fe60806-324c-420b-970e-6d695a7995d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConfirmationDialog&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-xs-offset-10&quot;]/input[@id=&quot;Yes&quot;]</value>
      <webElementGuid>5d5ecd9f-e6c9-4ece-b190-32af060e8413</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Yes'])[2]</value>
      <webElementGuid>c1762c0a-a108-412a-9480-6b101f3b1437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ConfirmationDialog']/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>3d6c710e-d29f-452e-98df-6a0418066e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>3622123a-6d03-41c8-9e53-0185973fe235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'Yes']</value>
      <webElementGuid>021183cd-dbd8-4360-88e1-3e9223d7b92c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
