<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firstLabelAdd_button</name>
   <tag></tag>
   <elementGuidId>b6b8b777-6abd-4663-aa95-e381261a010f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='one-loop-all-legs-tbody']/tr/td/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.one-loop-tool-tip.move-to > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>94b3503a-bcc2-4b46-a64d-eb92d5c5f3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-loop-all-legs-tbody&quot;)/tr[1]/td[@class=&quot;one-loop-tool-tip move-to&quot;]/label[1]</value>
      <webElementGuid>ae9dca58-2d14-41e5-bd39-5f24a426dea5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='one-loop-all-legs-tbody']/tr/td/label</value>
      <webElementGuid>b01e4b23-dc5a-4124-8098-a637acee2da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/label</value>
      <webElementGuid>18f7d021-43c1-4673-ad17-8d4875162f1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
