<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hoursCheck_checkBox</name>
   <tag></tag>
   <elementGuidId>4627715d-fc56-4730-b5f5-01c8d73d16cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f69c302-e558-4101-b395-782d9ea84242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bf299a02-2d5a-401b-95b7-2fce87ff3dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>3b1fd92c-1182-40b5-824d-3d8febf8a7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountInfo&quot;)/div[@class=&quot;row target-account-detail&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-group col-xs-12 row_margin_bottom&quot;]/div[@class=&quot;target-client-account-overrides-div&quot;]/div[1]/div[@class=&quot;row col-xs-12 target-add-flight-plan-override-div&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 account-override-multi-selectlist&quot;]/span[@class=&quot;multiselect-native-select&quot;]/div[@class=&quot;btn-group&quot;]/ul[@class=&quot;multiselect-container dropdown-menu&quot;]/li[@class=&quot;active&quot;]/a[1]/label[@class=&quot;checkbox&quot;]/input[1]</value>
      <webElementGuid>912ae886-91e2-413a-b1b9-075c5fdfe2ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='4']</value>
      <webElementGuid>99dddf14-4057-4f1a-b836-cbc8da40bd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccountInfo']/div/div[5]/div/div/div[2]/div/div[3]/div[2]/div/span/div/ul/li[5]/a/label/input</value>
      <webElementGuid>4d240a9f-5456-4ccd-89c1-669500a6251d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/label/input</value>
      <webElementGuid>d98bbf16-0a0b-46ab-818f-77e8689cf497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>bb0bba17-9d3e-402d-9f35-e73149a5fc4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
