<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectAll_checkBox</name>
   <tag></tag>
   <elementGuidId>f5aef1be-8360-4f89-ae8f-a053fca78fd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='multiselect-all']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50c01330-8984-4aeb-acaf-ccae8ce82535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b3196f08-fe73-474a-bc8b-af2266f0d617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>multiselect-all</value>
      <webElementGuid>40c83a19-2d47-4c74-9fd9-a899325d8618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountInfo&quot;)/div[@class=&quot;row target-account-detail&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-group col-xs-12 row_margin_bottom&quot;]/div[@class=&quot;target-client-account-overrides-div&quot;]/div[1]/div[@class=&quot;row col-xs-12 target-add-flight-plan-override-div&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 account-override-multi-selectlist&quot;]/span[@class=&quot;multiselect-native-select&quot;]/div[@class=&quot;btn-group&quot;]/ul[@class=&quot;multiselect-container dropdown-menu&quot;]/li[@class=&quot;multiselect-item multiselect-all active&quot;]/a[@class=&quot;multiselect-all&quot;]/label[@class=&quot;checkbox&quot;]/input[1]</value>
      <webElementGuid>7e3cf2f2-4564-4888-ab86-1040c0bc43cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='multiselect-all']</value>
      <webElementGuid>07995cbf-ea48-4469-be80-a4bb1d2008d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccountInfo']/div/div[5]/div/div/div[2]/div/div[3]/div[2]/div/span/div/ul/li/a/label/input</value>
      <webElementGuid>ec1065c1-518c-4552-b5e8-b2276850ebd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>4b885bb6-4366-4430-9a7c-848631b9f651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>4c246353-043f-4d41-803c-652357734d24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
