<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>soyMilk_checkBox</name>
   <tag></tag>
   <elementGuidId>04c47493-bcb3-45aa-81d1-272a1903f382</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Milk-options']/li[6]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b9a67786-5c67-48eb-9a6f-016e88d2fbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>MilkSoy Milk</value>
      <webElementGuid>2bf7d0a4-7e46-401e-91b2-90830af7be54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Soy Milk</value>
      <webElementGuid>42ad1fe2-a0de-4aa1-9992-0b9bcef9c7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Milk-options&quot;)/li[6]/label[1]</value>
      <webElementGuid>54aa384c-5cc4-44bc-9fd7-930363e2e26b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Milk-options']/li[6]/label</value>
      <webElementGuid>84f0de6b-ea78-429f-af56-5050f2c17ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organic Milk'])[1]/following::label[1]</value>
      <webElementGuid>17e6fa5c-2a2e-459f-89c1-1bb7a6709f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skim Milk'])[1]/following::label[2]</value>
      <webElementGuid>e0c3ea6c-8dc5-4b2c-9b6f-c173852e1d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chocolate Milk'])[1]/preceding::label[1]</value>
      <webElementGuid>dc2045cf-4e03-49df-860a-672d30bfe62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[7]/preceding::label[2]</value>
      <webElementGuid>39459e24-5b02-4b55-ba49-20eaa3b70d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Soy Milk']/parent::*</value>
      <webElementGuid>0e7c03eb-f80e-435d-864b-2dd5b5334036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/h4[2]/ul/li[6]/label</value>
      <webElementGuid>4d898ceb-c46b-4955-8c78-57d5841f727b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Soy Milk' or . = 'Soy Milk')]</value>
      <webElementGuid>3a81b944-7d51-435d-a7e9-64708fb35e0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
