<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>signIn_button</name>
   <tag></tag>
   <elementGuidId>d4b23de2-0f9f-40e6-82c5-f5ed5473bfe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SelectAircraftLoginButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SelectAircraftLoginButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37ed9a6a-0706-4f0f-a83b-1bb4464ca548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary guest-submit</value>
      <webElementGuid>1de0bdeb-2b1f-4d20-bd74-173aa809d4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd087587-f764-426d-8572-8affa416ab64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SelectAircraftLoginButton</value>
      <webElementGuid>42ce0f1f-9aa7-4b71-935a-a4990edee8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>BAJ.login(this)</value>
      <webElementGuid>91d4fc43-4ab5-44b7-97ea-209edb7f4862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>3e5d5533-8c7b-4149-b616-2310eb0efaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectAircraftLoginButton&quot;)</value>
      <webElementGuid>43a906f2-dd80-4be9-acff-0219df6dd479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SelectAircraftLoginButton']</value>
      <webElementGuid>820b9a32-1efe-4464-ab86-330e05407741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SignInForm']/div/div/div/div/div[5]/input</value>
      <webElementGuid>e9bd326a-07e9-46c0-80fd-e8dd17669000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>7e8ff7f5-591b-4e00-b028-97bd1ced26f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'SelectAircraftLoginButton']</value>
      <webElementGuid>8544e7ac-2c83-47ab-9ac3-712592e0609b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
