<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>leg1_checkBox</name>
   <tag></tag>
   <elementGuidId>d6ffbe6e-994a-4a3f-8234-cd32da15b7e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[14]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.target-operator-quote-group-select.cursor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5c6a7c7-1fcb-47fc-8952-4c90220dbb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-operator-quote-group-select cursor</value>
      <webElementGuid>3083f5ac-2fdc-4b5a-974b-bfb4a0207442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-id</name>
      <type>Main</type>
      <value>910183</value>
      <webElementGuid>e7648696-6b3c-489f-9039-8615f5dbac08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-operator-quote-id</name>
      <type>Main</type>
      <value>137604</value>
      <webElementGuid>dc22f16e-c65b-4354-b9fd-73883a531468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5c6e4ddb-d012-4065-a438-b87ab985ec04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-op-quote-form&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-xs-12 target-leg-operator-quotes-group&quot;]/div[@class=&quot;target-leg-quotes-div&quot;]/input[@class=&quot;target-operator-quote-group-select cursor&quot;]</value>
      <webElementGuid>674f30e3-1446-4d09-ab1d-431fd9273301</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[14]</value>
      <webElementGuid>0d3680e1-457a-426f-b377-456a726984b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='target-op-quote-form']/div/div/div/div/div[2]/input</value>
      <webElementGuid>4f2037cb-987a-476d-a26b-5cddde618765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div[2]/input</value>
      <webElementGuid>d2a688c7-b718-4ec6-94d9-673f39594464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>c5ad56da-6a4c-4265-a211-1ff46445d7bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
