<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newTotalPrice_value</name>
   <tag></tag>
   <elementGuidId>fd267d52-c02b-4b5b-9e88-78cbe94d7556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='itinerary-container']/div/div[2]/div[2]/table/tbody/tr[11]/td[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e38ab2de-b2af-4843-be72-79e7520676d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$132,626.45</value>
      <webElementGuid>ee0cdbe9-6230-41b1-9f13-135dc48e61f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itinerary-container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;itinerary-media-table&quot;]/table[@class=&quot;top-table table&quot;]/tbody[1]/tr[11]/td[@class=&quot;numeric-align&quot;]/label[1]</value>
      <webElementGuid>9fc07348-c84e-4f99-93b4-dcbdc172f934</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='itinerary-container']/div/div[2]/div[2]/table/tbody/tr[11]/td[2]/label</value>
      <webElementGuid>ee227233-6233-444e-858b-ead158557a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Due:'])[2]/following::label[1]</value>
      <webElementGuid>3659dbb7-2567-4f31-85c6-e8ea82e44b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$40.50'])[2]/following::label[3]</value>
      <webElementGuid>aa3eb3a4-e6b5-47a4-a1af-4132290bbbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='changes'])[1]/preceding::label[2]</value>
      <webElementGuid>03fca605-2e9a-45d8-b2a8-32c29d2b14b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DECLINE'])[1]/preceding::label[2]</value>
      <webElementGuid>19d44ce8-800b-4555-9ebb-0a7bf08cd612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$132,626.45']/parent::*</value>
      <webElementGuid>c503b4d2-9d84-495f-a3fe-3f79764e1e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/table/tbody/tr[11]/td[2]/label</value>
      <webElementGuid>a897120e-9390-4d8d-91a6-a51de0318bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '$132,626.45' or . = '$132,626.45')]</value>
      <webElementGuid>6ddee833-c6f0-40de-af7a-1f01c40eccbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
