<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>noDecline_button</name>
   <tag></tag>
   <elementGuidId>ce1799be-8149-499f-b588-d8ab5f125145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.reject-button.itinerary-button.target-modal-cancel-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='No']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dad9edd5-807a-47fe-8ac7-5617bfa29412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f715e3d-bf30-499e-8042-aa4a032a48a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn reject-button itinerary-button target-modal-cancel-button</value>
      <webElementGuid>95c4e1c0-1e9f-4a02-9e84-268fbe289ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>29f8a420-c6b2-494b-8266-75907b96a6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-accept-changes&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 float-right&quot;]/input[@class=&quot;btn reject-button itinerary-button target-modal-cancel-button&quot;]</value>
      <webElementGuid>c5040451-dbeb-4645-b976-49e812e3c6a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='No']</value>
      <webElementGuid>4326bc10-56a5-45ce-b03a-315a3f78c785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='target-accept-changes']/div/div[3]/input</value>
      <webElementGuid>9275c751-a609-4413-8218-a9ac2659f14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/input</value>
      <webElementGuid>b9c0d72b-960b-4af3-a0bf-45ee906f382f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>ff1e2368-b9d0-4132-8955-476630d6cd46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
