<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>previousTotalPrice_value</name>
   <tag></tag>
   <elementGuidId>106e9fe9-be03-4f47-89e8-c458f90b58a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='itinerary-container']/div/div/div[2]/table/tbody/tr[11]/td[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0da16430-8917-4671-b6d7-08f9bdefb081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$98,573.40</value>
      <webElementGuid>0984a303-0e83-4501-a112-5b092a5ff35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itinerary-container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;itinerary-media-table&quot;]/table[@class=&quot;top-table table&quot;]/tbody[1]/tr[11]/td[@class=&quot;numeric-align&quot;]/label[1]</value>
      <webElementGuid>5bb74f5d-41c1-4003-b353-16fcd80534ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='itinerary-container']/div/div/div[2]/table/tbody/tr[11]/td[2]/label</value>
      <webElementGuid>b1428a62-f1c0-4094-b258-8b671a31504a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Due:'])[1]/following::label[1]</value>
      <webElementGuid>c50ffa58-d51b-44a9-8e1a-092d632e8c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$40.50'])[1]/following::label[3]</value>
      <webElementGuid>7b4260ad-ac7d-4864-84ff-6dbe531b5a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updated Flight Plan'])[1]/preceding::label[1]</value>
      <webElementGuid>2d0717c0-911b-44ce-96af-3473e1b5d1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leg'])[2]/preceding::label[1]</value>
      <webElementGuid>b9bc46cf-caac-41eb-8eb1-3938c72523ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$98,573.40']/parent::*</value>
      <webElementGuid>b6f1bfaf-6b99-41ad-8179-6c48b754c95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[2]/label</value>
      <webElementGuid>6ed563d3-4a31-4751-b861-19230b2f35c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '$98,573.40' or . = '$98,573.40')]</value>
      <webElementGuid>4f468285-3a3d-407b-bb0d-52c9ef779805</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
