<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yesDecline_button</name>
   <tag></tag>
   <elementGuidId>431137fb-96b3-4898-8348-c43c61a57b86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.accept-button.itinerary-button.target-decline-yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7073b09-61e8-43cd-abe8-dd0877388bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4a283590-b8a4-4e20-880f-0cebff6634b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn accept-button itinerary-button target-decline-yes</value>
      <webElementGuid>c45d4234-f39e-4766-aba2-fc00841498d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>db200c14-a15b-4200-b58d-746c5388d5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-accept-changes&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 float-right&quot;]/input[@class=&quot;btn accept-button itinerary-button target-decline-yes&quot;]</value>
      <webElementGuid>ba0675c8-a9e2-4d5d-a950-c53ddd571c05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Yes']</value>
      <webElementGuid>b62876da-d6d9-48f5-92ca-03d5a864c70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='target-accept-changes']/div/div[3]/input[2]</value>
      <webElementGuid>18c45536-6b9d-4958-b638-3a8a407528ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[2]</value>
      <webElementGuid>86fac30a-0fb2-49b1-bae0-db0ae71aeaee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>b8113bf3-ff77-43f1-b30c-afb52e10e4ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
